### ISSUE TITLE
FindItems() not fulfilled/rejected for an unauthorized request

### ISSUE THREAD

**Issue by qcom** [gautamsi/ews-javascript-api#101]
I'm calling `FindItems()` against an array of email addresses.

My authenticated Office 365 account (`../../vendor/exchange`) has Read/Manage permissions for all of these email address mailboxes except for one of them.

For the mailboxes where permissions are correct `doSomethingWithResponse()` is called correctly. But for the 1 address without permissions, the rejection callback does not get called and my `Promise.map()` over `countEmailsFromUser()` hangs.

I'm using the following code:

```javascript
import exch from '../../vendor/exchange';
import {
	Mailbox,
	FolderId,
	WellKnownFolderName,
	DateTime,
	TimeSpan,
	SearchFilter,
	ItemSchema,
	ItemView
} from 'ews-javascript-api';
import doSomethingWithResponse from './doSomethingWithResponse';

function countEmailsFromUser(email) {
	// folderId
	const userMailbox = new Mailbox(email);
	const userFolderId = new FolderId(WellKnownFolderName.SentItems, userMailbox);

	// searchFilter
	const now = moment();
	const hours = now.hours();

	const startOfToday = new DateTime(
		DateTime.Now.TotalMilliSeconds - TimeSpan.FromHours(hours).asMilliseconds()
	);
	const afterTodayFilter = new SearchFilter.IsGreaterThanOrEqualTo(
		ItemSchema.DateTimeSent,
		startOfToday
	);

	// itemView
	const itemView = new ItemView(1000);

	return exch.FindItems(userFolderId, afterTodayFilter, itemView)
		.then(function(res) {
			// called!
			doSomethingWithResponse(res);
		}, function(err) {
			// not called!
			debugger;
		});
}
```

Please let me know if I'm not error handling correctly.
I'm using v0.6.0.

**Comment by gautamsi** [comment]
I see what is happening, the code where it throws the error is not being properly caught. I am working on this.

**Comment by gautamsi** [comment]
can you build this yourself? I have fixed issue in master branch but the npm publish is still not out.

**Comment by qcom** [comment]
I should be good to wait for the release, but for the future what are the steps to build?

I checked out the repo and ran `gulp build` (also `gulp npm-prep`) but I'm unable to require/import the library.

I'm using this in a node environment without a module bundler.

**Comment by gautamsi** [comment]
After `gulp build` and `gulp npm-prep` you can install from `build\output\node\src` sub directory.

You can run `npm install <path to src as described above>` where you want to update.

**Comment by qcom** [comment]
Got it! Thank you for all the help.
