### ISSUE TITLE
Unsubscribe throws a type error

### ISSUE THREAD

**Issue by istersin** [gautamsi/ews-javascript-api#103]
When using unsubscribing a pull subscription the unsubscribe function returns a type error: 
_TypeError: Cannot read property 'Scheme' of undefined_

I pass in a valid subscription ID, any ideas what this might be?

**Comment by gautamsi** [comment]
an you provide the details how you are passing it. mask the subscription id.

**Comment by istersin** [comment]
This was a mistake on my end, unsubscribe works perfectly fine.
