### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by nofear87** [gautamsi/ews-javascript-api#104]
When I navigate to exchange.asmx I can insert my credentials (look like a htaccess prompt) and come to an site where I got informed that I have created a service. But when using the script I got 401.

```
Error in calling service, error code:401
server: Microsoft-IIS/8.5
request-id: f2bb00de-6601-445f-be6e-65bd67abde37
www-authenticate: Negotiate, NTLM
x-powered-by: ASP.NET
x-feserver: EXCHANGE02
date: Thu, 22 Sep 2016 12:52:52 GMT
content-length: 0
```

Any ideas what could went wrong? Url and credentials seems to be ok.

**Comment by gautamsi** [comment]
Have you tried https://gist.github.com/gautamsi/28211eda711e3e7dc04c? I see that it needs NTLM authentication which is not supported natively by the script. you have to use helper mentioned in gist. 

username must be in format `domain\username` or `user@domain.com` etc.

**Comment by gautamsi** [comment]
for ntlm you can also try [`ews-javascript-api-auth`](/gautamsi/ews-javascript-api-auth) npm package. 

please reopen if you still face any issue after using fix above and the new package. wait for 0.9 to use new package or build it from master branch
