### ISSUE TITLE
How to use SyncFolderItems together with LoadPropertiesForItems

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#105]
Hello,
I apologize if this questions might sound obvious. The result of `SyncFolderItems` exposes the properties `Count`, `SyncState` and `MoreChangesAvailable`, which I can access without any problem. But I would like to resolve properties of the items in the ChangeCollection using `LoadPropertiesForItems`.

I found this solutions that seems to work but using the private `changes` property:

``` js
exchange.SyncFolderItems(calenderFolderId, new ews.PropertySet(ews.BasePropertySet.IdOnly), null, MAX_ITEMS_QUERY, ews.SyncFolderItemsScope.NormalItems, syncState)
.then((params) => {
     var items = params.changes.map((change) => change.Item);
     exchange.LoadPropertiesForItems(items, propSet).then((data) => {})
}, (err) => {
});
```

Should I use the `__thisIndexer` method to access the changes and construct a list of Items? The name seems to suggests that this method is private too, isn't it?

Thanks

**Comment by istersin** [comment]
I do the same thing as you do there.. What you need is in the changes property.

**Comment by gautamsi** [comment]
You should use `__thisIndexer` this is not private, I had to work this up so that i can use `this[indexer]` from c#. 
you can iterate to `.Count` and use `__thisIndexer`

**Comment by marcoancona** [comment]
Ok thanks
