### ISSUE TITLE
Error on EmailMessage.ToRecipients.Add()

### ISSUE THREAD

**Issue by volktron** [gautamsi/ews-javascript-api#106]
In this very simple example, with everything globally scoped:

```
var ews = require('ews-javascript-api');
var ntlmXHR = require("./../../ntlmXHRApi");
var ntlmXHRApi = new ntlmXHR.ntlmXHRApi(user, password);

var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);
exch.XHRApi = ntlmXHRApi;
exch.Credentials = new ews.ExchangeCredentials(user, password);
exch.Url = new ews.Uri(host);

var msg = new ews.EmailMessage(exch);
msg.ToRecipients.Add(new ews.EmailAddress("some.email@address.com"))
```

The following error gets thrown:

```
[ComplexProperty.Changed] OnChange events not fired due to circular calling, todo: fix needed
```

Am I missing something here, or is this a bug?

**Comment by volktron** [comment]
Email gets sent, above output is inconsequential.

**Comment by ddymko** [comment]
Is that the fix for this? Ignore the error? Sure the email might send but

- why are we getting this error? 
- what can we do to address this error?
- why should we "ignore" the error?

**Comment by gautamsi** [comment]
`[ComplexProperty.Changed] OnChange events not fired due to circular calling, todo: fix needed` is not an error, this is a warning/reminder that if you have anything dependent on change `OnChange` event, this event is still in todo list and is not fired.

**Comment by gautamsi** [comment]
this should be fix now. see comment on #137 for more details.
