### ISSUE TITLE
SyncFolderItems: if the "SyncState" is invalid, none of the promise call back function is called, 

### ISSUE THREAD

**Issue by gurusamy** [gautamsi/ews-javascript-api#107]
Callback is not called, if it is invalid syncstate

```
var final = [], syncState = 'Invalid Sync State';
function invokeService() {
            exch.SyncFolderItems(new ews.FolderId(ews.WellKnownFolderName.Inbox),
                ews.PropertySet.IdOnly,
                null, 5,
                ews.SyncFolderItemsScope.NormalItems,
                syncState)
                .then(function (resp) {
                    var data = [];
                    _.forEach(resp.changes, function (val) {
                        data.push({id: val.Item.Id.UniqueId.toString(), changeKey: val.Item.Id.ChangeKey.toString()});
                    });
                    final.push({
                        data: data,
                        syncState: resp.syncState
                    });
                    if (resp.moreChangesAvailable) {
                        return invokeService();
                    }
                    res.send(final);
                }, function (errors) {
                    res.send(errors);
                }, function (errors) {
                    res.send(errors);
                });
    }
    invokeService();
```

below is the parsed response from service

```
SyncFolderItemsResponse: {
            __prefix: 'm',
            __type: 'SyncFolderItemsResponse',
            ResponseMessages: {
                __prefix: 'm',
                __type: 'ResponseMessages',
                SyncFolderItemsResponseMessage: {
                    __prefix: 'm',
                    __type: 'SyncFolderItemsResponseMessage',
                    ResponseClass: 'Error',
                    MessageText: 'Synchronization state data is corrupt or otherwise invalid.',
                    ResponseCode: 'ErrorInvalidSyncStateData',
                    DescriptiveLinkKey: '0',
                    SyncState: null,
                    IncludesLastItemInRange: 'true'
                }
            }
        }
```

`<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Header><h:ServerVersionInfo MajorVersion="15" MinorVersion="0" MajorBuildNumber="847" MinorBuildNumber="46" Version="V2_8" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"/></s:Header><s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><m:SyncFolderItemsResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><m:ResponseMessages><m:SyncFolderItemsResponseMessage ResponseClass="Error"><m:MessageText>Synchronization state data is corrupt or otherwise invalid.</m:MessageText><m:ResponseCode>ErrorInvalidSyncStateData</m:ResponseCode><m:DescriptiveLinkKey>0</m:DescriptiveLinkKey><m:SyncState/><m:IncludesLastItemInRange>true</m:IncludesLastItemInRange></m:SyncFolderItemsResponseMessage></m:ResponseMessages></m:SyncFolderItemsResponse></s:Body></s:Envelope>`

**Comment by gautamsi** [comment]
looking into it

**Comment by gautamsi** [comment]
I tested this scenario, the promise should be rejected with `ServiceResponseException` object which has `Response` property of `SyncFolderItemsResponse` type, you can read `ErrorMessage` when `Response.Result===ews.ServiceResult.Error`.

Try the latest npm

**Comment by gautamsi** [comment]
closing as no response to update.
