### ISSUE TITLE
DateTimeReceived causes crash

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#108]
Some events do not have the DateTimeReceived property. 
When I try to check if the property exists with `if (item.DateTimeReceived) {}` the application crashes
with the following error:

``` js
‌TypeError: Cannot read property 'toString' of null
    at t.wrapWasThrown (eval at undefined, <anonymous>:204:85)
```

Or should I use a different method to check is a property exists in the Item before trying to retrieve it?

**Comment by gautamsi** [comment]
you may want to wrap this in `try..catch`. I can take a look later to improve.

**Comment by gautamsi** [comment]
initial peek suggests that how thos is designed by Microsoft. you can use [TryGetProperty or GetLoadedPropertyDefinitions](https://social.msdn.microsoft.com/Forums/en-US/3faf56b9-3146-4cda-ac3d-e78f24cf7cba/ews-managed-api-11-how-to-check-whether-the-property-is-loaded-in-exchange-object-task?forum=exchangesvrdevelopment)
