### ISSUE TITLE
Appointment: Recurrence is always null

### ISSUE THREAD

**Issue by gurusamy** [gautamsi/ews-javascript-api#109]
Please see the below xml response response. In the serialized object Recurrence is always NULL.

` <t:CalendarItem>
                                <t:ItemId Id="AAMkADg0YmE4MWRlLWRlNjctNDViYi1hOTAyLWQ5MTBhOWZjNjM3ZgBGAAAAAABbzj0TbEKKRLILnyD3/e6QBwDjscDb6oj3T5NpGFPlDeJAAAAAAAEOAADjscDb6oj3T5NpGFPlDeJAAACdOCw7AAA=" ChangeKey="DwAAABYAAADjscDb6oj3T5NpGFPlDeJAAACdOO+t"/>
                                <t:ParentFolderId Id="AQMkADg0YmE4MWRlLWRlNjctNDViYgAtYTkwMi1kOTEwYTlmYzYzN2YALgAAA1vOPRNsQopEsgufIPf97pABAOOxwNvqiPdPk2kYU+UN4kAAAAIBDgAAAA==" ChangeKey="AQAAAA=="/>
                                <t:ItemClass>IPM.Appointment</t:ItemClass>
                                <t:Subject>Every Tuesday meeting - testing  </t:Subject>
                                <t:Sensitivity>Normal</t:Sensitivity>
                                <t:Body BodyType="HTML" IsTruncated="false">&lt;html&gt;&#xD;\n&lt;head&gt;&#xD;\n&lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8"&gt;&#xD;\n&lt;style type="text/css" style="display:none;"&gt;&lt;!-- P {margin-top:0;margin-bottom:0;} --&gt;&lt;/style&gt;&#xD;\n&lt;/head&gt;&#xD;\n&lt;body dir="ltr"&gt;&#xD;\n&lt;div id="divtagdefaultwrapper" style="font-size:12pt;color:#000000;font-family:Calibri,Arial,Helvetica,sans-serif;"&gt;&#xD;\n&lt;p&gt;Sample Event created by Guru for testing&lt;/p&gt;&#xD;\n&lt;p&gt;&lt;br&gt;&#xD;\n&lt;/p&gt;&#xD;\n&lt;p&gt;thanks,&lt;/p&gt;&#xD;\n&lt;p&gt;Guru&lt;/p&gt;&#xD;\n&lt;/div&gt;&#xD;\n&lt;/body&gt;&#xD;\n&lt;/html&gt;&#xD;\n</t:Body>
                                <t:Attachments>
                                    <t:FileAttachment>
                                        <t:AttachmentId Id="AAMkADg0YmE4MWRlLWRlNjctNDViYi1hOTAyLWQ5MTBhOWZjNjM3ZgBGAAAAAABbzj0TbEKKRLILnyD3/e6QBwDjscDb6oj3T5NpGFPlDeJAAAAAAAEOAADjscDb6oj3T5NpGFPlDeJAAACdOCw7AAABEgAQAMQtWE0BXwlLnWiRSLHi7S4="/>
                                        <t:Name>Payment Confirmation.pdf</t:Name>
                                        <t:ContentType>application/pdf</t:ContentType>
                                        <t:ContentId>6217230C51E5F1459B4027D66981C26C@namprd16.prod.outlook.com</t:ContentId>
                                        <t:Size>194392</t:Size>
                                        <t:LastModifiedTime>2016-10-05T22:24:32</t:LastModifiedTime>
                                        <t:IsInline>false</t:IsInline>
                                        <t:IsContactPhoto>false</t:IsContactPhoto>
                                    </t:FileAttachment>
                                </t:Attachments>
                                <t:DateTimeReceived>2016-10-05T22:25:16Z</t:DateTimeReceived>
                                <t:Size>200853</t:Size>
                                <t:Importance>Normal</t:Importance>
                                <t:IsSubmitted>false</t:IsSubmitted>
                                <t:IsDraft>false</t:IsDraft>
                                <t:IsFromMe>false</t:IsFromMe>
                                <t:IsResend>false</t:IsResend>
                                <t:IsUnmodified>false</t:IsUnmodified>
                                <t:DateTimeSent>2016-10-05T22:25:16Z</t:DateTimeSent>
                                <t:DateTimeCreated>2016-10-05T22:25:16Z</t:DateTimeCreated>
                                <t:ResponseObjects>
                                    <t:AcceptItem/>
                                    <t:TentativelyAcceptItem/>
                                    <t:DeclineItem/>
                                    <t:ReplyToItem/>
                                    <t:ReplyAllToItem/>
                                    <t:ForwardItem/>
                                </t:ResponseObjects>
                                <t:ReminderDueBy>2016-10-11T15:00:00Z</t:ReminderDueBy>
                                <t:ReminderIsSet>true</t:ReminderIsSet>
                                <t:ReminderNextTime>2016-10-11T14:45:00Z</t:ReminderNextTime>
                                <t:ReminderMinutesBeforeStart>15</t:ReminderMinutesBeforeStart>
                                <t:DisplayCc/>
                                <t:HasAttachments>true</t:HasAttachments>
                                <t:Culture>en-US</t:Culture>
                                <t:EffectiveRights>
                                    <t:CreateAssociated>false</t:CreateAssociated>
                                    <t:CreateContents>false</t:CreateContents>
                                    <t:CreateHierarchy>false</t:CreateHierarchy>
                                    <t:Delete>true</t:Delete>
                                    <t:Modify>true</t:Modify>
                                    <t:Read>true</t:Read>
                                    <t:ViewPrivateItems>true</t:ViewPrivateItems>
                                </t:EffectiveRights>
                                <t:LastModifiedName>Conner Carter</t:LastModifiedName>
                                <t:LastModifiedTime>2016-10-05T22:25:16Z</t:LastModifiedTime>
                                <t:IsAssociated>false</t:IsAssociated>
                                <t:WebClientReadFormQueryString>?ItemID=AAMkADg0YmE4MWRlLWRlNjctNDViYi1hOTAyLWQ5MTBhOWZjNjM3ZgBGAAAAAABbzj0TbEKKRLILnyD3%2Fe6QBwDjscDb6oj3T5NpGFPlDeJAAAAAAAEOAADjscDb6oj3T5NpGFPlDeJAAACdOCw7AAA%3D&amp;exvsurl=1&amp;viewmodel=CalendarItemDetailsViewModelFactory</t:WebClientReadFormQueryString>
                                <t:WebClientEditFormQueryString>?ItemID=AAMkADg0YmE4MWRlLWRlNjctNDViYi1hOTAyLWQ5MTBhOWZjNjM3ZgBGAAAAAABbzj0TbEKKRLILnyD3%2Fe6QBwDjscDb6oj3T5NpGFPlDeJAAAAAAAEOAADjscDb6oj3T5NpGFPlDeJAAACdOCw7AAA%3D&amp;exvsurl=1&amp;viewmodel=ComposeCalendarItemViewModelFactory</t:WebClientEditFormQueryString>
                                <t:ConversationId Id="AAQkADg0YmE4MWRlLWRlNjctNDViYi1hOTAyLWQ5MTBhOWZjNjM3ZgAQABeqDV0YK05EgdmNrWgCXbQ="/>
                                <t:Flag>
                                    <t:FlagStatus>NotFlagged</t:FlagStatus>
                                </t:Flag>
                                <t:InstanceKey>AQAAAAAAAQ4BAAAAnTgsOwAAAAA=</t:InstanceKey>
                                <t:EntityExtractionResult/>
                                <t:UID>040000008200E00074C5B7101A82E00800000000792A5A3E571FD20100000000000000001000000017728BC05EC29640A69D0B5711B9F83F</t:UID>
                                <t:DateTimeStamp>2016-10-05T22:25:10Z</t:DateTimeStamp>
                                <t:Start>2016-10-11T15:00:00Z</t:Start>
                                <t:End>2016-10-11T15:30:00Z</t:End>
                                <t:IsAllDayEvent>false</t:IsAllDayEvent>
                                <t:LegacyFreeBusyStatus>Tentative</t:LegacyFreeBusyStatus>
                                <t:Location>Pleasanton, California, United States</t:Location>
                                <t:IsMeeting>true</t:IsMeeting>
                                <t:IsCancelled>false</t:IsCancelled>
                                <t:IsRecurring>true</t:IsRecurring>
                                <t:MeetingRequestWasSent>false</t:MeetingRequestWasSent>
                                <t:IsResponseRequested>true</t:IsResponseRequested>
                                <t:CalendarItemType>RecurringMaster</t:CalendarItemType>
                                <t:MyResponseType>NoResponseReceived</t:MyResponseType>
                                <t:Duration>PT30M</t:Duration>
                                <t:TimeZone>Pacific Standard Time</t:TimeZone>
                                <t:AppointmentSequenceNumber>0</t:AppointmentSequenceNumber>
                                <t:AppointmentState>3</t:AppointmentState>
                                <t:Recurrence>
                                    <t:WeeklyRecurrence>
                                        <t:Interval>1</t:Interval>
                                        <t:DaysOfWeek>Tuesday</t:DaysOfWeek>
                                        <t:FirstDayOfWeek>Sunday</t:FirstDayOfWeek>
                                    </t:WeeklyRecurrence>
                                    <t:NoEndRecurrence>
                                        <t:StartDate>2016-10-11-07:00</t:StartDate>
                                    </t:NoEndRecurrence>
                                </t:Recurrence>
                                <t:FirstOccurrence>
                                    <t:ItemId Id="AAMkADg0YmE4MWRlLWRlNjctNDViYi1hOTAyLWQ5MTBhOWZjNjM3ZgFRAAgI0/Fpi0hAAEYAAAAAW849E2xCikSyC58g9/3ukAcA47HA2+qI90+TaRhT5Q3iQAAAAAABDgAA47HA2+qI90+TaRhT5Q3iQAAAnTgsOwAAEA==" ChangeKey="DwAAABYAAADjscDb6oj3T5NpGFPlDeJAAACdOO+t"/>
                                    <t:Start>2016-10-11T15:00:00Z</t:Start>
                                    <t:End>2016-10-11T15:30:00Z</t:End>
                                    <t:OriginalStart>2016-10-11T15:00:00Z</t:OriginalStart>
                                </t:FirstOccurrence>
                                <t:AllowNewTimeProposal>true</t:AllowNewTimeProposal>
                                <t:StartWallClock>2016-10-11T08:00:00-07:00</t:StartWallClock>
                                <t:EndWallClock>2016-10-11T08:30:00-07:00</t:EndWallClock>
                                <t:StartTimeZoneId>Pacific Standard Time</t:StartTimeZoneId>
                                <t:EndTimeZoneId>Pacific Standard Time</t:EndTimeZoneId>
                                <t:IntendedFreeBusyStatus>Busy</t:IntendedFreeBusyStatus>
                                <t:IsOrganizer>false</t:IsOrganizer>
                            </t:CalendarItem>`

**Comment by gautamsi** [comment]
looking into it. missed few lines in code porting 😢

**Comment by gautamsi** [comment]
recurrence range pattern is fixed, no longer null .
