### ISSUE TITLE
GetRooms has no method 'WriteToXml'

### ISSUE THREAD

**Issue by istersin** [gautamsi/ews-javascript-api#110]
When issuing a GetRooms request for a certain room list, I get the following: 
_Object roomlist@roomlist.com has no method 'WriteToXml'_

Looking at GetRoomsRequest I see this:

`GetRoomsRequest.prototype.WriteElementsToXml = function (writer) {
        //this.RoomList.WriteToXml(writer, XmlNamespace.Messages, XmlElementNames.RoomList);
        this.RoomList.WriteToXml(writer, XmlElementNames_1.XmlElementNames.RoomList, XmlNamespace_1.XmlNamespace.Messages); //info: temp workaround github #52 
    };`

I guess there's no method on this.RoomList. Or is it related to #52 ?

**Comment by gautamsi** [comment]
looks like you are passing incorrect parameter. can you provide relevant code, I can fix it for you.

**Comment by istersin** [comment]
I used a plain string as a parameter to the GetRooms request, instead of the ews.EmailAddress object, I rushed and made stupid mistake.
