### ISSUE TITLE
Some time ews request did not return response

### ISSUE THREAD

**Issue by alkasain** [gautamsi/ews-javascript-api#111]
Hi Gautam,

We are using exchange GetUserSettings, GetUserAvailability, FindAppointments and appointment.Save feature using ews javascript api. Some time the esw request executes and then did not return response i.e. neither of success/error/complete is returned and everything stuck. Could you please suggest why this happen or any workaround to handle this scenario.

Thanks,
Alka Saini

**Comment by gautamsi** [comment]
do you have specific scenario to make it little easier in debugging?

**Comment by alkasain** [comment]
We face this issue while GetUserSettings and appointment.Save. I tried to set timeout for the request but I think its not implemented. I found this code block in ExchangeServiceBase.js:

request.Timeout = this.Timeout; //todo: implement this within IPromise

To be more specific, we wanted to set timeout for the ews request, So that if promise is not resolved then we can cancel the request.

Thanks,
Alka Saini

**Comment by gautamsi** [comment]
I have to link this to promise and xhr re-implementation #94 it will take some time.

**Comment by gautamsi** [comment]
timeout is not yet implemented even though the #131 pr is merged. 

you can implement using BlueBird promise - http://bluebirdjs.com/docs/api/timeout.html

**Comment by gautamsi** [comment]
you can use timeout value with Bluebird.
