### ISSUE TITLE
Appointment issues

### ISSUE THREAD

**Issue by alitriki** [gautamsi/ews-javascript-api#116]
Hello,
I just found that there are several issues with tha **Appintment** class.

when I try to use the setters I found in the doc like :
````javascript
 var appointment= new ews.Appointment(exch);
appointment.Body(new ews.MessageBody("This is a generated Appointment.");
//OR
appointment.Start(Some_Date); 
// AND many others
````
this raises an exception :

````
ews-javascript-api/js/Core/PropertyBag.js:270                                                                            
            throw serviceException.exception;                                          
            ^                                                                          
null                                               
````
But after some digging I found you can assign values like this : 
````javascript
appointment.Body = new ews.MessageBody("This is a generated Appointment.");
````
So I just wanted to point that out for any users of this API who are having the same exception or maybe for doc update.

**Comment by gautamsi** [comment]
thanks for pointing out, can you provide me which document you are referring to?

**Comment by alitriki** [comment]
I'm using this [link](http://ews-javascript-api.github.io/api/classes/core_serviceobjects_items_appointment.appointment.html) to see the constructors, list of methods and accessors.

**Comment by gautamsi** [comment]
that is API, the property has getter and setter which is documented that way, when you use js setter property you do `obj.Prop = new MessageBody(xyz);`

**Comment by alitriki** [comment]
Ok thanks :+1:
