### ISSUE TITLE
Use this API in thunderbird addon

### ISSUE THREAD

**Issue by guderkar** [gautamsi/ews-javascript-api#118]
Hello gautamsi, sorry to bother again. I'd like to ask if it's possible to use this api directly in thunderbird extension. My current solution is bundling nodejs binary within addon and then making a new process each time I need to do something.

**Comment by gautamsi** [comment]
I have not tested this scenario, if it is using, node process, it should work, let me know if you face any issue, I can work on resolving this.

**Comment by guderkar** [comment]
Yeah it works when I call nodejs binary from my javascript handler. But it would be better to use api objects directly in handler.

**Comment by gautamsi** [comment]
can you setup a sample repo and help me with how you want to access the API

**Comment by guderkar** [comment]
Hello after some while I gave up on trying to load module directly. So I stuck up with calling a Node.js process each time.

I have just finished the add-on. Link: https://github.com/guderkar/MExInt

Thanks for the all help with using your API :-)
