### ISSUE TITLE
Calendar Details always return objects busyType ="busy" 

### ISSUE THREAD

**Issue by rkiran16** [gautamsi/ews-javascript-api#12]
Hi,

First of all I want to say thanks for the great module.I am implementing outlook dashboard  which lists out  meeting rooms that are available  and booked.When i make a call to "GetUserAvailability" which always returns Calendar Details that has only busyType="busy" . I think i am missing some thing or configuration is incorrect. Here is code I am using

var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010);
exch.Credentials = new ews.ExchangeCredentials("*****", "*****");
exch.Url = new ews.Uri("https://colarnexch02.test.com/ews/exchange.asmx");
var attendee = [new ews.AttendeeInfo("***********************")];
var timeWindow = new ews.TimeWindow(ews.DateTime.Now, new ews.DateTime(ews.DateTime.Now.TotalMilliSeconds +ews.TimeSpan.FromHours(24).asMilliseconds()));

exch.GetUserAvailability(attendee, timeWindow, ews.AvailabilityData.FreeBusy)

This is output i get : 

 GetUserAvailabilityResponse: 
      { FreeBusyResponseArray: 
         { FreeBusyResponse: 
            { ResponseMessage: { ResponseClass: 'Success', ResponseCode: 'NoError' },
              FreeBusyView: 
               { FreeBusyViewType: 'Detailed',
                 CalendarEventArray: 
                  { __type: 'CalendarEventArray',
                    CalendarEvent: 
                     [ { __type: 'CalendarEvent',
                         StartTime: '2016-03-01T14:30:00',
                         EndTime: '2016-03-01T15:00:00',
                         BusyType: 'Busy',
                         CalendarEventDetails: 
                          { __type: 'CalendarEventDetails',
                            ID: '00000000AB34FCBB2DD5D5439F00576C34BC890F0700A7104A6AE99E604A9316B97E9A390B880000003168AF0000A7104A6AE99E604A9316B97E9A390B880000007B4ED50000',
                            Subject: 'Dave Adam',
                            Location: '***********************',
                            IsMeeting: 'true',
                            IsRecurring: 'true',
                            IsException: 'false',
                            IsReminderSet: 'false',
                            IsPrivate: 'false' } },

Thanks in Advance.

**Comment by gautamsi** [comment]
CalendarEventDetails is for any entry in Calendar, it can not return any entry which is not there :) It would say BusyType:Free if there is an event in calendar but it's availability is marked as "Free". you can figure out that anything not returned is free time in calendar. 

see more details about the operation here https://msdn.microsoft.com/en-us/library/aa564001(v=exchg.150).aspx

try this example - https://msdn.microsoft.com/EN-US/library/office/dn643673(v=exchg.150).aspx

see if GetUserAvailability overload with AvailabilityOption helps you http://ews-javascript-api.github.io/api/classes/exchangeservice.html#getuseravailability

```js
var options = new AvailabilityOptions();
        options.RequestedFreeBusyView = FreeBusyViewType.FreeBusyMerged;// or FreeBusyViewType.DetailedMerged 
        options.MergedFreeBusyInterval  = 60;        
       exch.GetUserAvailability(attendee, timeWindow, ews.AvailabilityData.FreeBusy, options)
```
after promise is resolved, use result variable
```js
.then(function(result){
var mergedstatus = result.AttendeesAvailability.Responses[0].MergedFreeBusyStatus
//do something
});
```
for example if you request TimeWindow from 00:00:00 to 23:59:59 , it may give you `MergedFreeBusyStatus` as  `[0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0]` 
This means user is free for first 8 hours (60 min * 8); busy 8:00 AM to 10:00 AM (clock start at 0, so after 8 hours it is 8:00 AM) then free for rest of the day.

See Remarks section at https://msdn.microsoft.com/en-us/library/aa566048(v=exchg.150).aspx

**Comment by rkiran16** [comment]
Thank you Gautham .I will try that....that definitely make sense.

**Comment by rkiran16** [comment]
Hey Gautham, Quick question : 

This works fine when I run the code on the server side where as if i do the same thing on client side it throws an error saying " Error Calling Service : Error Code Undefined" .Any Idea ?

**Comment by gautamsi** [comment]
you meant running in browser? I have not tested browser operations. I need to work on unit tests for browser and node, didnot have time. 

as of now testing is manual for each piece of code I am porting.

**Comment by gautamsi** [comment]
I also remember, running in browser has a limitation. you can only use it when you disable security in chrome. Disabling security in Chrome stops using OPTIONS pre-call for CORS. Exchange WebService does not implement HTTP OPTOPNS verb, essentially disabling CORS.

**Comment by gautamsi** [comment]
@rkiran16 if you want browser based script, still have to use webpack like optimizer. CORS is still the issue. but you can run in Electron/NW.js renderer process (webview)
