### ISSUE TITLE
Mail attachment problem  

### ISSUE THREAD

**Issue by NerminMujagic** [gautamsi/ews-javascript-api#126]
Hello,
Currently I am having a problem on sending a attachment email over the ews library on Exchange versions lower than 2013 .

I followed the instructions on the wiki: https://github.com/gautamsi/ews-javascript-api/wiki/Send-Attachment and it dose not work on EWS versions < 2013 it sends the email but with no files.

**Comment by gautamsi** [comment]
looks like version issue. some code still needs be updates. it should work with Exchange 2010_SP2 version (I have tested)

**Comment by gautamsi** [comment]
should work now.
