### ISSUE TITLE
Can this library be used in new Typescript projects?

### ISSUE THREAD

**Issue by robertohuertasm** [gautamsi/ews-javascript-api#136]
Hi, I'm trying to use this library but it seems to be impossible to get my Typescript compiler to find the typings. 

I've finally modified the `package.json` and set `typings: "typings/ExchangeWebService.d.ts"` but whenever I try to compile the app now I get an error about `moment.js typings`:

![image](https://cloud.githubusercontent.com/assets/696981/20897416/80d0b8da-bb22-11e6-8b03-ac1e6fff1cd5.png)

Any hints? Why not to publish the npm package with `declaration: true`?

**Comment by gautamsi** [comment]
already fixed in #131 once it is merged, a new version will be available. please review the pull and provide feedback.

**Comment by gautamsi** [comment]
#131 is merged. you can build from source for this or you can also wait for the next npm publish. to buid
`gulp build && gulp build-typedef && gulp npm-prep`

once build, install from folder `build/output/node/src`
