### ISSUE TITLE
Folder.FindItems(filter,view) broken

### ISSUE THREAD

**Issue by Pierre-Felber** [gautamsi/ews-javascript-api#138]
Bug (Typo) at [Folder.ts Line 374](https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Core/ServiceObjects/Folders/Folder.ts#L374)

should be

> if (argsLength >= 2) {

**Comment by gautamsi** [comment]
can you send a PR?

**Comment by Pierre-Felber** [comment]
why not just change 3 to 2 and be done, i would need to fork, clone, push, create pr
1 second vs. 15 minutes

**Comment by gautamsi** [comment]
I have other branches to publish, Will publish soon.
