### ISSUE TITLE
FindItems With Custom PropertySet Hangs On Last Item

### ISSUE THREAD

**Issue by benne-bo** [gautamsi/ews-javascript-api#139]
When I run exch.FindItems() with the following PropertySet the process hangs on the last item where it can't log the ItemId as a Loading property:

       `calview = new ews.CalendarView(startdate, enddate);

        var PropertySet = new ews.PropertySet();
        PropertySet.Add(ews.ItemSchema.Id);
        PropertySet.Add(ews.ItemSchema.Subject);
        PropertySet.Add(ews.AppointmentSchema.Location);
        PropertySet.Add(ews.AppointmentSchema.Start);
        PropertySet.Add(ews.AppointmentSchema.End);
        PropertySet.Add(ews.ItemSchema.DateTimeCreated);
        PropertySet.Add(ews.AppointmentSchema.Categories);
        PropertySet.Add(ews.ItemSchema.LastModifiedName);

        calview.PropertySet = PropertySet;
        filter = null;

        exch.FindItems(new ews.FolderId(ews.WellKnownFolderName.Calendar, new ews.Mailbox(settings.ews.mailbox, "SMTP")), filter, calview) 
               .then(function (res) {
               {...}`

**Comment by gautamsi** [comment]
looks like I missed this, do you still have issues? there were number of updates including Promise rewrite which may have solved your problem.
