### ISSUE TITLE
SubscribeToPullNotifications returns InnerException

### ISSUE THREAD

**Issue by omardlhz** [gautamsi/ews-javascript-api#149]
Im trying to subscribe to pull notifications to the Calendar folder, but for some reason I'm getting
~~~~javascript
{"InnerException":null,"message":"The collection is empty.","ParamName":"The collection is empty."}
~~~~

This is my code:

~~~~javascript
exch.SubscribeToPullNotifications(new ews.FolderId(WellKnownFolderName.Calendar, new ews.Mailbox("test@testdomain.com.co")), 1440, null, [ews.EventType.Created, ews.EventType.Modified]);
~~~~

My authentication is working perfectly, I based my code from the EWS documentation.

**Comment by gautamsi** [comment]
you have to wrap first parameter in array, try this:
`exch.SubscribeToPullNotifications([new ews.FolderId(WellKnownFolderName.Calendar, new ews.Mailbox("test@testdomain.com.co"))], 1440, null, [ews.EventType.Created, ews.EventType.Modified]);
`

here is c# method signature, same is used in this, `IEnumerable<>` becomes `Array<>`
```cs
public PullSubscription SubscribeToPullNotifications(
	IEnumerable<FolderId> folderIds,
	int timeout,
	string watermark,
	params EventType[] eventTypes
)

```

**Comment by omardlhz** [comment]
I got this to work, forgot to close it, thank you!
