### ISSUE TITLE
Problems with Recurrence.RelativeMonthlyPattern

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#151]
There seems to be a couple of problems in `Recurrence.RelativeMonthlyPattern.ts`:
- zero is a valid value for both `DayOfTheWeek` and `DayOfTheWeekIndex` but the validation method
```

        if (!this.dayOfTheWeek) {
            throw new ServiceValidationException(Strings.DayOfTheWeekMustBeSpecifiedForRecurrencePattern);
        }

        if (!this.dayOfTheWeekIndex) {
            throw new ServiceValidationException(Strings.DayOfWeekIndexMustBeSpecifiedForRecurrencePattern);

```
wrongly rejects this values. Validation should be `this.dayOfTheWeek === null`.

- the method `InternalWritePropertiesToXml` of this class only contains a copy of the code of the validation method. Probably something is missing there :)

**Comment by marcoancona** [comment]
The first issue also affects `Recurrence.RelativeYearlyPattern.ts`.

**Comment by marcoancona** [comment]
Would it be possible to have these last changes into the dev brench so I can get it by npm next?

**Comment by gautamsi** [comment]
this is added to @next on npm.

**Comment by marcoancona** [comment]
Thanks
