### ISSUE TITLE
getResponseHeader should be case-insensitive

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#152]
The method `getResponseHeader()` in `XHRDefaults.ts` should be case-insensitive, in order to comply with https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getResponseHeader

This currently causes a bug in the Autodiscover service (`GetEndpointsFromHttpResponse()`) where flags (ie "X-SOAP-Enabled') are checked against the response header which is lowercase:
```js
 { 'cache-control': 'private',
     'content-type': 'text/html',
     server: 'Microsoft-IIS/7.5',
     'x-soap-enabled': 'True',
     'x-wssecurity-enabled': 'True',
     'x-wssecurity-for': 'None',
     'x-aspnet-version': '2.0.50727',
     ...
}
```
As a result I get always only the Legacy flag.

**Comment by gautamsi** [comment]
it may take some time, for time being you can change the method to do case insensitive lookup.

**Comment by gautamsi** [comment]
16b474f60c87c91b6f6ea16566622a587c939909 should have fixed casing issue. re open if this is an issue
