### ISSUE TITLE
appointment.Save() doesn't create appointment.

### ISSUE THREAD

**Issue by omardlhz** [gautamsi/ews-javascript-api#154]
When I try to create an appointment I always get the following error:

```[DateTimePropertyDefinition.GetConvertedDateTime] TimeZone info could be misleading, It should be used as UTC in all cases until fixed ```

This is my code:

````
 var appointment = new Appointment(exch);

appointment.Subject = appointmentData.Subject;
appointment.Body = "";
appointment.Start = new DateTime('2016-12-12 12:00:00');
appointment.End = appointment.Start.Add(2, 'hour');
appointment.Location = appointmentData.Location;
appointment.Save(SendInvitationsMode.SendToAllAndSaveCopy);

````

What's wrong with the timezone?

**Comment by omardlhz** [comment]
is DateTimeKind implemented? I'm trying to pass Start and End time as UTC but I've had no luck, I get ```TypeError: Cannot set property 'kind' of undefined

**Comment by gautamsi** [comment]
its not implemented. I am working part time on this library these days. TimeZone is next major change. the line you get in the log should be a logging only, should not be blocking your code. all the calls should be UTC by default, you can have to track the time changes yourself for time being

**Comment by omardlhz** [comment]
@gautamsi when I use DateTime.UtcNow the appointment gets added, but when I use another date it doesn't. How do I do a UTC call?

**Comment by omardlhz** [comment]
I have to add, thank you very much for your amazing work!

**Comment by gautamsi** [comment]
you may want to convert the date/time to utc, could be that if you are using any other date not corresponding to a future utc date/time (even a min later, when treated by EWS) it sees them as past date and fail.

**Comment by gautamsi** [comment]
timezone is implemented recently, let me know if it is still an issue.
