### ISSUE TITLE
Excessive console output

### ISSUE THREAD

**Issue by rousselle** [gautamsi/ews-javascript-api#155]
When I sync mail or calendars I see a great deal of console output. Is there any way to reduce this? I am on 0.6.0. Is there any change in the amount of console logging in later releases? Thanks

**Comment by gautamsi** [comment]
any reason you are not upgrading to 0.8?

try setting `EwsLogging.DebugLogEnabled = false` to remove all the verbose messages.

**Comment by rousselle** [comment]
We haven't gone to 0.8.0 because everything has been good with 0.6.

Thanks for the help with DebugLogEnabled. That was what I needed.
