### ISSUE TITLE
AllDayEvent on Exchange2007_SP1?

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#156]
Is it possible any-how to create daily events with Exchange2007_SP1? The problem is that I get:
```
Error: 'StartTimeZone required when setting the Start, End, IsAllDayEvent, or Recurrence properties.
```

but if I set StartTimeZone, I get
```
Error: Error: MeetingTimeZone.ts - WriteAttributesToXml : Not implemented.
```

I know that TimeZone is not implemented, but is there a way to create daily events (in UTC)?

**Comment by gautamsi** [comment]
let me work for this. can not commit on timeline though 😢

**Comment by gautamsi** [comment]
you really want to use 2007_SP1??
