### ISSUE TITLE
Updating appointment does not update meeting's attendees

### ISSUE THREAD

**Issue by inkirby** [gautamsi/ews-javascript-api#162]
I've tried to update a meeting by changing it's subject, time, adding new attendees and removing some attendees, but the attendees in the `RequiredAttendees` is not updated.

I followed the EWS Managed API on [Adding and removing meeting attendees](https://msdn.microsoft.com/en-us/library/office/dd633620(v=exchg.80).aspx), but no attendee changed in the appointment.
TL;DR: I bind an appointment, use `Add` or `RemoveAt` on `appointment.RequiredAttendees`, then call `appointment.Update`.

I also tried `ExchangeService.UpdateItems` but doesn't work as well.

It seems like the output XML doesn't contain any attendee data.
Do you have any suggestions?

**Comment by gautamsi** [comment]
use `npm install ews-javascript-api@next`

if you use ntlm/cookie auth, you will also need to use `npm-javascript-api-auth` going forward, see the github page of auth library for usage detail.

**Comment by inkirby** [comment]
I've tried `ews-javascrpit-api@next` with `ews-javascript-api-auth` but I got an error instead:

> ServiceResponseException - An object within a change description must contain one and only one property to modify.

Can you help me with this?

**Comment by gautamsi** [comment]
provide example code to reproduce this.

does this happen with `ntlm` only or with `basic` authentication as well?

**Comment by inkirby** [comment]
I'm testing on 2 servers - `Exchange 2010` with `NTLM`, and `Office 365` with `basic`.

My implementation works on `Office 365` but not my local `Exchange 2010`, not sure if the server version or authentication cause the problem.

The code is actually long, so I will try to paste only some of it:
1. I configure my ews with NTLM if the server need it with `ews.ConfigurationApi.ConfigureXHR(new ewsAuth.ntlmAuthXhrApi(user, pass, true));` (certs are locally self-signed).
2. I bind the `appointment` with `ews.Appointment.Bind(exchangeService, new ews.ItemId(theId))`
3. I changed some appointment details with
`rawAppointment.Subject = someTitleString`, `rawAppointment.Body = new ews.MessageBody(someBodyString)`, `rawAppointment.Start = new ews.DateTime(startUnix)`, `rawAppointment.End = new ews.DateTime(endUnix)`, `rawAppointment.Location = someRoomEmailAddr`, and `rawAppointment.ReminderSet = false`
4. I remove and add some attendees by `rawAppointment.RequiredAttendees.RemoveAt(i)` and `rawAppointment.RequiredAttendees.Add(new ews.Attendee(event.attendees[i]))`
5. Lastly, I use `rawAppointment.Update(ews.ConflictResolutionMode.AlwaysOverwrite, ews.SendInvitationsOrCancellationsMode.SendToAllAndSaveCopy)` to send all update data.

As I said above, I also tried `exchangeService.UpdateItems` as well, but the result still the same.

Creating and deleting appointment are all fine.

**Comment by gautamsi** [comment]
can you post the soap data from debug log? I suspect version issue. what happens when you try with O365 and initialize ExchangeService with Exchange2010 version?

I do not have 2010 server to test unfortunately

**Comment by inkirby** [comment]
This going to be taking time... I discovered that the error happens only sometimes, and I still trying to find out what cause this.

If I have any further information, I will post an update here.

Thanks.

**Comment by inkirby** [comment]
By the way, the error that printout without while `EwsLogging.DebugLogEnabled = false;` is this:

```
ServiceResponseException {
  message: 'An object within a change description must contain one and only one property to modify.',
  stack: [Getter/Setter],
  InnerException: null,
  response:
    UpdateItemResponse {
      errorDetails: DictionaryWithStringKey { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] },
      errorProperties: [],
      item:
        Appointment {
          lockObject: {},
          OnChange: [],
          setService: [Function],
          getService: [Function],
          propertyBag: [Object],
          parentAttachment: null,
          ReminderSet: false },
      returnedItem: null,
      conflictCount: 0,
      result: 2,
      errorCode: 124,
      errorMessage: 'An object within a change description must contain one and only one property to modify.' } }
```

**Comment by gautamsi** [comment]
this is what I want from the debug log (`data: `). if you have turned off debugger you can turn it back on by setting `ews.EwsLogging.DebugLogEnabled = true;`. you can and should remove personal/privacy data from XML before sending me. You can also send that to my email in profile. 

```json
sending ews request
{ url: 'https://outlook.office365.com/Ews/Exchange.asmx',
  headers: 
   { 'Content-Type': 'text/xml; charset=utf-8',
     Accept: 'text/xml',
     Authorization: 'Basic xxxxxxxxxxxxxxxxxxxxxxxx' },
  type: 'POST',
  data: '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2013_SP1"></t:RequestServerVersion></soap:Header><soap:Body><m:GetItem><m:ItemShape><t:BaseShape>AllProperties</t:BaseShape><t:AdditionalProperties><t:FieldURI FieldURI="contacts:DisplayName"></t:FieldURI><t:FieldURI FieldURI="contacts:GivenName"></t:FieldURI><t:FieldURI FieldURI="contacts:EmailAddresses"></t:FieldURI><t:IndexedFieldURI FieldURI="contacts:EmailAddress" FieldIndex="EmailAddress1"></t:IndexedFieldURI></t:AdditionalProperties></m:ItemShape><m:ItemIds><t:ItemId Id="AAMkADQwYjI2NmQzLWRjOGItNDcyMC1iMWE2LWZiMWQxZTk0NDA5YwBGAAAAAAD7THPLlZw5QIg6OXUk7V98BwBW56ZK5wEvSplui1kQQWjKAAAAAAEOAABW56ZK5wEvSplui1kQQWjKAADGcgdaAAA="></t:ItemId></m:ItemIds></m:GetItem></soap:Body></soap:Envelope>' }
```

**Comment by inkirby** [comment]
The log is quite long, so I saved as a text file and uploaded [here](https://drive.google.com/open?id=0ByBWZ9C0up4dUnZiZWpNNjJ1S1U).

I saw `Basic` authentication instead of `NTLM`. Is that the problem?

P.S. Some personal data has been replaced for privacy protection.

**Comment by gautamsi** [comment]
looks like some field items have been set twice in the request XML. for example, subject body are listed two times. there are many other field like this.

please confirm it wasn't in the process of removing privacy information.

**Comment by inkirby** [comment]
No data was removed from the log file, just replaced any personal email with "attendee1@mail.com", "attendee2@mail.com", and "room1@mail.com".

**Comment by inkirby** [comment]
No data was removed from the log file, just replaced any personal email with "attendee1", "attendee2", and "room1".

**Comment by gautamsi** [comment]
Just making sure, it wasn't the case. I am working on it.

**Comment by gautamsi** [comment]
found the bug, it is `false` value not getting set. due to wrong if block. pushed new dev build can you install @next and try again.

**Comment by inkirby** [comment]
My existing build does not contain any `IsAllDayEvent` setting code, so I will try the new dev build and let you know if the problem solved.

Thanks again for your support :D

**Comment by inkirby** [comment]
I have tried the updated version of the code, but now I got another error instead.

The error was `ErrorInvalidPropertySet` and it indicated that `calendar:MyResponseType` field cause this error.

I found that the error means that the field is read-only, and should not be sent upon update request.
Could you guide me to fix this?

**Comment by gautamsi** [comment]
it could be something in your code triggering this, I see the XML you posted has those fields which in my case isn't. can you send me email with related code? I may be able to point out something.

**Comment by inkirby** [comment]
The related code has been sent to your email, if you need any other information, please tell me again.

**Comment by inkirby** [comment]
For other readers, the `ErrorInvalidPropertySet` was temporary solved by removing `PropertyDefinitionFlags_1.PropertyDefinitionFlags.CanSet` and `PropertyDefinitionFlags_1.PropertyDefinitionFlags.CanUpdate` properties from `AppointmentSchema` file.

AFAIK, those properties are correctly set in [official ews-java-api](https://github.com/OfficeDev/ews-java-api/blob/master/src/main/java/microsoft/exchange/webservices/data/core/service/schema/AppointmentSchema.java) and [official C# ews-managed-api](https://github.com/OfficeDev/ews-managed-api/blob/master/Core/ServiceObjects/Schemas/AppointmentSchema.cs), but that somehow cause the error only on my 2010 server, not the Office365 and others.
