### ISSUE TITLE
BUG: FileAttachment.Load does not work, throws error

### ISSUE THREAD

**Issue by gautamsi** [gautamsi/ews-javascript-api#163]
the error message is `The element at position 0 is invalid`

issue: the validation of request looks for wrong property. 

status: code fixed.

reference #85 (pointed by @chetanmekha)

**Comment by gautamsi** [comment]
fixed in `ews-javascript-api@0.9.0-dev.3`

**Comment by chetanmekha** [comment]
@gautamsi thanks for the reply, i have fixed it.. :)
