### ISSUE TITLE
Can't update permissions on calendar folder

### ISSUE THREAD

**Issue by jtbennett** [gautamsi/ews-javascript-api#164]
I am trying to update permissions on a calendar folder.  The [recommended process](https://msdn.microsoft.com/en-us/library/office/dn641962%28v=exchg.150%29.aspx?f=255&MSPPError=-2147217396) is to bind to the folder after explicitly specifying that permissions be included in the `PropertySet`, modify the permission set, and then call `FolderUpdate`.

There are typically three permissions by default on every calendar: Default (none), Anonymous (none), and "any authenticated user" (read free/busy values only).  When calendar permissions are retrieved, that last one is included, and its `UserId` value is empty -- no `StandardUser`, `sID`, or `PrimarySmtpAddress`.  Its permissionLevel is 11, meaning custom.

That causes all updates to fail, because validation for `UserId` requires one of those three values. The specific error (from UserId.ts) is: "The UserId in the folder permission at index 0 is invalid. The StandardUser, PrimarySmtpAddress, or SID property must be set."

If you remove that "all authenticated users" permission before submitting, the validation error is avoided.  However, the operation still fails on the server, because the `<t:Updates></t:Updates>` element is empty.  It does not appear that changes to the `Permissions` property are reflected in the XML sent to the server. (This would be a bad thing to do in production in any case, since you'd be removing the ability for people to see free/busy info for their colleagues.)

Here is the code I'm using:

```js
let ews = require('ews-javascript-api');
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);
exch.Credentials = new ews.ExchangeCredentials("foo@example.com", "foopw");
exch.Url = new ews.Uri("https://example.com/Ews/Exchange.asmx");

const calendarFolderId = new ews.FolderId(
  ews.WellKnownFolderName.Calendar,
  new ews.Mailbox("foo@example.com"))

const propertySet = new ews.PropertySet(
  ews.BasePropertySet.FirstClassProperties,
  ews.FolderSchema.Permissions)

ews.CalendarFolder.Bind(exch, calendarFolderId, propertySet)
  .then((calendarFolder) => {

    // allow user "bar" to see calendar of user "foo"
    const userId = new ews.UserId("bar@example.com")
    const permission = new ews.FolderPermission(
      userId,
      ews.FolderPermissionLevel.Reviewer
    )
    calendarFolder.Permissions.Add(permission)

    exch.UpdateFolder(calendarFolder)
      .then((response) => {
        console.log('Succeeded!')
      }, err => {
        console.log(err)
      })

  })
```

Any ideas on how to get around this?  

Thanks!

**Comment by gautamsi** [comment]
I have to test the authenticated User scenario. other issue may be due to #124,  can you make use of `ews-javascript-api@next` package for second part

**Comment by gautamsi** [comment]
I have to work on series of files (which has similar issues). if you want to try fix this one only, rename `LoadFromXmlJsObject` method to `CreateFromXmlJsObjectCollection` in `FolderPermissionCollection.js` file.

**Comment by gautamsi** [comment]
done, use `ews-jsvsscript-api@next` to use meanwhile.
