### ISSUE TITLE
Proxy and Auth with username and password

### ISSUE THREAD

**Issue by NerminMujagic** [gautamsi/ews-javascript-api#166]
Does the library support proxy?
Example: My application is on a private network with proxy and wants to access a office365 ?
And does the library support authentication with username and password instead email and password ?

**Comment by gautamsi** [comment]
still need help on this?

**Comment by presidenten** [comment]
Im using ews-javascript-api 0.9.1. 
Could you be more specific on how to set the fetch config to include the proxy setting in the requests?

**Comment by gautamsi** [comment]
https://github.com/ewsjs/xhr should help, recent development. try with latest npm package, I may just re-publish current dev tag as 0.9.3

**Comment by gautamsi** [comment]
https://github.com/ewsjs/xhr is way to go forward, contains proxy related code.
