### ISSUE TITLE
Accessing Calendar Notes

### ISSUE THREAD

**Issue by bdevore17** [gautamsi/ews-javascript-api#168]
Is there a way to access a calendar appointment's notes/body using this API? I've been searching for a while and have yet to figure it out.

**Comment by gautamsi** [comment]
have you tried binding to Appointment?  see [`Appointment.Bind`](https://msdn.microsoft.com/en-us/library/office/dd634072(v=exchg.80).aspx) static method

**Comment by gautamsi** [comment]
were you able to work with this?
