### ISSUE TITLE
Autodiscovery broken on master 

### ISSUE THREAD

**Issue by Pierre-Felber** [gautamsi/ews-javascript-api#172]
You are checking for autodiscovery headers, but you use different casing as what is sent from microsoft.
you have:
```
AutodiscoverService.AutodiscoverSoapEnabledHeaderName = "X-SOAP-Enabled";
AutodiscoverService.AutodiscoverWsSecurityEnabledHeaderName = "X-WSSecurity-Enabled";
AutodiscoverService.AutodiscoverWsSecuritySymmetricKeyEnabledHeaderName = "X-WSSecurity-SymmetricKey-Enabled";
AutodiscoverService.AutodiscoverWsSecurityX509CertEnabledHeaderName = "X-WSSecurity-X509Cert-Enabled";
AutodiscoverService.AutodiscoverOAuthEnabledHeaderName = "X-OAuth-Enabled";
```
I receive:

![image](https://cloud.githubusercontent.com/assets/19165025/24252565/1968d306-0fde-11e7-80d9-1eb6de65ea6a.png)

The checks must be implemented case insensitive, i guess.

**Comment by Pierre-Felber** [comment]
hm, somehow, it is more complicated. I am on node, and when I intercept the responses, the raw headers are as you have defined them. Some module must normalize them to lowercase.

**Comment by Pierre-Felber** [comment]
Well, this [disscussion](https://github.com/nodejs/node-v0.x-archive/issues/1954) sheds light.
So I suppose I was right, by suggesting the checks have to be case insensitive.

**Comment by gautamsi** [comment]
I have to work on this casing issue

**Comment by gautamsi** [comment]
this is implemented already,  autodiscover is also re-written in #324
