### ISSUE TITLE
Has anyone got this working with NTLMv2?

### ISSUE THREAD

**Issue by rickard-505** [gautamsi/ews-javascript-api#173]
I'am stuck with 401 response from server..works fine if i accept NTLMv1

**Comment by gautamsi** [comment]
Have you tried `ews-javascript-api@next`?

**Comment by duongkha** [comment]
@gautamsi : I am looking for how to authenticate EWS server by NTLM which is in on-premise mail server. I got 401 error when trying to authenticate. Could you please advise how i can use your lib to authenticate by NTLM? BTW, what is  "ews-javascript-api@next"?

**Comment by gautamsi** [comment]
latest auth package is not published. try installing from source branch like this `npm install git+https://github.com/gautamsi/ews-javascript-api-auth.git/#ntlmv2 --save`

@next is dev tag for npm package. there are many changes included in there. install like `npm install ews-javascript-api@next`

ntlmv2 implementation only supports "username" format. domain\username or upn does not work.

**Comment by gautamsi** [comment]
`ews-javascript-api-auth` is bumped to 1.2.0 with tag ntlmv2 (latest still points to 1.1). you can try this.

**Comment by gautamsi** [comment]
1.2.0 is moved to latest tag, no need for tag based install.
