### ISSUE TITLE
Stop subscribe mailbox with unknown error

### ISSUE THREAD

**Issue by duongkha** [gautamsi/ews-javascript-api#174]
Hi,

I am trying to subscribe a mailbox to get new email coming and the application is running continuously to monitor the new email automatically. I use SubscribeToStreamingNotificationsOnAllFolders and StreamingSubscriptionConnection with timeout 30 minutes. 

I also subscribe OnDisconnect event to reconnect by calling connection.Open();
and OnNotificationEvent to listen new email.

It was working very well for monitoring the new email in mailbox, however, it is stopped after running for a while (a day or some hours) without error alarm. I don't know when i will happen, just see it stops listen the new email. I have no idea if this is an issue of library or we need to do something extra to handle the case to re-connect to mailbox.

Could you please advise what i can do to fix the issue?

Thanks in advanced.

**Comment by gautamsi** [comment]
are you catching error on `connection.Open()` promise?

**Comment by duongkha** [comment]
No, i am not. I should catch error and call Open again,right?

**Comment by gautamsi** [comment]
first check what is the error it give, log it in console or in file to review later. if there is something I can fix that would help others

**Comment by soptimizer** [comment]
Hi, i have similar problem. When internet connection gone, i catch disconnect event. And i try reopen connection but i can not catch any error.

```
    conn.Open().then((err) => {
            console.log("error: " + err);
        });
```

Is this code true.

**Comment by gautamsi** [comment]
@soptimizer  you can not do it this way, `.then(success function, error function)` is the syntax. You have to use 2nd parameter for exception in `.then`

if you are consuming `ews-javascript-api@next` then you can also use BlueBird's `.catch`.

**Comment by soptimizer** [comment]
@gautamsi  thanks for fast response. 
I tried code at the below, but not work for me.

```
    conn.OnDisconnect.push(() => {
        console.log("OnDisconnect : " + new Date() ); // works
        conn.Open().then( function(success) {
                            console.log("OK : " + success)  // not works
                         },
                         function(error) {
                            console.log("ERR : " + error) // not works
                         },
                        );
        console.log("test text");  // not works
    });
```
In this code, conn.Open() is working. But after the ".then" function  is not working.
I do not see any "success" message, neither "error" message nor "test text" message.

**Comment by duongkha** [comment]
this is what i do and works for me. 
$q(connection.Open())
      .then(function(success){
              console.log("ews connected.");
          },
          function(error){
              console.log("ews connection error.");
              console.log(error);
          });

**Comment by gautamsi** [comment]
@duongkha  did you receive any error in the error block?

**Comment by duongkha** [comment]
Yes. the error is _"'You must add at least one subscription to this connection before it can be opened.'"_

I guess that it happened inside your code that the subscription somehow is disappeared. 
It is not happening often, but it can happen at any time, some hours or a day since my app is always running to listen new email.

**Comment by soptimizer** [comment]
I tried q promise and it works. Success function was called.  But when i lost the internet connection, error function was not called. So i can not handle net connection error.

Do you have a suggestion for me?

**Comment by gautamsi** [comment]
I will take a look on this sometime this week.

**Comment by duongkha** [comment]
what i am trying to do is dispose the current connection and create new connection with subscription, it seems to be working now. but let's see if it is stopped working for long run or not.

**Comment by soptimizer** [comment]
@duongkha How do you catch "disconnection"? In my code i plug off cable and "OnDisconnect" is working correctly. In this situation, I call conn.Open() but I can not receive any error.

**Comment by duongkha** [comment]
i also subscribe Disconnected event and reconnect again only.

**Comment by duongkha** [comment]
@gautamsi : I tried to set the timeout to 1 minutes of subscribing the mailbox. however, i recognized that sometimes, it called to reopen the connection and it failed, nothing response with Open() call. What should we do when the Open is failed? Should we recall Open again?

**Comment by soptimizer** [comment]
@duongkha I'm struggling with the same problem. How can i catch when the Open function is failed?

**Comment by gautamsi** [comment]
`isDisposed` is a private member. you should not need access.
`isConnected` is never set to true which is a bug. 

try the [gist for subscription example](https://gist.github.com/gautamsi/1c267504b5d4c759afc2a93def67e4d1). It worked for me when there was no internet.

**Comment by soptimizer** [comment]
@gautamsi  I tried code that you suggested. When i run the code without internet connection, and I can catch the error. But when i cut off internet connection while the code is running, I can not catch connection error.

My code has to run in  all condititons. For this reason i have to catch connection error while code running, and i have to retry with delay. ( like => ** setTimeout ( retryConnection(), 1000 * 10) ;** )

Do you have a suggestion for me?

**Comment by soptimizer** [comment]
@gautamsi I tried code that you suggested. It is working for when connection cut off. But Promise not work for Open() function. I can not understand Open() process successed or failed.

If i solve this problem i can handle all condition that i need.

Do you have a suggestion for me?

**Comment by gautamsi** [comment]
I see the problem. the issue is `connection.open()` does not return promise, but internally it tries to reject the promise, looks like it has to be changed to throw because I do not want this to block any code (async scenario). 

Will have to take deeper look on this.

**Comment by duongkha** [comment]
@gautamsi Yea. I see this problem too. I can't handle when the internet is interrupted. The Open() function does not return success or fail. Do you have idea to check if the connection state is failed? I need to repeatedly reconnect in my code.

**Comment by gautamsi** [comment]
you can now use `connection.Open().then(successFunc,errFunc)`. use `ews-javascript-api@next` meanwhile.

**Comment by soptimizer** [comment]
Hi, gautam.

I tested this with 0.9.0-dev.5. 

I encountered interesting error. When i call open function first with then(successFunc,errFunc) the code do not enter to success or error func. When connection timeout, previous success message shown. Sample code and output at below.

```
            console.log("Precalling... " + counter );
            connection.Open().then(
                function(success){
                    console.log("OK" + counter  );
                },
                function(error){
                    console.log("FAIL" + counter  );
                });
```

Precalling. 1
(Timeout) Fri Apr 14 2017 13:10:12   // This output must be there below (After the Ok. 1 message)
Ok. 1
Precalling. 2
(Timeout) Fri Apr 14 2017 13:11:14  // This output must be there below (After the Ok. 2 message)
Ok. 2
...

**Comment by gautamsi** [comment]
I see the way current code is organized, It resolves only after HTTP connection stream is disconnected. I can resolve the promise early in header event (when first headers arrive) but that may be bit early. other place I can resolve promise is when first data section arrives, but that may be late, data event is fired when first set of notification is received.

**Comment by gautamsi** [comment]
I have finally decided to wrap this in OnResponseHeader delegate (similar to OnDisconnect) so that you can also look for headers and test for connection (which is always true if you received header).

**Comment by duongkha** [comment]
@gautamsi : My app is running 24/7, but if there is any error with the connection open sometimes, there is no returned error that helps me to know in order to call reconnect. My question is " Is it possible to check the connection state by a timer to know if the connection is still ok"?

**Comment by gautamsi** [comment]
this is published in dev6 tonight. 
there is still a caveat, the promise will never resolve as this is streaming. you can first detect connection by subscribing to `OnResponseHeader` delegate use `connection.OnResponseHeader.push(function(headers){/* do something with headers*/});` This actually gives you header information. I am not checking if the header is for success or failure. on failures, it will not have data stream and it will change `IsOpen` from true to false immediately. 

you can use timer to check `connection.IsOpen` value, which will be true if the connection is still open. let me know what you find.

**Comment by gautamsi** [comment]
please reopen if needed.

**Comment by hgezim** [comment]
@gautamsi, thanks for this awesome library!

I'm also experincing the issue with `.Open()` not indicating success or failure. I even used the `q` library as described above to no avail:

```
    private onDisconnect(args: ews.SubscriptionErrorEventArgs) {
        winston.error('[exchange] subscription disconnected:', args.Exception);
        winston.error('[exchange] subscription number before reconnecting:', this.connection.CurrentSubscriptions.length);
        q(this.connection.Open())
.then(function(success){
console.log("ews connected.");
},
function(error){
console.log("ews connection error.");
console.log(error);
});
```

Output:

> 
> error: [exchange] subscription disconnected:
> error: [exchange] subscription number before reconnecting: 1
> error: [exchange] subscription number after reconnecting: 1

The bigger issue is that for some reason, we stop receiving email notifications.

**Comment by hgezim** [comment]
Furthermore, `connection.IsOpen` always seems to return true, even when I disconnect my internet:

```
        setInterval(() => {
            console.log('conn is open?: ', this.connection.IsOpen);
        }, 5000);
```

**Comment by gautamsi** [comment]
I have to find time to replicate this. stay tuned.
