### ISSUE TITLE
Throw error when call folder.FindFolders(folderView)

### ISSUE THREAD

**Issue by ooclleeke** [gautamsi/ews-javascript-api#178]
if I pass single argument to folder.FindFolders function, it throw an error.
I have check the source code, it seem have a bug at this line:
return this.Service.FindFolders(this.Id, view);

In my case, it will pass the null to Service.FindFolders function. Please help to check, thanks.

 ews-javascript-api/src/js/Core/ServiceObjects/Folders/Folder.ts:
```
    FindFolders(viewOrSearchFilter: FolderView | SearchFilter, view?: FolderView): Promise<FindFoldersResults> {
        this.ThrowIfThisIsNew();
        //todo: better argument check with ewsutilities
        var argsLength = arguments.length;
        if (argsLength < 1 && argsLength > 2) {
            throw new Error("invalid arguments, check documentation and try again.");
        }

        if (viewOrSearchFilter instanceof FolderView) {
            return this.Service.FindFolders(this.Id, view);
        }
        else if (viewOrSearchFilter instanceof SearchFilter) {
            if (typeof view === 'undefined' || !(view instanceof FolderView)) {
                throw new Error("Folder.ts - FindFolders - incorrect uses of parameters at 2nd position, must be FolderView");
            }
            return this.Service.FindFolders(this.Id, viewOrSearchFilter, view);
        }
        else {
            throw new Error("Folder.ts - FindFolders - incorrect uses of parameters at 1st position, must be FolderView or SearchFilter");
        }
    }
```

**Comment by gautamsi** [comment]
this is how it is expecting the argument based on c# version. 

How are you making it pass null? are you passing null for view? or `Folder.Id` is null?

**Comment by ooclleeke** [comment]
I use this function to list all sub folder. 
I try to call this function like this:
`folder.FindFolders(folderView);`
But it will throw an error. 

If I call the function like this: 
`folder.FindFolders(folderView, folderView);`
it will return the correct result.

**Comment by gautamsi** [comment]
you may want to share full code for repro.  use gitter to send private message

**Comment by gautamsi** [comment]
problem is with the line:
```ts
       if (viewOrSearchFilter instanceof FolderView) {
            return this.Service.FindFolders(this.Id, view);
        }
```
it should be 
```ts
       if (viewOrSearchFilter instanceof FolderView) {
            return this.Service.FindFolders(this.Id, viewOrSearchFilter);
        }
```

**Comment by gautamsi** [comment]
`ews-javascript-api@0.9.0-dev.6` containing this change is published
