### ISSUE TITLE
ReferenceError: Reflect is not defined

### ISSUE THREAD

**Issue by alkasain** [gautamsi/ews-javascript-api#18]
Hi,

I am using Nodejs v5.9.1 and ews-javascript-api and getting error 

> ReferenceError: Reflect is not defined 

while executing `var ews = require('ews-javascript-api');` code.

I have attached screen shot of the issue. Any help would be highly appreciated. 

Thanks,
Alka Saini
![error](https://cloud.githubusercontent.com/assets/11312473/14166417/ced6ff5a-f730-11e5-9dcc-ac98afb00f32.JPG)

**Comment by gautamsi** [comment]
Please check if 'reflect-metadata' is installed under node_modules.

test if it is not having any issues. when you run `require('reflect-metadata');` in node command prompt, it should add `Reflect` in global.

**Comment by gautamsi** [comment]
I just tested by fresh `npm install` no error. can you give me repro steps.

**Comment by alkasain** [comment]
Attached is my js file and on line #42 error is thrown
[index.zip](https://github.com/gautamsi/ews-javascript-api/files/197382/index.zip)

**Comment by gautamsi** [comment]
it is not compatible with browser yet. I have not tested properly. npm package is for node.  

What is the loader you are using? you may have to shim reflect-metadata or load it in browser before this code. 

moment and moment-timezone needs to be loaded as well.

**Comment by gautamsi** [comment]
is your app on GitHub? can I fork and test? or can you give me skeleton which breaks without giving full code. I can try debug and fix it.  you can also use Visual Studio Code to debug your node app and report exact issue.

**Comment by alkasain** [comment]
[index.zip](https://github.com/gautamsi/ews-javascript-api/files/199485/index.zip)
![command_prompt](https://cloud.githubusercontent.com/assets/11312473/14205619/394dd4c2-f82a-11e5-88fc-b210a176652b.JPG)

I am attaching the node project and the command prompt screen shot. download the index.zip and say its placed at "E:\alka\index.zip".

- you need to install nodewebkit. 
- In nodejs command prompt navigate to the path of nw.exe(~\node_modules\nodewebkit\nodewebkit).
Now to run the zip project using nw command: nw E:\alka\index.zip
nodewebkit browser would be opened and you can login using exchange username and password.

**Comment by gautamsi** [comment]
I have no issues when I run it in windows.  node v5.10.0

can you test again after upgrading node to stable version

**Comment by alkasain** [comment]
after upgrading nodejs v5.10.0 tried again and getting same issue.

**Comment by gautamsi** [comment]
well... it could be specific to your computer. can not reproduce myself. is it possible for you to test this on another machine, a virtual machine possibly?

used your steps and it worked fine for me. 

![capture](https://cloud.githubusercontent.com/assets/5769869/14247262/99453b24-fa8a-11e5-8176-149c44b4f422.PNG)

**Comment by alkasain** [comment]
Thanks Gautam.. I commented out the Reflect code and now its working. So I am closing this issue, will contact back if I face any other issue.

**Comment by gautamsi** [comment]
@alkasain  if you want browser based script, still have to use webpack like optimizer. CORS is still the issue. but you can run in Electron/NW.js renderer process (webview)
