### ISSUE TITLE
PropertySet comparison bug

### ISSUE THREAD

**Issue by anujkumaraurea** [gautamsi/ews-javascript-api#181]
Hi Gautam, the comparison is failing at following step

https://github.com/gautamsi/ews-javascript-api/blob/2e665986a40af55ce0b5907eed9d620e4dae6c44/src/js/PropertyDefinitions/ExtendedPropertyDefinition.ts#L229

This is happening while getting extended property. I am using following code.

```
const adinationalProps = [];
const token_property_set = new ews.ExtendedPropertyDefinition(new ews.Guid("958DB3CF-41AB-4d05-9DE7-3ACC0D3FABF3"), 100, ews.MapiPropertyType.String);
adinationalProps.push(token_property_set);
const subjectFilter = new ews.SearchFilter.IsEqualTo(ews.ItemSchema.Subject, "Authentication");
const filter = new ews.SearchFilter.SearchFilterCollection(ews.LogicalOperator.And, [subjectFilter]);
const property_set = new ews.PropertySet(ews.BasePropertySet.IdOnly, adinationalProps);
service.FindItems(ews.WellKnownFolderName.Inbox, filter, view).then(function (response) {
    const item = response.items[0];
    item.Load(property_set).then(function () {
        var token = {outValue: null};
        item.ExtendedProperties.TryGetValue(adinationalProps[0], token);
        console.log(token.Items);
    });
}, (error) => {
    var z = error;
});
```

**Comment by gautamsi** [comment]
you should not be using TryGetValue, this is internal method. Two ways you can use this. 

1. 
```
for (var i = 0;i<item.ExtendedProperties.Count;i++){
    var property = item.ExtendedProperties._getItem(i);
    var value = property.Value;
}
```
2.
```
for (let property of item.ExtendedProperties.GetEnumerator()){
    let value = property.Value;
}
```

**Comment by anujkumaraurea** [comment]
Isn't TryGetValue available in C#, you mean to say here, it is internal ?

**Comment by gautamsi** [comment]
it is internal in c# version. [TryGetValue<T>](https://github.com/OfficeDev/ews-managed-api/blob/master/ComplexProperties/ExtendedPropertyCollection.cs#L151) is internal

**Comment by gautamsi** [comment]
see [Viewing custom extended properties by using the EWS Managed API 2.0](https://msdn.microsoft.com/en-us/library/office/dd633697(v=exchg.80).aspx)

**Comment by anujkumaraurea** [comment]
Oh my bad, it should be TryGetProperty.

https://msdn.microsoft.com/en-us/library/microsoft.exchange.webservices.data.item.trygetproperty(v=exchg.80).aspx

**Comment by anujkumaraurea** [comment]
Closing this, will reopen it if problem persists.

**Comment by anujkumaraurea** [comment]
TryGetProperty suffers from same problem.

```
var token = { outValue: null };
item.ExtendedProperties.TryGetProperty(token_property_set, token);
```
PropertySet is present, but it is failing in comparison.

**Comment by gautamsi** [comment]
comparison may be a bug, provide me little more code and context (gitter 1:1 for code if not already on github)

`TryGetProperty` is on `ServiceObject` so you should do `item.TryGetProperty` not on ExtendedPorperties property of it.

**Comment by gautamsi** [comment]
I found one bug with it, qn: Is the extended property you want to use, has Guid type? this scenario struck me while looking for another issue.

**Comment by anujkumaraurea** [comment]
That's correct, the custom extended property was indeed of guid type, that's why I had pointed you to very specific line in source code :)

**Comment by gautamsi** [comment]
it should be fixed with tonight's nightly (@next tag in npm). 
published
