### ISSUE TITLE
How to get ExtendedProperty of a meeting?

### ISSUE THREAD

**Issue by inkirby** [gautamsi/ews-javascript-api#182]
Hi again,

I'm trying to get [`PidLidGlobalObjectId`](https://msdn.microsoft.com/en-us/library/office/cc815676.aspx) from a meeting, however, after I adapted [this implementation](https://social.technet.microsoft.com/Forums/lync/en-US/e1714a15-1ef7-4868-a701-f53c5ceae1ad/ews-api-differences-in-icaluid-returned-when-appointments-are-created-by-office-365-account-vs?forum=exchangesvrdevelopment), the expected `outValue` is always `null`.

Here is the block of my code:
```
ewsApi.Appointment.Bind(cService, new ewsApi.ItemId(data.appointmentId))
.done(function (returnAppointment) {
	var cleanObjId = new ewsApi.ExtendedPropertyDefinition(0x23, ewsApi.MapiPropertyType.Binary);
	var propSet = new ewsApi.PropertySet(ewsApi.BasePropertySet.FirstClassProperties);
	propSet.Add(ewsApi.AppointmentSchema.ICalUid);
	propSet.Add(cleanObjId);
	returnAppointment.Load(propSet)
	.done(function (isSuccess) {
		var returnedObjId = {};
		returnAppointment.TryGetExtendedProperty(cleanObjId, returnedObjId);
		try {
			var objId = new Buffer(returnedObjId.outValue, 'binary').toString('base64');
			console.log("cleanGlobalID: "+objId);
		} catch (err) {
			console.log("Get Item Property Err: "+err);
		};
	}, function (err) {
		console.log("Get Item Detail Err: "+JSON.stringify(err));
	});
}, function (err) {
	console.log("Getting Event Err: "+JSON.stringify(err));
});
```

Do you have any suggestions?
Thanks.

**Comment by gautamsi** [comment]
Looks like this code has issues in EWS Managed API as well, gives me error - "The extended property attribute combination is invalid". 

can you provide more details. you may want to try see if there are other MAPI property you can fetch or not.

**Comment by gautamsi** [comment]
with more research, I think you want to use it this way rather than the example. 
```js
var cleanObjId = new ewsApi.ExtendedPropertyDefinition(new ewsApi.Guid("6ED8DA90-450B-101B-98DA-00AA003F1305"), 0x23, ewsApi.MapiPropertyType.Binary);
```

I found this Guid by using [MFCMapi](https://github.com/stephenegriffin/mfcmapi) app. this worked for me when using 0.9 dev7, there was a bug in Extended Property which I fixed today.

reopen if you still need help.
