### ISSUE TITLE
Possible 0.8.1 Release

### ISSUE THREAD

**Issue by BennettJames** [gautamsi/ews-javascript-api#185]
Hello,

I was wondering if it would make sense to have a 0.8.1 release - I noticed that there's a [commit that moved the package version to 0.8.1][1], but no matching release. Is there production ready version of 0.8.1 in the codebase, or will those changes ultimately all go into a 0.9 release?

P.S. Thanks for all the great work on this library!

[1]: https://github.com/gautamsi/ews-javascript-api/commit/80bc56259cd65e6b9dc8bcabbe05426aeb3493cc

**Comment by BennettJames** [comment]
For a little more context - I think the *typings* property in that package would play nicer with my builds, so if I could directly get a version directly from npm with *typings* set that would be great. I think a few other issues were opened about that (like #136), but I wasn't sure if there was any roadblock to a new release with the changes.

**Comment by gautamsi** [comment]
have you tried latest dev builds? I am pretty sure they are stable, I have also committed timezone related code which is the only pending item for 0.9 release. only thing remain is to perform testing with my private test repo with live exchange server to make sure it works as intended. 

if you have tries 0.9-dev-* and it works well, I can publish 0.9 sooner.

**Comment by BennettJames** [comment]
Hey guatamsi,

Thanks for the quick response! I think that'll work - there were a few getters I was using that were marked internal, but I think I was able to work around them. I'll let you know if anything else turns up when using it.

If it does seem to work out, I do think there's something to be said for publishing 0.9 sooner. I do not have a ton of TypeScript experience, but given that other people seem to have run across needing the `typings` property it would be nice if the most recent release in npm has the property configured.
