### ISSUE TITLE
XML parsing error

### ISSUE THREAD

**Issue by emcho92** [gautamsi/ews-javascript-api#188]
While working with Office365 (Exchange 2013), once in a while there is a response like the one below. Seems like the XML parsing fails, however it also crashes the application right after the output below. This is just a part of the output but it is mostly these three messages. Looks to originate from the xmldom library which is a dependency of this one. Any ideas?

```
[xmldom warning]	attribute "100%" missed quot(")!! 
@#[line:28,col:58] [xmldom warning] attribute "1" missed quot(")!! 
@#[line:28,col:58] [xmldom warning] attribute "silver" missed quot(")!! 
```
......

**Comment by gautamsi** [comment]
can you provide the soap response from debug log? use gitter to send me this if you want

**Comment by istersin** [comment]
Unfortunately no, it seems to be really random and have not caught it yet..

**Comment by gautamsi** [comment]
no response on this. please reopen when you have more information.
