### ISSUE TITLE
"value can not be of type object" when calling GetUserAvailability

### ISSUE THREAD

**Issue by jozip** [gautamsi/ews-javascript-api#189]
This error has me completely stumped. I make a call to GetUserAvailability that is almost identical to the example in the README, so it should work as intended. It appeared when I bumped version from 0.8.0 to 0.9.1. Could it be something related to the breaking changes with the promises?

Error: value can not be of type object
    at EwsServiceXmlWriter.module.exports.EwsServiceXmlWriter.ConvertObjectToString (/var/task/lib/index.js:57120:35)
    at EwsServiceXmlWriter.module.exports.EwsServiceXmlWriter.WriteAttributeValue (/var/task/lib/index.js:57181:32)
    at TimeZoneDefinition.module.exports.TimeZoneDefinition.WriteAttributesToXml (/var/task/lib/index.js:90782:20)
    at TimeZoneDefinition.module.exports.ComplexProperty.WriteToXml (/var/task/lib/index.js:7717:14)
    at TimeZoneDefinition.module.exports.TimeZoneDefinition.WriteToXml (/var/task/lib/index.js:90826:37)
    at GetUserAvailabilityRequest.module.exports.ServiceRequestBase.WriteToXml (/var/task/lib/index.js:58954:45)
    at GetUserAvailabilityRequest.module.exports.ServiceRequestBase.EmitRequest (/var/task/lib/index.js:58621:18)
    at GetUserAvailabilityRequest.module.exports.ServiceRequestBase.BuildXHR (/var/task/lib/index.js:58587:14)
    at /var/task/lib/index.js:8551:33
    at Promise._execute (/var/task/lib/index.js:137378:9)
    at Promise._resolveFromExecutor (/var/task/lib/index.js:139453:18)
    at new Promise (/var/task/lib/index.js:139049:10)
    at GetUserAvailabilityRequest.module.exports.SimpleServiceRequestBase.InternalExecute (/var/task/lib/index.js:8550:16)
    at GetUserAvailabilityRequest.module.exports.GetUserAvailabilityRequest.Execute (/var/task/lib/index.js:96532:78)
    at ExchangeService.module.exports.ExchangeService.GetUserAvailability (/var/task/lib/index.js:147297:24)
    at Object.fetchBusyInfo (/var/task/lib/index.js:134059:16)

**Comment by jozip** [comment]
I should mention that I import xhr2 before ews-javascript-api in order to change the user agent:
`var xhr2 = require('xhr2');`
`xhr2.prototype._userAgent = 'CustomUserAgent/1';`
`var ews = require('ews-javascript-api');`

**Comment by gautamsi** [comment]
what parameters you used ?

**Comment by jozip** [comment]
`var now = ews.DateTime.Now;`
`var then = new ews.DateTime(now.TotalMilliSeconds + ews.TimeSpan.FromHours(24).TotalMilliseconds);`
`var attendee = [new ews.AttendeeInfo(roomSMTP)];`
`var timeWindow = new ews.TimeWindow(now, then);`
`exch.GetUserAvailability(attendee, timeWindow, ews.AvailabilityData.FreeBusy) ...`

**Comment by gautamsi** [comment]
you might want to simplify like `var then = new ews.DateTime.Now.AddDays(1)` see #140 for more details on DateTime improvements
I do not see any issue with xhr2, i am not using it.  


are you initializing with TimeZoneDefinition, can you paste full code or share it on gitter with 1:1 message

**Comment by jozip** [comment]
Never used TimeZoneDefinition -- do I need it despite wanting timestamps and dates in UTC+0?
xhr2 at least used to be a dependency way down in the stack, and I needed to change the user agent to accommodate for a policy that a customer had set up. But I suppose that's a digression, so never mind.

**Comment by gautamsi** [comment]
not sure if it was a deep dependency, I do not see this in my node_modules directory. could be something else. 

what happens when you try this without xhr2 modification? I tried adding custom user agent but it wasnt working with earlier attempt, I can try this again.

**Comment by jozip** [comment]
Interesting; I see that xhr2 is a dependency to winjs-node, which was a dependency in 0.8.0. Funny thing is that nothing breaks when I pull notifications and calendars of a user, only when I call GetUserAvailability on a room. I think there may be an issue related to how I set up auth and the fact that I use the old-style promises. Do you have the SHA-1 for the commit that corresponds to the 0.9.1 release? (I assume 0.8.0 is the same as the tag)

**Comment by jozip** [comment]
I've found something odd going on in the ConvertObjectToString method in src/js/core/EwsServiceXmlWriter.ts (around line 142):

[0.8.0] `if (typeof value.GetSearchString === 'function')`
[HEAD] `if (TypeGuards.isISearchStringProvider(value))`

where
```typescript
export function isISearchStringProvider(arg: any): arg is ISearchStringProvider {
    return arg && typeof arg.GetSearchString === 'function';
}
```
A few thoughts:
- The exception is thrown if the test fails, which means that `value` can either be falsy or that it lacks a `GetSearchString`-method.
- It's established from the code that `value` is not `null`, `0` or `""`, since those values are tested. This leaves `undefined` and `NaN` as potential falsies.
- My guess is that TimeZoneDefinition lacks the necessary methods, or that a TimeZoneDefinition is missing somehow.

**Comment by gautamsi** [comment]
strange thing is that it does not have any problem on my machine. can you give me something to reproduce. I can also do a remote session to check this out. 

can you try deleting the ews-javascript-api node modules folder and npm install again?

**Comment by jozip** [comment]
Further investigation gives that the TimeZoneDefinition in question looks like this:
```javascript
TimeZoneDefinition {
Namespace: 2,
OnChange: [ [length]: 0 ],
periods:
DictionaryWithStringKey {
keys: [ [length]: 0 ],
keysToObjs: {},
objects: {},
keyPicker: { [Function] [length]: 1, [name]: '', [prototype]: [Object] } },
transitionGroups:
DictionaryWithStringKey {
keys: [ [length]: 0 ],
keysToObjs: {},
objects: {},
keyPicker: { [Function] [length]: 1, [name]: '', [prototype]: [Object] } },
transitions: [ [length]: 0 ],
Id:
[ [ 'Etc/GMT', 'America/Danmarkshavn', 'Etc/UTC', [length]: 3 ],
'(UTC) Coordinated Universal Time',
'Coordinated Universal Time',
'Coordinated Universal Time',
false,
0,
[length]: 6 ],
Name:
[ [ 'Etc/GMT', 'America/Danmarkshavn', 'Etc/UTC', [length]: 3 ],
'(UTC) Coordinated Universal Time',
'Coordinated Universal Time',
'Coordinated Universal Time',
false,
0,
[length]: 6 ] }
```
Note that the `Name` and `Id` is this strange array instead of a string.

**Comment by jozip** [comment]
...and the TimeZoneDefinition in question looks like this:
```javascript
TimeZoneInfo {
_ianaId: 'UTC',
_displayName:
[ [ 'Etc/GMT', 'America/Danmarkshavn', 'Etc/UTC', [length]: 3 ],
'(UTC) Coordinated Universal Time',
'Coordinated Universal Time',
'Coordinated Universal Time',
false,
0,
[length]: 6 ],
_standardDisplayName:
[ [ 'Etc/GMT', 'America/Danmarkshavn', 'Etc/UTC', [length]: 3 ],
'(UTC) Coordinated Universal Time',
'Coordinated Universal Time',
'Coordinated Universal Time',
false,
0,
[length]: 6 ],
_daylightDisplayName:
[ [ 'Etc/GMT', 'America/Danmarkshavn', 'Etc/UTC', [length]: 3 ],
'(UTC) Coordinated Universal Time',
'Coordinated Universal Time',
'Coordinated Universal Time',
false,
0,
[length]: 6 ],
_supportsDaylightSavingTime: false,
_adjustmentRules: null,
_id:
[ [ 'Etc/GMT', 'America/Danmarkshavn', 'Etc/UTC', [length]: 3 ],
'(UTC) Coordinated Universal Time',
'Coordinated Universal Time',
'Coordinated Universal Time',
false,
0,
[length]: 6 ],
_baseUtcOffset:
{ [Number: 0]
getMomentDuration: { [Function] [length]: 0, [name]: '', [prototype]: [Object] },
setMomentDuration: { [Function] [length]: 1, [name]: '', [prototype]: [Object] } } }
```

**Comment by jozip** [comment]
So I tried setting the TimeZoneDefinition by adding the following line
```javascript
  exch.TimeZoneDefinition = new ews.TimeZoneDefinition(ews.TimeZoneInfo.Utc);
```
However, TimeZoneDefinition is not exported in ExchangeWebService.

**Comment by gautamsi** [comment]
what is the server version you are using? It may be 2013 if you have not used any argument to initialize it.

**Comment by gautamsi** [comment]
you can not create `TimeZoneDefinition` yourself. the `TimeZoneDefinition` property is getter only, no effect on setting it. 

you can however pass `TimeZoneInfo` object in `ExchangeService` constructor.

```ts
    constructor();
    constructor(timeZone: TimeZoneInfo);
    constructor(requestedServerVersion: ExchangeVersion);
    constructor(requestedServerVersion: ExchangeVersion, timeZone: TimeZoneInfo);
    constructor(service: ExchangeServiceBase);
    constructor(service: ExchangeServiceBase, requestedServerVersion: ExchangeVersion);
```

**Comment by gautamsi** [comment]
which timezone you are in, you can try find this using [`moment.tz.guess()`](http://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/)

**Comment by jozip** [comment]
Ah, I see. I only passed the exchange version explicitly to the constructor previously. Tried passing TimeZoneInfo.Utc too and that appear to have fixed the issue. Thanks for the help!

**Comment by gautamsi** [comment]
can you still tell me your timezone, I may have to fix it for other. I see that your errors saying UTC timezone but that should not be the case unless you are in UTC timezone.

**Comment by jozip** [comment]
The code is running in the AWS eu-west region, that is UTC+/-00:00, Z.

**Comment by gautamsi** [comment]
can you capture `moment.tz.guess()`? it will help, there must be something not right in logic for machine in UTC

**Comment by jozip** [comment]
The result of `moment.tz.guess()` is `"UTC"`

**Comment by tobiasviehweger** [comment]
I also am facing this issue on a Linux EC2 instance, while it's working on my local Windows PC without problems...

**Comment by gautamsi** [comment]
@tobiasviehweger  I am unable to repro, need console access to ec2 instance, i can do teamviewer

**Comment by tobiasviehweger** [comment]
@gautamsi Let me see if I can set up a dummy instance and a small test script for you to try - probably won't bae able to do is this week (manually setting UTC for now works). I'll send you something next week. Thanks!
