### ISSUE TITLE
GetUserAvailability issue

### ISSUE THREAD

**Issue by isakar** [gautamsi/ews-javascript-api#19]
I am trying to use the use the **GetUserAvailability** function, literally, just like your example and nothing else, i get success with the **GetPasswordExpirationDate** method but **GetUserAvailability** I just get an error: 

_ErrorTypeError: Cannot read property 'Validate' of null_

Do you have any thought about it?

Thank you!

**Comment by gautamsi** [comment]
I have pushed 0.2.1 which fixes this. let me know if you still have issue.

**Comment by isakar** [comment]
Hi, I just updated the v0.2.1 and now all work great!! Thank you!
