### ISSUE TITLE
Is it possible to use eDiscovery to get mailboxes with the built in "litigation hold" enabled?

### ISSUE THREAD

**Issue by danxfisher** [gautamsi/ews-javascript-api#193]
I know you can use `GetHoldOnMailboxes` with a `HoldId` to find mailboxes pertaining to a user created In-Place Hold but can it be used for the "Litigation Hold"?  I know this can be done with PowerShell but not sure about EWS.

**Comment by gautamsi** [comment]
not sure if you can do that in EWS.

**Comment by danxfisher** [comment]
That's what I thought.  I'll see if we can get an In-Place hold instead of the built in Litigation hold and then this shouldn't be an issue.  Thanks.
