### ISSUE TITLE
Getting response headers

### ISSUE THREAD

**Issue by istersin** [gautamsi/ews-javascript-api#194]
Is there any way of getting the response headers, as in is it possible to hook into somewhere and get the raw response headers, or the raw response, just to get those headers - if there is no standard way of getting them through the library.

**Comment by gautamsi** [comment]
one way to do this is to copy source of `XHRDefaults.ts` and make changes yourself, plug this with `ConfigurationApi`

**Comment by istersin** [comment]
Something like #184 ?

**Comment by gautamsi** [comment]
you can use that as reference. this should work.

**Comment by istersin** [comment]
Done as per #184
