### ISSUE TITLE
How to set cookies on the Exchange Service instance

### ISSUE THREAD

**Issue by istersin** [gautamsi/ews-javascript-api#195]
Can this be done in the current version?

Here is an example of a request I need to be able to do.. this is from the MS docs page [here](https://msdn.microsoft.com/en-us/library/office/dn458789(v=exchg.150).aspx#bk_throttling).

Notice this line below, in the code:
**Cookie: X-BackEndOverrideCookie=CO1PR06MB222.namprd06.prod.outlook.com~1941996295**

I am getting this cookie from an EWS response, and now I need to use it in all my subsequent requests. How can I do so?

```
POST https://outlook.office365.com/EWS/Exchange.asmx HTTP/1.1
Content-Type: text/xml; charset=utf-8
Accept: text/xml
User-Agent: ExchangeServicesClient/15.00.0516.014
X-AnchorMailbox: alfred@consoso.com
X-PreferServerAffinity: true
Host: outlook.office365.com
Cookie: X-BackEndOverrideCookie=CO1PR06MB222.namprd06.prod.outlook.com~1941996295

<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <t:RequestServerVersion Version="Exchange2013" />
    <t:ExchangeImpersonation>
      <t:ConnectingSID>
        <t:SmtpAddress>sadie@consoso.com </t:SmtpAddress>
      </t:ConnectingSID>
    </t:ExchangeImpersonation>
  </soap:Header>
  <soap:Body>
    <m:Subscribe>
      <m:StreamingSubscriptionRequest>
        <t:FolderIds>
          <t:DistinguishedFolderId Id="inbox" />
        </t:FolderIds>
        <t:EventTypes>
          <t:EventType>NewMailEvent</t:EventType>
        </t:EventTypes>
      </m:StreamingSubscriptionRequest>
    </m:Subscribe>
  </soap:Body>
</soap:Envelope>
```

**Comment by gautamsi** [comment]
```ts
var svc = new ExchangeService(/*...args..*/);
svc.HttpHeaders = {};
svc.HttpHeaders["Cookie"] = "X-BackEndOverrideCookie=CO1PR06MB222.namprd06.prod.outlook.com~1941996295";
// OR
svc.HttpHeaders = {"Cookie":"X-BackEndOverrideCookie=CO1PR06MB222.namprd06.prod.outlook.com~1941996295"};
```

anything you pass here will be inserted in headers, this option exist in current version.

**Comment by istersin** [comment]
I already did set it like that, just was not sure if that's correct.. According to the MS docs, once you set that cookie header on your subsequent subscriptions requests, you should not be getting that header back in the rest of the responses (you are supposed to cache it), BUT I am getting it back, thus making me think that setting the cookie like this does not work. - That is, the cookie is not being sent, and Exchange thinks I did not get it so it sends it in every request until I send it back..

Quoting the docs, from the same link above:

> Sadie’s subscription response looks like this. Note that it does not include the X-BackEndOverrideCookie. The client is responsible for caching that value for future requests.

**Comment by gautamsi** [comment]
turn on debug log if off. `EwsLogging.DebugLogEnabled = true` it will log the request which you can verify if all headers are sent or not.

**Comment by istersin** [comment]
I do see the headers being set, that is not the problem.. Closing for now, will investigate further
