### ISSUE TITLE
Mismatch Between Stored Timezones and Intl 

### ISSUE THREAD

**Issue by BennettJames** [gautamsi/ews-javascript-api#196]
Hello,

I think there's a mismatch between moment's timezones (which I believe are derived from the Intl object) and the values stored in the `tzmapping.ts` file. Just as an example - moment uses "US/Mountain" for US Mountain time, whereas `tzmapping.ts` has it stored as "US Mountain Standard Time". For node, this will cause the service to fail to start if the timezone isn't stored due to the assertion here: https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/TimeZoneInfo.ts#L157-L176

As an alternative: I wonder if the fallback should always just create a custom time zone from the moment data, presuming it returns a guess. Perhaps something like this:
```ts
let tzGuess: string = moment.tz.guess();                                                                                                     
let offset: number = moment().utcOffset();                                                                                                   
if (StringHelper.IsNullOrEmpty(tzGuess)) {                                       
  console.assert(false, "Unabele to guess timezone, switching to Utc");                                                                    
  return this.Utc;                                                                                                                         
}
if (StringHelper.IsNullOrEmpty(TimeZoneMappingData[tzGuess])) {
  this._localTimeZone = this.CreateCustomTimeZone(tzGuess, TimeSpan.FromMinutes(offset), tzGuess, tzGuess);
}
```
Which would generate a local time zone from the given offset from moment.js, and just populate the strings with whatever simple value it gives back. If this would, I could draw up a patch with the change. I haven't tested this though - I don't know if the `TimeZoneInfo` value must have specific string values to work.

Thanks,

-Bennett

**Comment by BennettJames** [comment]
Quick followup - I think the general principle of the above change would work. I actually tried to override *all* of tzmappings with moment data and it seems to work fine:
```ts
  const moment = require('moment-timezone');
  const zoneMap = require('ews-javascript-api/js/tzmapping').TimeZoneMappingData;
  Object.keys(zoneMap).forEach((zone) => delete zoneMap[zone]);
  moment.tz.names().forEach((name) => {
    zoneMap[name] = name;
  });
```
I'm actually a little curious about the source of the current values - were they taken from C#'s own `TimeZoneInfo` class?

**Comment by gautamsi** [comment]
I have build that data from fusion of Windows `TimeZoneInfo.GetSystemTimeZones()` and IANA database. packed in moment inspired fomat. it still usage moment to figure out some information on the fly rather than packing everything on its own. 

I have included an export `CustomTimeZoneMappingData` object where you can add custom mapping not packed already. like there was one I did based on #189. see tzmappingex.ts file. 
use: `CustomTimeZoneMappingData["missing tz"] = "nearest mapped IANA/c# name"`

packing c# value is required as server always sends back c# value which is inaccessible inside nodejs. plesae suggest if you see a better way to pack the data considering required parsing of server based c# values.

**Comment by BennettJames** [comment]
I did see the `CustomTimeZoneMappingData` object, but in this case an error is thrown unless the time zone is found in the `TimeZoneMappingData` object. Is there any way to get around that lookup in `CreateLocal`? Maybe the lookup should fall back to the custom map if the lookup on [this line](https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/TimeZoneInfo.ts#L160) fails?

**Comment by BennettJames** [comment]
From reading issue #189 a little more closely - looks like maybe the source of this issue is that I am not passing in a `TimeZoneInfo` when constructing the service, and it throws an error when trying to auto-generate this value. I'll try generating my own from moment data and passing it in to see if that deals with the issue.

**Comment by gautamsi** [comment]
you can create TimeZoneInfo instance like this - `TimeZoneInfo.FindSystemTimeZoneById("Sakhalin Standard Time")`

you can pass `moment_timezone.guess()` in `FindSystemTimeZoneById`
