### ISSUE TITLE
Access Office365

### ISSUE THREAD

**Issue by quancao** [gautamsi/ews-javascript-api#197]
Hi,
Thank you for a great project.
I am investigating some opensources which allow my daemon application extract meeting information and cancel the meeting in Office365 Exchange Online. In fact, my daemon will deploy on Raspberry Pi and send the meeting formation to some embedded display.
I found this project support quite complete Exchange API but I am curious to know if this project has been in any commercial product? 

Thanks,
Quan

**Comment by gautamsi** [comment]
two to three of the regular issue openers are using them in commercial projects. one of them is meeting room system which shows schedule on the screen. I do not have full information as they did not disclose the full product info. I have asked them to provide consent to include their software in usage list. no word yet.

**Comment by gautamsi** [comment]
@quancao were you able to use this in any commercial project, may be you can provide some detail about it.
