### ISSUE TITLE
The example of user availability doesn't work

### ISSUE THREAD

**Issue by AshwinKheta** [gautamsi/ews-javascript-api#200]
The example of user availability which I had used by replacing dummy username and password and valid email addresses of attendees didn't work at first, it gave an error saying that '.asMilliseconds()' is not a function and later when i removed this then again gave an error having error code 5010. It would be really great to hear form you if I had made some error using your code or if the error has any solution. Or am I missing any configuration?

Regards,
Ashwin

**Comment by gautamsi** [comment]
fixed example in readme. try again.

**Comment by AshwinKheta** [comment]
Thanks for the reply its working fine now thanks again
