### ISSUE TITLE
Failed to get the ItemAttachment

### ISSUE THREAD

**Issue by Uoliver** [gautamsi/ews-javascript-api#201]
when i used below code to load the attachment(it is a .msg attachment, in EWS is an ItemAttachment not FileAttachment) , an error occurred, error information:**The element at position 0 is invalid.** maybe is a bug to process the ItemAttachment, may you help ? thanks in advance.

below is the related code:
email.Load(new ews.PropertySet(ews.BasePropertySet.IdOnly, [ews.ItemSchema.Attachments, ews.ItemSchema.HasAttachments])).then(() => {
                    email.Attachments.Items.forEach(attach => {
                        console.log(attach.Items);
                        console.log('will load attach ' + attach.name + ' -----------------------------------');
                        attach.Load().then(() => {
                            console.log(attach.Base64Content);
                        }, error => {
                            console.log('Couldn\'t be loaded! ');
                            console.log(JSON.stringify(Object.keys(attach)));
                        });
                    }, (error) => {
                        if (error) {
                            console.log(error)
                        }
                    });
                }, (error) => {
                    if (error) {
                        console.log(error)
                    }
                });

**Comment by gautamsi** [comment]
did [this](https://github.com/gautamsi/ews-javascript-api/issues/163) not fix your issue?

**Comment by gautamsi** [comment]
reopen if you still have this issue and #163 did not fix for you.

**Comment by magnus-hansson** [comment]
Hi, first I would like to thank for your hard work on this library.
I am using 0.9.4 and I get this same error "The element at position 0 is invalid" when trying to do a .Load() on a attachment which is a email. I wonder if you have some pointers when working with ItemAttachments ?

**Comment by ramingar** [comment]
Sorry for the delay in the reply. I'm unable to contribute because I have not ever use Typescript. But I'm sure the problem is that: when you drag and drop an email into another, you are creating a link not a copy of a real file... so ews-javascript-api crashes while it loads the attachment.

**Comment by 1056109** [comment]
possible workaround for this: https://github.com/gautamsi/ews-javascript-api/issues/389#issuecomment-1010821742
