### ISSUE TITLE
Accept the self-signed certificate

### ISSUE THREAD

**Issue by quancao** [gautamsi/ews-javascript-api#202]
Hello Gautamsi,

Is there any option for ews-javascript-api module to accept self-signed certificate of EWS server ?
I created an Exchange Server 2010 and generated a self-signed certificate. When I use this module to access to my EWS server, I got the error 

```
Error in calling service, error code:0

SoapFaultDetails {
  message: 'unable to verify the first certificate',
  stack: [Getter/Setter],
  InnerException: null,
  faultCode: null,
  faultString: null,
  faultActor: null,
  responseCode: 127,
  errorCode: 0,
  exceptionType: null,
  lineNumber: 0,
  positionWithinLine: 0,
  errorDetails: DictionaryWithStringKey { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] },
  HttpStatusCode: 0 }
Error in calling service, error code:0

Unhandled rejection Error: unable to verify the first certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
```
Thanks,
CDQ

**Comment by gautamsi** [comment]
have you tried setting this 
`process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';`

**Comment by quancao** [comment]
Yes, already but still got issue.

**Comment by gautamsi** [comment]
are you using NTLM authentication?

**Comment by quancao** [comment]
No, I use basic authentication.
I just switch to NTML authentication by using your module ews-javascript-api-auth and it seems work now.
Thanks

**Comment by gautamsi** [comment]
is your exchange server configured to us basic authentication? that could be the issue.

**Comment by julestruong** [comment]
is there any way to do it in basic authent ?
