### ISSUE TITLE
ExchangeWebService.d.ts implicit any warnings

### ISSUE THREAD

**Issue by bensiron** [gautamsi/ews-javascript-api#203]
getting errors when compiling typescript files to javascript and using ews-javascript-api 0.91 in the file ExchangeWebService.d.ts:

function RemoveEntry<T>(array: Array<T>, entry: T, comparer?: (T) => boolean): boolean
error TS7006: Parameter 'T' implicitly has an 'any ' type.  

changing this to:
function RemoveEntry<T>(array: Array<T>, entry: T, comparer?: (item: T) => boolean): boolean
fixes the warning

there are three other warnings like this:
node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts(4352,35): error TS7006: Parameter 'key' implicitly has an 'any' type.
node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts(15240,13): error TS7006: Parameter 'string' implicitly has an 'any' type.
node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts(15241,23): error TS7006: Parameter 'any' implicitly has an 'any' type.

am I doing something wrong?

**Comment by gautamsi** [comment]
you may have set `noImplicitAny` option to `true` in tsconfig or in command line. I have not done strict checking yet. track #121 which would use all the latest typescript feature.

**Comment by bensiron** [comment]
OK, thanks.  In the meantime, I set "skipLibCheck": true in my tsconfig.json file to ignore errors from d.ts files, rather than disable noImplicitAny.
