### ISSUE TITLE
ews 401 unauthorized error

### ISSUE THREAD

**Issue by SummitGit** [gautamsi/ews-javascript-api#204]
Hi,

I am trying to use your api and I am getting 401 unauthorised error when trying to use the example which you have shared. I went through the various issues which were faced by others while using this library. I am just using basic auth as when I type in the url then I am shown a small dialog with username and password.
Also, in the exchange credential constructor I have tried passing all the valid formats (domain\\username, emailId).
Can you please point me to the correct path of using your library successfully.
Attaching the code snippet which I am trying to use. Also, the error which I am facing.

[gautamgitissue.pdf](https://github.com/gautamsi/ews-javascript-api/files/1317688/gautamgitissue.pdf)

**Comment by gautamsi** [comment]
from the error message it seems you are trying in browser, correct? you can not use this in browser (with CORS enabled) due to security issue. only place you can use this i browser is use in Electron/Ionic.

**Comment by SummitGit** [comment]
Hi Gautam,
Thanks for the prompt reply.Yes I am using browser.Could you please tell me if there is anyway to disable CORS on the server itself.
Regards,Summit 

    On Wednesday, September 20, 2017 11:44 PM, Gautam Singh <notifications@github.com> wrote:
 

 from the error message it seems you are trying in browser, correct? you can not use this in browser (with CORS enabled) due to security issue. only place you can use this i browser is use in Electron/Ionic.—

**Comment by gautamsi** [comment]
you can not disable CORS on server side. Exchange does not support OPTIONS verb.

**Comment by shahzaibrashid** [comment]
Hi,

I'm also getting 401 Unauthorized error. I'm using your example script in ubuntu server with Node version 4.8.

My code snippet:
`
const EWS = require('ews-javascript-api');

const ExchangeService = EWS.ExchangeService;
const ExchangeVersion = EWS.ExchangeVersion;
const ExchangeCredentials = EWS.ExchangeCredentials;
const Uri = EWS.Uri;
const DateTime = EWS.DateTime;
const CalendarView = EWS.CalendarView;
const WellKnownFolderName = EWS.WellKnownFolderName;
const EwsLogging = EWS.EwsLogging;

//import { ExchangeService, ExchangeVersion, ExchangeCredentials, Uri, DateTime, CalendarView, WellKnownFolderName, EwsLogging } from "ews-javascript-api";
const credentials = require("./credentials"); //for username and password

EwsLogging.DebugLogEnabled = false;

var service = new ExchangeService(ExchangeVersion.Exchange2016);
service.Credentials = new ExchangeCredentials(credentials.userName, credentials.password);
service.Url = new Uri("https://x.x.x.x/Ews/Exchange.asmx");

var view = new CalendarView(DateTime.Now.Add(-1, "week"), DateTime.Now.Add(1, 'week')); // appointments in last one week.
service.FindAppointments(WellKnownFolderName.Calendar, view).then((response) => {
    let appointments = response.Items;
    let appointment = appointments[0];
    console.log("Subject: " + appointment.Subject);
    console.log("Start Time: " + appointment.Start);
    console.log("End Time: " + appointment.End);
    console.log("Recipients: ");
    appointment.RequiredAttendees.Items.forEach((a) => {
        console.log(a.Address);
    });
    console.log("unique id: " + appointment.Id.UniqueId, true, true);

}, function (error) {
    console.log(error)
})
`

Please point me to correct direction.

**Comment by gautamsi** [comment]
@shahzaibrashid : are you using user name in any format other than email/upn?
