### ISSUE TITLE
FindItems / FindAppointments returns empty Dates

### ISSUE THREAD

**Issue by rile81** [gautamsi/ews-javascript-api#205]
I hope someone can help me out in pointing out what I'm doing wrong.
I'm trying to request Calendar events (either by FindItems or FindAppointments) and items are returned but the response has empty dates.

var f = new ews.FolderId(ews.WellKnownFolderName.Calendar, new ews.Mailbox(id));
var cv = new ews.CalendarView(new ews.DateTime(start), new ews.DateTime(end), maxItemsReturned);
var finditems = exch.FindItems(f,cv);

`CalendarItem:
                     { __prefix: 't',
                       __type: 'CalendarItem',
                       ItemId:
                        { __prefix: 't',
                          __type: 'ItemId',
                          Id: 'AAMkAGZjNDBlODI3LWJiNTctNGZjYS04M2ZhLTIxODExOTQ5NWRjMABGAAAAAAAXSw2UFTmiTba5AftujtdHBwAjC4kvqsLDTq/6HLhoiDhJAAAAAAENAAAjC4kvqsLDTq/6HLhoiDhJAAAIYov/AAA=',
                          ChangeKey: 'DwAAABYAAAAjC4kvqsLDTq/6HLhoiDhJAACLW8WN' },
                       ParentFolderId:
                        { __prefix: 't',
                          __type: 'ParentFolderId',
                          Id: 'AAMkAGZjNDBlODI3LWJiNTctNGZjYS04M2ZhLTIxODExOTQ5NWRjMAAuAAAAAAAXSw2UFTmiTba5AftujtdHAQAjC4kvqsLDTq/6HLhoiDhJAAAAAAENAAA=',
                          ChangeKey: 'AQAAAA==' },
                       ItemClass: 'IPM.Appointment',
                       Subject: 'My Subject',
                       Sensitivity: 'Normal',
                       DateTimeReceived: '2017-03-29T07:21:22Z',
                       Size: '41401',
                       Importance: 'Normal',
                       IsSubmitted: 'false',
                       IsDraft: 'false',
                       IsFromMe: 'false',
                       IsResend: 'false',
                       IsUnmodified: 'false',
                       DateTimeSent: '2017-03-29T07:21:22Z',
                       DateTimeCreated: '2017-03-29T07:21:39Z',
                       ReminderDueBy: '2017-09-04T22:00:00Z',
                       ReminderIsSet: 'false',
                       ReminderNextTime: '4501-01-01T00:00:00Z',
                       ReminderMinutesBeforeStart: '1080',
                       DisplayCc: null,
                       DisplayTo: 'John Doe',
                       HasAttachments: 'false',
                       Culture: 'nl-NL',
                       EffectiveRights:
                        { __prefix: 't',
                          __type: 'EffectiveRights',
                          CreateAssociated: 'false',
                          CreateContents: 'false',
                          CreateHierarchy: 'false',
                          Delete: 'true',
                          Modify: 'true',
                          Read: 'true',
                          ViewPrivateItems: 'true' },
                       LastModifiedName: 'John Doe',
                       LastModifiedTime: '2017-09-04T07:07:34Z',
                       IsAssociated: 'false',
                       WebClientReadFormQueryString: 'https://outlook.office365.com/owa/?itemid=AAMkAGZjNDQ5NWRjMABGENAAAjC4kvqsLDTq%2F6HLhoiDhJAAAIYov%2FAAA%3D&exvsurl=1&path=/calendar/item',
                       ConversationId:
                        { __prefix: 't',
                          __type: 'ConversationId',
                          Id: 'AAQkAGZjNDBlODI3LWJiNTctNGZjYS04M2ZhLTIxODExOTQ5NWRjMAAQAIu/Y=' },
                       Flag: { __prefix: 't', __type: 'Flag', FlagStatus: 'NotFlagged' },
                       InstanceKey: 'AQAAAAAAAQ0BAAAACGKL/wAAAAA=',
                       UID: '040000008200E00074C5B7101A82E0080000000030BCD6D46DA8D2010000000B8C56E0EA3',
                       DateTimeStamp: '2017-09-04T07:07:34Z',
                       Start: '2017-09-04T22:00:00Z',
                       End: '2017-09-06T22:00:00Z',
                       IsAllDayEvent: 'true',
                       LegacyFreeBusyStatus: 'Free',
                       Location: null,
                       IsMeeting: 'false',
                       IsCancelled: 'false',
                       IsRecurring: 'false',
                       MeetingRequestWasSent: 'false',
                       IsResponseRequested: 'true',
                       CalendarItemType: 'Single',
                       MyResponseType: 'Unknown',
                       Organizer:
                        { __prefix: 't',
                          __type: 'Organizer',
                          Mailbox:
                           { __prefix: 't',
                             __type: 'Mailbox',
                             Name: 'John Doe',
                             EmailAddress: '/O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GROUP (FYDIBOHF23SPDLT)/CN=RECIPIENTS/CN=D2D22CFF4EF9476EBBDC38-JOHND',
                             RoutingType: 'EX',
                             MailboxType: 'OneOff' } },
                       Duration: 'P2D',
                       TimeZone: '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna',
                       AppointmentSequenceNumber: '0',
                       AppointmentState: '0',
                       ConferenceType: '0',
                       AllowNewTimeProposal: 'true',
                       IsOnlineMeeting: 'false',
                       NetShowUrl: null,
                       StartWallClock: '2017-09-05T00:00:00+02:00',
                       EndWallClock: '2017-09-07T00:00:00+02:00',
                       StartTimeZoneId: 'W. Europe Standard Time',
                       EndTimeZoneId: 'W. Europe Standard Time',
                       IntendedFreeBusyStatus: 'NoData',
                       IsOrganizer: 'true' }`

Then every Date is returned like this (all other properties are returned correctly:

`[DateTimePropertyDefinition]            Loading property :              DateTimeStamp
{ [Number: 1504508854000]
  kind: 2,
  originalDateInput: null,
  getMomentDate: [Function],
  setMomentDate: [Function] }
[ScopedDateTimePropertyDefinition]              Loading property :              Start
{ [Number: 1504562400000]
  kind: 2,
  originalDateInput: null,
  getMomentDate: [Function],
  setMomentDate: [Function] }
[ScopedDateTimePropertyDefinition]              Loading property :              End
{ [Number: 1504735200000]
  kind: 2,
  originalDateInput: null,
  getMomentDate: [Function],
  setMomentDate: [Function] }`

When requesting availability (GetUserAvailability) I don't have this problem and all dates are returned correctly.

**Comment by gautamsi** [comment]
still facing this issue?
