### ISSUE TITLE
Debugger statements

### ISSUE THREAD

**Issue by efredin** [gautamsi/ews-javascript-api#207]
Is there any plan to remove the numerous debugger statements from the code base?  Sending an email with the debugger attached results in at least 3 breakpoints and that's on a successful send.

**Comment by gautamsi** [comment]
you can disable them in your js file. let me fix that in next build

**Comment by fgreinus** [comment]
Just call `EwsLogging.DebugLogEnabled = false` if someone is curious about it.

**Comment by gautamsi** [comment]
debugger statement is used for stopping in middle of debugging. `EwsLogging.DebugLogEnabled = false1 only stops printing debug info to console.
