### ISSUE TITLE
Fetch Contacts and Create Meetings not implemented

### ISSUE THREAD

**Issue by alkasain** [gautamsi/ews-javascript-api#21]
Hi Gautam,

I am trying to fetch contact but I did not find any method to achieve this. I think its not yet implemented.  Also, for creating new meeting using Appointment.Save I am not able to add RequiredAttendees & OptionalAttendees. Is there any other way to create new meeting? If not then Any plans to implement both these functionalities?

**Comment by gautamsi** [comment]
I have slowed down progress as I did not see much traffic or use by others in recent past. 

Now that I see someone is interested, I can work on requested feature. That is the idea for now. 

Keep your requests coming in. Do open other issues with features you want to use. will add that to my todo. If it is simple port, I can fix it within few days. if it is complex or require new workaround, will let you know about the delay.

**Comment by gautamsi** [comment]
can you provide Create meeting code you are trying

**Comment by alkasain** [comment]
Thank you so much Gautam for your prompt and positive reply. I used Appointment.Save to create new meeting with required and optional attendees and I got error that RequiredAttendees is not implemented. I also tried to use exchange.CreateItem() method but that too didn't worked.

Please find the code snippet:

var appointment = new ews.Appointment(exch);
        var today = new Date();
        appointment.Start = new ews.DateTime(new Date(today.getFullYear(),today.getMonth(),today.getDate(),3,30,0));
        appointment.End = new ews.DateTime(new Date(today.getFullYear(),today.getMonth(),today.getDate(),4,0,0));
        appointment.Location = "Plot 371 2nd floor";
        
        appointment.RequiredAttendees.Add('alkasaini@gmail.com');
        appointment.OptionalAttendees.Add('alka.saini@gmail.com');
       
        appointment.Save(ews.SendInvitationsMode.SendToAllAndSaveCopy).then( function(response) {
            console.log("------------");
        }, function(ei) {
            console.log(ei.stack, ei.stack.split("\n"));
            console.log("error");
        });

Thanks,
Alka Saini

**Comment by gautamsi** [comment]
try with latest from npm. o.2.3 can get you work with Appointment creation and sending.  Try working with responding to meeting request and report any issues. 

It took more time than what I anticipated. Fetch Contact should be done in next few days, latest by next weekend.

**Comment by alkasain** [comment]
Thank you Gautam, In latest 0.2.3 version, Appointment.Save is working fine.

**Comment by gautamsi** [comment]
glad that it worked for you, I am working on contacts stuff over next week.

**Comment by gautamsi** [comment]
Contacts can be accessed 2 ways
1. `ExchaangeService.ResolveName` method
2. `ContactsFolder.Bind` static methods

Check EWS documentation for example. method 2 is not yet on NPM, you can build from source for time being

I usually test few function before updating npm, this time I have tested anything yet. only Code updates.

**Comment by gautamsi** [comment]
v0.2.4 published

**Comment by alkasain** [comment]
Thank you Gautam for the update, As per your suggestion, I tried to use 2 method for contacts bind by building the source but somehow its not working. I need to fetch the WellKnownFolderName.QuickContacts only not all the contacts as of now.

Thanks,
Alka Saini

**Comment by gautamsi** [comment]
found few bugs which would prevent getting PhoneNumbers and ImAddresses. fix coming in 0.2.5

try this when I push 0.2.5 later this week
```js
import credentials = require("./credentials"); //username and password
var ews = require('ews-javascript-api');
ews.EwsLogging.DebugLogEnabled = false;
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);
exch.Credentials = new ews.ExchangeCredentials(credentials.userName, credentials.password);
exch.Url = new ews.Uri("https://outlook.office365.com/Ews/Exchange.asmx");
exch.FindItems([new ews.FolderId(ews.WellKnownFolderName.QuickContacts)], null, null, new ews.ItemView(10), null, ews.ServiceErrorHandling.ReturnErrors)
    .then(function(resp) {
        resp.Responses[0].Results.Items.forEach(function(item){
            ews.EwsLogging.Log([
                item.DisplayName,
                item.PhoneNumbers.Entries.Values,
                item.EmailAddresses.Entries.Values,
                item.Subject,
                item.ImAddresses.Entries.Values

            ], true, true);
        });
        //EwsLogging.Log(resp.Responses, true, true);
        console.log("------------");
    }, function(ei) {
        console.log(ei.stack, ei.stack.split("\n"));
        console.log("error");
    });
```

**Comment by gautamsi** [comment]
0.2.5 published, please test again.

**Comment by alkasain** [comment]
Thanks a lot... Its working.

**Comment by gautamsi** [comment]
thanks for the confirmation, please open more bugs when you found them.
