### ISSUE TITLE
Getting an "unable to get local issuer certificate" error. How to add an exception for my local CA issuer?

### ISSUE THREAD

**Issue by Saganus** [gautamsi/ews-javascript-api#211]
Hello,

I found this very useful project and I'm trying to use it to connect to an Exchange server, however I'm getting an "unable to get local issuer certificate".

I believe the cause is because the server is using TLS but the certificate is signed by a local CA, and since I don't have the issuer CA it fails.

The reason I suspect this is why I'm getting an error is because if I connect with a browser to the Exchange server address I'm trying to access, I get the certificate issuer error as well. However in a browser I can add an exception and carry on.

How can I do the same with your library? i.e. adding the issuer's CA to an exception list or somehow bypass that check?

Or, another option I think, if I save the certificate with Firefox for example, how can I use that CA certificate with the ews-javascript-api library so that it accepts the Exchange server certificate as valid (since I have the issuer's certificate)?

Thanks!

**Comment by Saganus** [comment]
Uhmm...apparently this is a NodeJS Issue and not an ews-javascript-api one.

**Comment by Saganus** [comment]
Apparently it might be a compound issue. Do you have any potential fixes for this?

Even if I add

`NODE_TLS_REJECT_UNAUTHORIZED=0`

before running node (even version 8.8.0), the request fails with

```
SoapFaultDetails {
  message: 'unable to get issuer certificate',
  InnerException: null,
  faultCode: null,
  faultString: null,
  faultActor: null,
  responseCode: 127,
  errorCode: 0,
  exceptionType: null,
  lineNumber: 0,
  positionWithinLine: 0,
  errorDetails: DictionaryWithStringKey { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] },
  HttpStatusCode: 0 }
```
However if I use the same env var and do 

```
const https = require('https');
https.get('https://myselfsigned.rootca.server.com');
```
It works fine, so the env var is actually preventing the error for a nodejs app, but not if I use your library. 

Is there a way to do the same with your library? i.e. use an env var or other setting to ignore the 'unable to get issuer certificate' error?

Thanks!

**Comment by gautamsi** [comment]
still having issues?

**Comment by Saganus** [comment]
Not anymore.

turns out I was both, usingthe wrong Root CA cert and the incorrect nodejs flag

**Comment by roeintense** [comment]
Can we get clarification on your solution @Saganus ? I see no way to change certificates or adjust flags. I have `NODE_TLS_REJECT_UNAUTHORIZED=0` in my environment as well and I continue to get certificate problems. Please advise @gautamsi

**Comment by gautamsi** [comment]
see this https://github.com/gautamsi/ews-javascript-api/issues/233#issuecomment-390703244
