### ISSUE TITLE
Does version 0.6.0 support Exchange 2016?

### ISSUE THREAD

**Issue by rousselle** [gautamsi/ews-javascript-api#212]
Quick question

**Comment by gautamsi** [comment]
why do you need version 0.6? can you not upgrade to 0.9?

**Comment by gautamsi** [comment]
BTW, this will still work with the functionality implemented. You can not choose `ExchangeVersion` to 2016 if it is not there in build. you can select downlevel `ExchangeVersion` enum anyways

**Comment by gautamsi** [comment]
non issue, continue to comment if needed.
