### ISSUE TITLE
Error: unable to verify the first certificate

### ISSUE THREAD

**Issue by Yonysun** [gautamsi/ews-javascript-api#215]
I got this error when i connect ews  using ews-javascript-api

![1111](https://user-images.githubusercontent.com/3928873/33164267-f7cf2466-d06c-11e7-94c8-bbe3441205c9.png)

how can i solve it

**Comment by gautamsi** [comment]
have you checked #202 ?

**Comment by gautamsi** [comment]
it could be duplicate. let me know if you have more information on this. will close after a week if no response.
