### ISSUE TITLE
Send Message as HTML

### ISSUE THREAD

**Issue by Marmoro** [gautamsi/ews-javascript-api#217]
I get the following response when sending message with HTML tags

`{ Violation: 'The element \'http://schemas.microsoft.com/exchange/services/2006/types:Body\' cannot contain child element \'b\' because the parent element\'s content model is text only.' }`

My code is based on Wiki:
```
var msgattach = new ews.EmailMessage(exch);
msgattach.Subject = "test from ews";
msgattach.Body = new ews.MessageBody(0, "Hell<b>o</b>");
```

**Comment by gautamsi** [comment]
see this https://github.com/gautamsi/ews-javascript-api/issues/81#issuecomment-235620076

you need to escape HTML body.
