### ISSUE TITLE
The SMTP address has no mailbox associated with it

### ISSUE THREAD

**Issue by nicpolhamus** [gautamsi/ews-javascript-api#220]
Hello,

Whenever I’m trying to find items in a shared mailbox, I’m getting the following error
```
ServiceResponseException {
    message: 'The SMTP address has no mailbox associated with it.'
}
```
I’m trying to access the inbox of a shared mailbox so that I can parse emails in the inbox.

**Comment by gautamsi** [comment]
how are you doing this? code sample please.

**Comment by soptimizer** [comment]
Hi,
iam getting same error.

sample : mailname@domain.com

when i try to login from owa i use just  mailname and password.

but when i try in ews-javascript-api i getting this error.
```
ServiceResponseException {
    message: 'The SMTP address has no mailbox associated with it.'
}
```
I tried EWSEditor.exe and there is no problem.

Not : when i use @domain.com on browser i cannot connect.

Additionally i tried with domain\mailname and password. but did not work.

**Comment by gautamsi** [comment]
please add solution for others

**Comment by Cescx0f** [comment]
Hi, i have the same error, @soptimizer can you share the solution for this problem? please

**Comment by Farham0** [comment]
please add solution for others

**Comment by Farham0** [comment]
@soptimizer can you share the solution for this problem? please
