### ISSUE TITLE
Access properties of Appointments

### ISSUE THREAD

**Issue by kitzler-walli** [gautamsi/ews-javascript-api#221]
When I try to access empty properties of an appointment I receive the error: "Unhandled rejection null"

How can I capture this error or simply get "null" as a result when I try to access "Body" or "TextBody"?

**Comment by gautamsi** [comment]
this is due to fact that how c# code is written. I will make an improvement over this in next build.

**Comment by do0g** [comment]
Hi @gautamsi, I'm seeing a similar problem but it seems that accessing the `Body` property for any appointment _always_ throws. Any chance you'll be looking at this in the near future, or can you point me in the right direction and I'll submit a PR?

**Comment by gautamsi** [comment]
checked code, it does return null if the value is loaded from server and is null. 

this is an issue if the property was not loaded from server (use `item.Load`).
