### ISSUE TITLE
Disable EWS connection logs

### ISSUE THREAD

**Issue by maximecuny** [gautamsi/ews-javascript-api#222]
Hello,

Everything is working fine, however I would really like to disable all the logs that popup when I do an operation. Is there a way to do that?

Thank you :)

**Comment by gautamsi** [comment]
https://github.com/gautamsi/ews-javascript-api/issues/207#issuecomment-335421214

simple search would help faster 😄 

`EwsLogging.DebugLogEnabled = false` before you initialize `ExchangeService`
