### ISSUE TITLE
Setting timeout in underlying request library

### ISSUE THREAD

**Issue by swiatek25** [gautamsi/ews-javascript-api#223]
Hi,

It seems that setting `EWS.Timeout` does not cause any effect. Any example/idea how I could propagate that value down? Or maybe you are planning to do that in feature version?

Thanks in advance,

**Comment by gautamsi** [comment]
current implementation does not make use of this. I can take a look in future, no promise

**Comment by wustwg** [comment]
> current implementation does not make use of this. I can take a look in future, no promise

this is very important....

**Comment by PhilHannent** [comment]
Hi, I think I am bumping into this issue with my system. 

I am seeing requests to O365 take a long time to return anything and then just closing. With many request being made and then a lot of them ending hanging for 1-2 mins it then creates a backlog of request and this builds up and up until my app hangs.

I've got no way to set a timeout to be 10 seconds or to cancel a request that is inflight.

**Comment by gautamsi** [comment]
I see that there may be solution already which I never checked. 

@PhilHannent do you want to try this:

```js
import { XHRDefault } from "./XHRDefault";
svc.XHRApi = new XHRDefault({timeout: 10000});
```

if you are using `@ewsjs/xhr`
```js
import { XhrApi } from "@ewsjs
svc.XHRApi = new XhrApi({timeout: 10000, ...otherrequstoptions});
```

**Comment by wustwg** [comment]
> I see that there may be solution already which I never checked.
> 
> @PhilHannent do you want to try this:
> 
> ```js
> import { XHRDefault } from "ews-javascript-api";
> svc.XHRApi = new XHRDefault({timeout: 10000, ...otherFetchOptions});
> ```
> 
> if you are using `@ewsjs/xhr`
> 
> ```js
> import { XhrApi } from "@ewsjs/xhr"
> svc.XHRApi = new XhrApi({timeout: 10000, ...otherrequstoptions});
> ```

I have read the fetch source , I dought that the timeout don't work normally.

`FetchStream.prototype._runStream = function (url_data, url) {

  var req = url_data.transport.request(url_data.urloptions, (function (res) {

      // catch new cookies before potential redirect
      if (Array.isArray(res.headers['set-cookie'])) {
          for (var i = 0; i < res.headers['set-cookie'].length; i++) {
              this.cookieJar.setCookie(res.headers['set-cookie'][i], url);
          }
      }

      if ([301, 302, 303, 307, 308].indexOf(res.statusCode) >= 0) {
          if (!this.options.disableRedirects && this.options.maxRedirects > this._redirect_count && res.headers.location) {
              this._redirect_count++;
              req.destroy();
              this.runStream(urllib.resolve(url, res.headers.location));
              return;
          }
      }

      this.meta = {
          status: res.statusCode,
          responseHeaders: res.headers,
          finalUrl: url,
          redirectCount: this._redirect_count,
          cookieJar: this.cookieJar
      };

      var curlen = 0,
          maxlen,

          receive = (function (chunk) {
              if (curlen + chunk.length > this.options.maxResponseLength) {
                  maxlen = this.options.maxResponseLength - curlen;
              } else {
                  maxlen = chunk.length;
              }

              if (maxlen <= 0) {
                  return;
              }

              curlen += Math.min(maxlen, chunk.length);
              if (maxlen >= chunk.length) {
                  if (this.responseBuffer.length === 0) {
                      this.responseBuffer = chunk;
                  } else {
                      this.responseBuffer = Buffer.concat([this.responseBuffer, chunk]);
                  }
              } else {
                  this.responseBuffer = Buffer.concat([this.responseBuffer, chunk], this.responseBuffer.length + maxlen);
              }
              this.drainBuffer();
          }).bind(this),

          error = (function (e) {
              this.ended = true;
              this.emit('error', e);
              this.drainBuffer();
          }).bind(this),

          end = (function () {
              this.ended = true;
              if (this.responseBuffer.length === 0) {
                  this.push(null);
              }
          }).bind(this),

          unpack = (function (type, res) {
              var z = zlib['create' + type]();
              z.on('data', receive);
              z.on('error', error);
              z.on('end', end);
              res.pipe(z);
          }).bind(this);

      this.emit('meta', this.meta);

      if (res.headers['content-encoding']) {
          switch (res.headers['content-encoding'].toLowerCase().trim()) {
              case 'gzip':
                  return unpack('Gunzip', res);
              case 'deflate':
                  return unpack('InflateRaw', res);
          }
      }

      res.on('data', receive);
      res.on('end', end);

  }).bind(this));

  req.on('error', (function (e) {
      this.emit('error', e);
  }).bind(this));

  if (this.options.timeout) {
      req.setTimeout(this.options.timeout, req.abort.bind(req));
  }
  this.on('destroy', req.abort.bind(req));

  if (this.options.payload) {
      req.end(this.options.payload);
  } else if (this.options.payloadStream) {
      this.options.payloadStream.pipe(req);
      this.options.payloadStream.resume();
  } else {
      req.end();
  }
};`

I'm not good at nodejs, do you think the timeout work normally? Is it possible the "req" destroy but not callback ?

**Comment by gautamsi** [comment]
if you have issues with fetch lib, try using `@ewsjs/xhr` which uses requestjs

**Comment by PhilHannent** [comment]
Thanks. We are using @ewsjs/xhr, I'll review it and see about applying it this weekend. The problem only manifests itself on production and only at random times so this is going to be hard to pin down.

As a side note, RequestJS has been depreciated, I've been moving my work to node-fetch, which is a much smaller dependency.
https://github.com/request/request
