### ISSUE TITLE
GetUserAvailability Error resronseCode: 127 and timeouts

### ISSUE THREAD

**Issue by rousselle** [gautamsi/ews-javascript-api#226]
Running this code in production on AWS we're seeing a couple intermittent errors with GetUserAvailability. One is that we sometimes get this error structure:
```javascript
{ message: '',
     InnerException: null,
     faultCode: null,
     faultString: null,
     faultActor: null,
     responseCode: 127,
     errorCode: 0,
     exceptionType: null,
     lineNumber: 0,
     positionWithinLine: 0,
     errorDetails: { keys: [], keysToObjs: {}, objects: {} },
     HttpStatusCode: 503 } 
```
We were wondering if this could be because the ews-javascript-api code is timing out too quickly. If we are reading https://msdn.microsoft.com/en-us/library/microsoft.exchange.webservices.data.exchangeservicebase.timeout(v=exchg.80).aspx correctly, the default timeout is 10 seconds. Is it possible for us to increase this?

The other error we see is that GetUserAvailability sometimes just doesn't return (we timeout after 10 minutes). We're not sure how to debug this.

Any information would be helpful.

Thank you.

**Comment by gautamsi** [comment]
take a look at `js/XHRDefaults.js`

you want to add timeout option to following code
```js
      var options = {
            url: xhroptions.url,
            payload: xhroptions.data,
            headers: xhroptions.headers,
            method: xhroptions.type
        };
```

`timeout:10000 // in milliseconds`

I am using this lib: https://github.com/andris9/fetch
