### ISSUE TITLE
Issues with Autodiscover

### ISSUE THREAD

**Issue by ray73864** [gautamsi/ews-javascript-api#23]
Trying to use the example you have here for autodiscovery and getting user settings however I am hitting a snag when it comes to the Autodiscovery itself.

I have the AutoDiscoverService set up as:

`var autod = new ews.AutodiscoverService(ews.ExchangeVersion.Exchange2013);`

I then do

`autod.Credentials = new ews.ExchangeCredentials("testuser", "testpass", "mydomain");`

I also change the `autod.GetUserSettings()` to have the correct email address in it, however when I run the code via node I get the following issue:

`Determining which endpoints are enabled for host autodiscover.example.com
Host returned enabled endpoint flags: Legacy,Soap,WsSecurity,OAuth
--hard checking for office 365 with node.js http request and presence of header x-federationtrusttokenissueruri: urn:federation:MicrosoftOnline. All other redirection wil fail
Trying to get Autodiscover redirection URL from http://autodiscover.example.com/autodiscover/autodiscover.xml.
--Request error: 403, Forbidden`

(Obviously changed the actual domain to example.com just for this issue)

There is no 'autodiscover' subdomain on my domain, it is 'mail', also, with Exchange 2016 it looks like (at least on my server) that it is: mail.example.com/Autodiscover/Autodiscover.xml (not the capital A).

**Comment by ray73864** [comment]
If I change the first line to

`var autod = new ews.AutodiscoverService(new ews.Uri("https://mail.example.com/Autodiscover/Autodiscover.xml"), ews.ExchangeVersion.Exchange2013);`

and change the second line to

`autod.Credentials = new ews.ExchangeCredentials("testuser@example.com", "testpass");`

I then run the js file using node, it apparently runs the `autod.GetUserSettings()` as it returns the `autod.Url.ToString()` however instead of returning user settings it just returns `undefined`.

**Comment by gautamsi** [comment]
looking into it.

**Comment by gautamsi** [comment]
if you have mail.domain.com configuration and autodiscover.domain.com does not exist, this will not work. 

I can probably fix it later by adding srv record lookup. If there are no autodiscover publishing done, can not fix.

change url to `"https://mail.example.com/Autodiscover/Autodiscover.svc"` when manually assigning url. it should work.

**Comment by jackiehluo** [comment]
@gautamsi Hey! I think I'm experiencing a similar issue—I'm using `https://outlook.office365.com/autodiscover/services.wsdl` for the URL, but the response is consistently `undefined`. Any chance you could help?

**Comment by gautamsi** [comment]
`https://outlook.office365.com/autodiscover/services.wsdl` is  not correct URL for autodiscover. use `https://outlook.office365.com/Autodiscover/Autodiscover.svc` instead

**Comment by jackiehluo** [comment]
@gautamsi Oh, I'm sorry, I pasted the wrong link. Yes—that's the URL I was using! Here's what I get in the console.

```
https://outlook.office365.com/Autodiscover/Autodiscover.svc
undefined
```

**Comment by gautamsi** [comment]
can you post your code please?

**Comment by jackiehluo** [comment]
Thanks for taking a look! I don't think I changed much:

```
//import ews module
var ews = require('ews-javascript-api')
var util = require('util')

//create AutodiscoverService object
var autod = new ews.AutodiscoverService(new ews.Uri("https://outlook.office365.com/Autodiscover/Autodiscover.svc"), ews.ExchangeVersion.Exchange2010);
//set credential for service
autod.Credentials = new ews.ExchangeCredentials(EMAIL_ADDRESS, PASSWORD);

//create array to include list of desired settings
var settings = [
  ews.UserSettingName.InternalEwsUrl,
  ews.UserSettingName.ExternalEwsUrl,
  ews.UserSettingName.UserDisplayName,
  ews.UserSettingName.UserDN,
  ews.UserSettingName.EwsPartnerUrl,
  ews.UserSettingName.DocumentSharingLocations,
  ews.UserSettingName.MailboxDN,
  ews.UserSettingName.ActiveDirectoryServer,
  ews.UserSettingName.CasVersion,
  ews.UserSettingName.ExternalWebClientUrls,
  ews.UserSettingName.ExternalImap4Connections,
  ews.UserSettingName.AlternateMailboxes,
];

//get the setting
autod.GetUserSettings([EMAIL_ADDRESS], settings)
.then((response) => {
    //do what you want with user settings    
    var tabcount = 0;
    var tabs = function () { return ews.StringHelper.Repeat("\t", tabcount); };
    console.log(autod.Url.ToString());
    console.log(response)
    console.log(util.inspect(response, { showHidden: false, depth: null, colors: true }));
    for (var _i = 0, _a = response.Responses; _i < _a.length; _i++) {
        var resp = _a[_i];
        console.log(ews.StringHelper.Format("{0}settings for email: {1}", tabs(), resp.SmtpAddress));
        tabcount++;
        for (var setting in resp.Settings) {
            console.log(ews.StringHelper.Format("{0}{1} = {2}", tabs(), ews.UserSettingName[setting], resp.Settings[setting]));
        }
        tabcount--;
    }
}, function (e) {
  console.log(e)
    //log errors or do something with errors
});
```

**Comment by jackiehluo** [comment]
Ahhh, just got it! I needed to generate an app password. Would be really useful to have a more descriptive error message—I really appreciate the help! This library is great.

**Comment by gautamsi** [comment]
@jackiehluo will track missing error info when failed in #70
