### ISSUE TITLE
ConfigurePromise Sample

### ISSUE THREAD

**Issue by omatrot** [gautamsi/ews-javascript-api#230]
I'd like to switch the Promise library that is used by default because [it fails with Graphcool](https://github.com/graphcool/prisma/issues/1550#issuecomment-358045049).

I'm not an expert of typescript but when I go to definition of an awaitable EWS Method, it tells me about Promise:
> @typescript -- 2.1.1 lib.es6.d.ts Promise Description

I'd like to switch to:
> lib.es2015.symbol.wellknown.d.ts 

I hope I'm clear.
Thanks in advance.

**Comment by gautamsi** [comment]
if you can create bare sample for this problem, I can investigate further. example that you refer is not related to ews-javascript-api.

I think you want to modify [ExchangeWebService.d.ts](https://github.com/gautamsi/ews-javascript-api/blob/master/typings/ExchangeWebService.d.ts) with content of `lib.es2015.symbol.wellknown.d.ts` starting with line https://github.com/gautamsi/ews-javascript-api/blob/6fa705079141a9ea5ce76d877a132d86d2bad1ca/typings/ExchangeWebService.d.ts#L311

and ending with line https://github.com/gautamsi/ews-javascript-api/blob/6fa705079141a9ea5ce76d877a132d86d2bad1ca/typings/ExchangeWebService.d.ts#L552

you have to replace in context of Promise typing, I will try to reproduce this with ES6 Promise under improvement tag.

**Comment by gautamsi** [comment]
looks like [you solved it long ago](https://github.com/prisma/prisma/issues/1550#issuecomment-358269092), was this still related to Promise lib?

**Comment by omatrot** [comment]
We went away from using Graphcool.
