### ISSUE TITLE
Credential options "strictSSL"

### ISSUE THREAD

**Issue by rrubio** [gautamsi/ews-javascript-api#233]
Hi Guys,

Is there a way to add options to credentials or other settings? i'd like to add "strictSSL=false" but not having any luck.

I keep on getting the following error message:

`SoapFaultDetails {
  message: 'unable to verify the first certificate',
  InnerException: null,
  faultCode: null,
  faultString: null,
  faultActor: null,
  responseCode: 127,
  errorCode: 0,
  exceptionType: null,
  lineNumber: 0,
  positionWithinLine: 0,
  errorDetails: DictionaryWithStringKey { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] },
  HttpStatusCode: 0 }`

Below is my code - I am planning to get user calendar events essentially:

`var ews  = require('ews-javascript-api'),
    ExchangeVersion = ews.ExchangeVersion;

const options = {
    strictSSL: false
};
    
var exch = new ews.ExchangeService(ExchangeVersion.Exchange2010_SP2);

exch.Credentials = new ews.ExchangeCredentials("user@myexchange.com", "mypassword");
process.env['NODE_TLS_REJECT_UNAUTHORIZED'] = '0';

//set ews endpoint url to use
exch.Url = new ews.Uri("https://myexchange.com/Ews/Exchange.asmx"); // you can also use exch.AutodiscoverUrl

exch.GetRoomLists('user@email')
.then(function (availabilityResponse) {
    //do what you want with user availability
    console.log('Response --> ', availabilityResponse);
}, function (errors) {
    //log errors or do something with errors
    console.log('Errors --> ', errors);
});`

Cheers, Rodrigo

**Comment by gautamsi** [comment]
I have had success with `NODE_TLS_REJECT_UNAUTHORIZED`. you may want to dig further if there is some other issue.

**Comment by julestruong** [comment]
@rrubio Any solution ?

**Comment by gautamsi** [comment]
have recently pushed update which has this undocumented feature, this will be documented when I release 0.9.3 but for now, you can use it this way, see 6618c29c08a5ad087abe9636c3128bef9837d4ae

```ts
import {....., ConfigurationApi, .......} from 'ews-javascript-api';
// use this before instantiating ExchangeService 
ConfigurationApi.SetXHROptions({rejectUnauthorized : false});
```

let me know if it helped.

**Comment by gautamsi** [comment]
see readme for 0.9.4
