### ISSUE TITLE
Problem setting Appointment.StartTimeZone

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#234]
Hello,
I am trying to set `StartTimeZone` for an Appointment:

```
item.Subject = 'Summary';
item.Start = new ews.DateTime(start);
item.End = new ews.DateTime(end);
item.StartTimeZone = ews.TimeZoneInfo.FindSystemTimeZoneById("Eastern Standard Time");
```

This generates an error:

> 'The element \'CalendarItem\' in namespace \'http://schemas.microsoft.com/exchange/services/2006/types\' has invalid child element \'TimeZoneDefinition\' in namespace \'http://schemas.microsoft.com/exchange/services/2006/types\'. List of possible elements expected: \'MimeContent, ItemId, ParentFolderId, ItemClass, ...' 

If I look at the raw request, it looks like:

```
<t:SetItemField>
	<t:FieldURI FieldURI="calendar:StartTimeZone"></t:FieldURI>
	<t:CalendarItem>
		<t:TimeZoneDefinition Name="(UTC-05:00) Eastern Time (US &amp; Canada)" Id="Eastern Standard Time"></t:TimeZoneDefinition>
	</t:CalendarItem>
</t:SetItemField>
```

where, according to [the doc](https://msdn.microsoft.com/en-us/library/office/dn789030(v=exchg.150).aspx), it should be more like:

```
<t:SetItemField>
    <t:FieldURI FieldURI="calendar:StartTimeZone" />
        <t:CalendarItem>
               <t:StartTimeZone Id="Central Standard Time" />
         </t:CalendarItem>
</t:SetItemField>
```
Can this be the problem, or I am missing something?

**Comment by gautamsi** [comment]
what is the version you are using? latest?

**Comment by marcoancona** [comment]
Latest release, 0.9.2
I hadn’t time to look into it, but I can try to figure out the problem more specifically if it helps.

Il giorno 10 feb 2018, alle ore 19:24, Gautam Singh <notifications@github.com<mailto:notifications@github.com>> ha scritto:


what is the version you are using? latest?

**Comment by eugrdn** [comment]
I'm sorry for offtop, but with Appointments response in Organizer's Address property I receive something like 'O=EXCHANGELABS/OU=EXCHANGE ADMINISTRATIVE GROUP...'. I know that it is probably a Mailbox, but with the 'EX' routingType instead of 'SMTP' that is known as default. Is there any ways to proceed it to common 'SMTP' type?

**Comment by tobiasviehweger** [comment]
This is fixed by https://github.com/gautamsi/ews-javascript-api/pull/219, could you consider merging this?

**Comment by gautamsi** [comment]
merged

**Comment by gautamsi** [comment]
this one is redone in upcoming 0.9.5
