### ISSUE TITLE
Unable to reduce time span in TimeWindow

### ISSUE THREAD

**Issue by Ramprakashd1** [gautamsi/ews-javascript-api#235]
We have timeWindow in ews Service. Now we have 2 days of the time span. I want to reduce the time to half-an-hour. I have tried for it. It is showing errors. So is it possible to reduce the time span in timeWindow?
->var timeWindow = new ews.TimeWindow(new ews.DateTime('2016-12-12 12:00:00'),new ews.DateTime('2016-12-12 12:00:00').AddMinutes(30));
    This is the error showing:
->`SoapFaultDetails {
  message: '',
  stack: [Getter/Setter],
  InnerException: null,
  faultCode: 'a:ErrorInvalidTimeInterval',
  faultString:
   { 'xml:lang': 'en-US',
     faultstring: 'The time duration specified for
FreeBusyViewOptions.TimeWindow is invalid.' },
  faultActor: null,
  responseCode: 127,
  errorCode: 127,
  exceptionType: null,
  lineNumber: 0,
  positionWithinLine: 0,
  errorDetails: DictionaryWithStringKey { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] },
  HttpStatusCode: 500 } 'err'`

**Comment by gautamsi** [comment]
EWS Limitation on server side [MSDN](https://msdn.microsoft.com/en-us/library/ee356454(v=exchg.80).aspx) 

The GetUserAvailability(IEnumerable<AttendeeInfo>, TimeWindow, AvailabilityData, AvailabilityOptions) method supports only time periods that are a minimum of 24 hours long and that begin and end at 12:00a.m. To restrict the results of the method to a shorter time period, you must filter the results on the client.

**Comment by Ramprakashd1** [comment]
@gautamsi thanks for response. The time span is working for at least of 10 hrs. Thats okay! I want to compare the times. For example when I get the response,
`        
for(let i=0;i<availabilityResponse.attendeesAvailability.responses[0].calendarEvents.length;i++){
                if(availabilityResponse.attendeesAvailability.responses[0].calendarEvents[i].startTime.originalDateInput==timeWindow.StartTime.originalDateInput){
  //do something here....
        }
}`            
 I want to compare the responses with the time, I am getting false even the response is same. Can you please help on this?

**Comment by gautamsi** [comment]
they may have changed the window silently but my not be supporting it officially. you do not want to use originalDateInput? if you are trying to compare time , use TotalMilliSeconds instance property.

**Comment by Ramprakashd1** [comment]
Okay @gautamsi, I have the following responses for server. How can I convert into ms,
`availabilityResponse.attendeesAvailability.responses[0].calendarEvents[i].startTime.originalDateInput`
Response: "2018-02-14T16:30:00.000Z"
timeWindow.StartTime.originalDateInput
Response: "2018-02-14T17:30:00.000Z"
How can I change this into MilliSeconds so that we can compare it!

**Comment by gautamsi** [comment]
what do you get for `availabilityResponse.attendeesAvailability.responses[0].calendarEvents[i].startTime. TotalMilliSeconds`?

**Comment by Ramprakashd1** [comment]
Wonderful, got the response! It is working for some better results it seems. Thanks a lot @gautamsi
