### ISSUE TITLE
Streaming Notications

### ISSUE THREAD

**Issue by ray73864** [gautamsi/ews-javascript-api#24]
Is it possible to have streaming notifications? would like to be able to subscribe to new mail notifications.

**Comment by gautamsi** [comment]
Let me look into it.

**Comment by demarius** [comment]
I could definitely use this as well.

**Comment by gautamsi** [comment]
I have done basic research and it looks promising. I will work on it over next week time.

**Comment by gautamsi** [comment]
v0.2.7 pushed. See example below. (TypeScript)

```ts
import {EwsLogging, FolderId, ExchangeService, StreamingSubscriptionConnection, WellKnownFolderName, StreamingSubscription, ExchangeVersion, Uri, ExchangeCredentials, EventType} from "ews-javascript-api";

import credentials = require("./credentials");

var service = new ExchangeService(ExchangeVersion.Exchange2010_SP1);
service.Credentials = new ExchangeCredentials(credentials.userName, credentials.password);
service.Url = new Uri("https://outlook.office365.com/Ews/Exchange.asmx");

service.SubscribeToStreamingNotifications(
    [new FolderId(WellKnownFolderName.Inbox)],
    EventType.NewMail,
    EventType.Created,
    EventType.Deleted,
    EventType.Modified,
    EventType.Moved,
    EventType.Copied,
    EventType.FreeBusyChanged).then((streamingSubscription) => {
        console.log(streamingSubscription);
        // Create a streaming connection to the service object, over which events are returned to the client.
        // Keep the streaming connection open for 30 minutes.
        let connection: StreamingSubscriptionConnection = new StreamingSubscriptionConnection(service, 3);
        connection.AddSubscription(streamingSubscription);
        connection.OnNotificationEvent.push((o, a) => {
            console.log("notification received") //this gives you each notification.
            EwsLogging.Log(a, true, true);
        });
        connection.Open();

    }, (err) => {
        debugger;
        console.log(err);
    });
```

**Comment by gautamsi** [comment]
closing this to complete milestone, add any bugs discovered.

**Comment by picazi** [comment]
Hi,
I tested the code and it works really nice! Thanks!
But I read that the connection can only be opened 30 minutes max. Is it possible to reopen the same connection after a timeout?
Can I use a handler (and how?) (OnDisconnect) to wait till the disconnect event occurs? 

Thank you very much.

**Comment by gautamsi** [comment]
you can use 
```js
StreamingSubscriptionConnection.OnDisconnect.push(function(streamingSubscriptionConnectionInstance,subscriptionErrorEventArgsInstance){
   //do what you want when this is disconnected.  keep in mind that you have to keep track if you have initiated disconnect with StreamingSubscriptionConnection.Close() or it was disconnected with some exception. 
})
```

`streamingSubscriptionConnectionInstance` is instance of [StreamingSubscriptionConnection](https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Notifications/StreamingSubscriptionConnection.ts)
// SubscriptionErrorEventArgs is instance of [SubscriptionErrorEventArgs](https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Notifications/SubscriptionErrorEventArgs.ts) 
>Note: `SubscriptionErrorEventArgs.Subscription` property is always null per the OfficeDev\ews\managed-api snapshot I used when port code.

**Comment by picazi** [comment]
Mh I am sorry but I have problems with the SubscriptionErrorEventArgs instance. The method is not responding on disconnect... Maybe is it possible that you can extend your code from the top with the OnDisconnect method? 

I saw that the pull and streaming notifications are available. Are push notifications working? I am asking because I want to get notified if I get a new Mail. But the streaming connection has to be connected for the whole day. Is this recommended? Thank you very much for your API!!

**Comment by gautamsi** [comment]
I will look into the ondisconnect call. Push does work but it requires you to create external application which serves as receiver on internet.

**Comment by picazi** [comment]
Hey,
can you tell me how I can get the subscriptionErrorEventArgsInstance?

connection.OnDisconnect.push((connection, ???) => {
      console.log("disconnect");
      connection.Open();
 });

**Comment by gautamsi** [comment]
```ts
connection.OnDisconnect.push((connection, subscriptionErrorEventArgsInstance) => {
 console.log("disconnect");
 //access subscriptionErrorEventArgsInstance
 connection.Open();
 });
```

**Comment by picazi** [comment]
I am very sorry to bother you again, but I don't see any message when it's diconnecting. 
If I am activating the logging I can see the disconnect response...

Here is my function:
`
...
var exchange = new ews.ExchangeService(GetExchangeVersion());
exchange.Credentials = new ews.ExchangeCredentials(settings.username, settings.password);
exchange.Url = new ews.Uri(settings.serverAddress + '/ews/Exchange.asmx');
...
SetNotifications: function() {
         console.log('starting subscription... ' + new Date().toLocaleTimeString());

         exchange.SubscribeToStreamingNotifications(
                 [mod_exchange.inboxFolder, mod_exchange.calendarFolder],
                 ews.EventType.NewMail,
                 ews.EventType.Created,
                 ews.EventType.Deleted,
                 ews.EventType.Modified,
                 ews.EventType.Moved,
                 ews.EventType.Copied,
                 ews.EventType.FreeBusyChanged)
             .then((streamingSubscription) => {
                 let connection = new ews.StreamingSubscriptionConnection(exchange, 1);

                 connection.AddSubscription(streamingSubscription);
                 connection.OnNotificationEvent.push((o, a) => {
                     console.log("notification received: " + o + a)
                 });
                 connection.OnDisconnect.push((connection, subscriptionErrorEventArgsInstance) => {
                     console.log("disconnected...");
                     //access subscriptionErrorEventArgsInstance
                     //connection.Open();
                 });

                 connection.Open();
             }, (err) => {
                 debugger;
                 console.log("ERROR: " + err);
             });
     },
`

**Comment by gautamsi** [comment]
tracking in bug #91.

you can fix it temp by replacing code given in #91

**Comment by hgezim** [comment]
@gautamsi, will the following not work if there's an exception?

```js
connection.OnDisconnect.push((connection, subscriptionErrorEventArgsInstance) => {
 console.log("disconnect");
 //access subscriptionErrorEventArgsInstance
 connection.Open();
 });
```

Do we have to call `SubscribeToStreamingNotifications()` again or `AddSubscription()`?

**Comment by gautamsi** [comment]
you may be able to do that unless the network has any issue.
