### ISSUE TITLE
Unhandled rejection calling folder.Bind()

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#242]
It looks like `folder.Bind` does not resolve the promise in case the requests return 200 but the content fails parsing:

> Unhandled rejection {"message":"The request failed. undefined","stack":null,"InnerException":{}}
>     at GetFolderRequest.SimpleServiceRequestBase.ReadResponsePrivate (/home/anconam/projects/ElectronCal/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:120:19)
>     at /home/anconam/projects/ElectronCal/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:59:49
>     at tryCatcher (/home/anconam/projects/ElectronCal/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/home/anconam/projects/ElectronCal/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/home/anconam/projects/ElectronCal/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/home/anconam/projects/ElectronCal/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/home/anconam/projects/ElectronCal/node_modules/bluebird/js/release/promise.js:693:18)
>     at Async._drainQueue (/home/anconam/projects/ElectronCal/node_modules/bluebird/js/release/async.js:133:16)
>     at Async._drainQueues (/home/anconam/projects/ElectronCal/node_modules/bluebird/js/release/async.js:143:10)
>     at Immediate.Async.drainQueues (/home/anconam/projects/ElectronCal/node_modules/bluebird/js/release/async.js:17:14)
>     at runCallback (timers.js:781:20)
>     at tryOnImmediate (timers.js:743:5)
>     at processImmediate [as _immediateCallback] (timers.js:714:5)

Is it not clear to me how to catch a `ServiceRequestException` at application level. Missing exception handling in [SimpleServiceRequestBase.ts, line 49](https://github.com/gautamsi/ews-javascript-api/blob/2698a9849a7944521fffd8b80cbe077ee41cc861/src/js/Core/Requests/SimpleServiceRequestBase.ts#L49) ?

**Comment by y25zhao** [comment]
Are we planning to resolve this issue? I got similar one for BindItem. It is currently blocking us. Thanks

**Comment by gautamsi** [comment]
let me work on this
