### ISSUE TITLE
Wrong time when getting time from an appointment

### ISSUE THREAD

**Issue by piavgh** [gautamsi/ews-javascript-api#243]
Hi @gautamsi ,

I have 2 meetings on office365:

![screenshot_1](https://user-images.githubusercontent.com/4060207/38076958-766b610c-3361-11e8-9909-6da547b597b6.png)

I set the timezone on office365 with UTC+2.

When I tried to get the appointments, I printed some date format from the result

![screenshot_2](https://user-images.githubusercontent.com/4060207/38077042-bd144416-3361-11e8-9459-f2d5b89f04a8.png)

```
console.log(appointment.Start.toString());
console.log(appointment.Start.ToISOString());
console.log(appointment.Start.getMomentDate());
```

And this is the result for 2 appointments, respectively: 

![screenshot_3](https://user-images.githubusercontent.com/4060207/38077090-e9c28054-3361-11e8-8cba-0b6df9bd7ab2.png)

As you can see, although the time of my appointments on office365 are:

> 2:30PM 03/30 UTC+2
> 9:30AM 03/31 UTC+2

All 3 printed values from code are incorrect, even if I converted the time on office365 to UTC or my real local time (UTC+7), they are not correct values.

Can you please check it? I think the moment-timezone is somehow incorrect.

Thank you.

**Comment by piavgh** [comment]
After some time for investigation, I see that this problem happens for timezone UTC+2 and UTC+3.
So I think it's because of daylight saving time.

I will close this issue for now.

**Comment by gautamsi** [comment]
moment should take care of daylight saving, I do not remember adding timezone data packs to moment. not sure it loads them by default, you may want to check this.
