### ISSUE TITLE
Appointment.Save() does not return any reference

### ISSUE THREAD

**Issue by saelfaer** [gautamsi/ews-javascript-api#244]
the appointment's Save method returns a promise,
that promise gets resolved and the appointment was created.

however it seems like it doesn't return any reference to the newly created Appointment. it has no arguments with which I can reference it.

In C# you can query for the appointment's Id property on the saved instance.
I'm thinking like, the appointment itself or it's Id or something like that should be resolve parameters for the promise.

I can of course go query the Calendar for events during that TimeWindow but it would be nice if the promise returns at least a reference to the item.

**Comment by gautamsi** [comment]
when I look at Appointment.cs code, Save method returns nothing (void), where do you get access to returned reference. 
`Appointment.Save` also does change the original appointment, you should hold on to the reference of Appointment instance to loot them later (after the `Save` Promise).
