### ISSUE TITLE
Body.Text return xml

### ISSUE THREAD

**Issue by AlexeyShalik** [gautamsi/ews-javascript-api#247]
When I do this code ->

        await appointment.Load(new ews.PropertySet(ews.BasePropertySet.FirstClassProperties));
        let event = {
          subject: appointment.Subject,
          members: []
        };
        appointment.RequiredAttendees.GetEnumerator().forEach((a) => {
          event.members.push(a.Name);
        });
        console.log(appointment.Body.Text);

I get xml, but I want to get text

**Comment by gautamsi** [comment]
https://msdn.microsoft.com/en-us/library/microsoft.exchange.webservices.data.emailmessage_members(v=exchg.80).aspx


Name | Description
-- | --
Body | Gets or sets the body of this item. (inherited from Item)
TextBody | Gets the text body of the item. The TextBody property is applicable for clients that target Exchange Online and versions of Exchange starting with Exchange Server 2013. (inherited from Item)
NormalizedBody | Gets the message body of an item that has been converted to a normalized value. The NormalizedBody property is applicable for clients that target Exchange Online and versions of Exchange starting with Exchange Server 2013. (inherited from Item)
UniqueBody | Gets the body part that is unique to the conversation that this item is part of. (inherited from Item)

**Comment by AlexeyShalik** [comment]
TextBody, NormalizeBody, UniqueBody don't work.

**Comment by AlexeyShalik** [comment]
I use
const exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010_SP2);
  exch.Credentials = new ews.WebCredentials(login, pass);
  exch.Url = new ews.Uri(config.url_365);

  const exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010_SP2);
  exch.Credentials = new ews.WebCredentials(login, pass);
  exch.Url = new ews.Uri(config.url);

How I can get value in Exchange Server 2010?

**Comment by gautamsi** [comment]
if your server is Exchange 2010, you may want to use something like https://github.com/werk85/node-html-to-text

**Comment by AlexeyShalik** [comment]
Thanks you)

**Comment by gautamsi** [comment]
you may want to help others with what you have done finally (if you did use some utility)

**Comment by german-st** [comment]
> TextBody, NormalizeBody, UniqueBody don't work.

Hello.

@gautamsi 

 UniqueBody still doesn't work ( thank you

**Comment by gautamsi** [comment]
have you checked verbose response and if that response contain XML or not? Another way is to find me an example with c# code and export that email in .eml with help of outlook client. That way I can fix the problem.
