### ISSUE TITLE
GetUserAvailability returns Exception in some cases

### ISSUE THREAD

**Issue by lorenc-tomasz** [gautamsi/ews-javascript-api#249]
Hi,
when I invoke 
GetUserAvailability([new AttendeeInfo("room-1@company.com"), new AttendeeInfo("room-2@company.com")],new TimeWindow(DateTime.Now, DateTime.Now.Add(1, "h")),AvailabilityData.FreeBusy) it returns Exception.

But

GetUserAvailability([new AttendeeInfo("room-1@company.com"), new AttendeeInfo("room-2@company.com")],new TimeWindow(DateTime.Now, DateTime.Now.Add(10, "h")),AvailabilityData.FreeBusy) works OK. 

Edited:

It works when TimeWindow(DateTime.Now, DateTime.Now.Add(4, "h")) is min. 4 hours long.

**Comment by gautamsi** [comment]
when you add 4h, it should be changing date, that matters. 

https://msdn.microsoft.com/en-us/library/ee356454(v=exchg.80).aspx
>The GetUserAvailability(IEnumerable<AttendeeInfo>, TimeWindow, AvailabilityData, AvailabilityOptions) method supports only time periods that are a minimum of 24 hours long and that begin and end at 12:00a.m. To restrict the results of the method to a shorter time period, you must filter the results on the client.

**Comment by lorenc-tomasz** [comment]
Is there, maybe, better way to check if the room is available for reservation?

**Comment by gautamsi** [comment]
you can still use this with larger time window and filter result before display.

in exchange you can create room list and then add those rooms based on room list to the GetUserAvailability call, then filter the result based on need. like if show which room is available in a time slot.
