### ISSUE TITLE
ContactSchema.HasPicture: [Exception: null]

### ISSUE THREAD

**Issue by lorenc-tomasz** [gautamsi/ews-javascript-api#254]
Hi,

I tried to get contact details from GAL using ResolveName("name surname", ResolveNameSearchLocation.DirectoryOnly, true). Basically it works but many properties returns [Exception: null]. Any idea why?

**Comment by gautamsi** [comment]
have you tried this? https://msdn.microsoft.com/en-us/library/hh532803(v=exchg.80).aspx

**Comment by lorenc-tomasz** [comment]
Thank you. I wrongly assumed that all properties are returned by default.
