### ISSUE TITLE
ServiceResponseCollection getEnumerator not implemented ?

### ISSUE THREAD

**Issue by julestruong** [gautamsi/ews-javascript-api#256]
Hello @gautamsi 

I'm trying to get my resources in my appointments. It seems that this is so hard !
I figured out that i couldnt not add `propSet.Add(AppointmentSchema.Resources);` in my calendarView and that i should use 

```
const serviceResponseCollection = await exch.LoadPropertiesForItems(
        appointments.Items,
        propSet,
      );
```

The problem is that the method serviceResponseCollection.GetEnumerator() is not implemented in your lib ?

Is there any solution to this ?

**Comment by gautamsi** [comment]
try `Responses`  property instead

**Comment by julestruong** [comment]
Perfect !
