### ISSUE TITLE
how to get Organizer

### ISSUE THREAD

**Issue by rodrigoWollies** [gautamsi/ews-javascript-api#257]
Hi Guys,

I'm currently using 'exch.GetUserAvailability()' to get meeting times (works perfectly) but it does not contain the Organizer. Any tips on/how to get it?

See example below:

```
exch.GetUserAvailability(attendees, tmw, ews.AvailabilityData.FreeBusyAndSuggestions, myOptions)
.then((availabilityResponse) => {           
  resolve(JSON.stringify(availabilityResponse.AttendeesAvailability.Responses[0].calendarEvents));
}, (e) => {
  reject(e);
});  
```     

Cheers, Rodrigo

**Comment by gautamsi** [comment]
when you add Attendee to array, did you choose to add organizer as "AttendeeType.Organizer"?

**Comment by gautamsi** [comment]
re-open if needed.
