### ISSUE TITLE
same approach does not work with outlook IOS. 

### ISSUE THREAD

**Issue by thePaddyVP** [gautamsi/ews-javascript-api#258]
I am trying to hardcode ewsUrl is it is not supported in outlook ios and passing the same itemid and accesstoken to get the item. But it fails with ID Malformed error and when i try to replace the characters "_" to "+" to make it valid it throws access denied exception. Please let me know if there is a way to overcome this issue

**Comment by thePaddyVP** [comment]
Is there any way to fix this issue?

**Comment by gautamsi** [comment]
still having this issue?
