### ISSUE TITLE
Error while cancelling the Meeting thru the unique id generated while booking

### ISSUE THREAD

**Issue by jafarsadiqali** [gautamsi/ews-javascript-api#260]
Hi Gautamsi,

I have booked the meeting and when I try to cancel the meeting , I am getting the below mentioned error.

{"**message":"Id is malformed.","stack":"Exception: Id is malformed.\n**    at GetItemResponse.ServiceResponse.InternalThrowIfNecessary (C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\ews-javascript-api\\js\\Core\\Responses\\ServiceResponse.js:111:19)\n    at GetItemResponse.ServiceResponse.ThrowIfNecessary (C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\ews-javascript-api\\js\\Core\\Responses\\ServiceResponse.js:221:14)\n    at C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\ews-javascript-api\\js\\Core\\Requests\\MultiResponseServiceRequest.js:50:59\n    at tryCatcher (C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\bluebird\\js\\release\\util.js:16:23)\n    at Promise._settlePromiseFromHandler (C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\bluebird\\js\\release\\promise.js:512:31)\n    at Promise._settlePromise (C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\bluebird\\js\\release\\promise.js:569:18)\n    at Promise._settlePromise0 (C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\bluebird\\js\\release\\promise.js:614:10)\n    at Promise._settlePromises (C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\bluebird\\js\\release\\promise.js:693:18)\n    at Async._drainQueue (C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\bluebird\\js\\release\\async.js:133:16)\n    at Async._drainQueues (C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\bluebird\\js\\release\\async.js:143:10)\n    at Immediate.Async.drainQueues (C:\\Jafar\\NVINCY\\BrightSign_Requirement\\SingleRoomBooking-Desk\\node_modules\\bluebird\\js\\release\\async.js:17:14)\n    at runCallback (timers.js:800:20)\n    at tryOnImmediate (timers.js:762:5)\n    at processImmediate [as _immediateCallback] (timers.js:733:5)","InnerException":null,"response":{"errorDetails":{"keys":[],"keysToObjs":{},"objects":{}},"errorProperties":[],"propertySet":{"basePropertySet":1,"additionalProperties":[],"requestedBodyType":null,"requestedUniqueBodyType":null,"requestedNormalizedBodyType":null,"filterHtml":null,"convertHtmlCodePageToUTF8":null,"inlineImageUrlTemplate":null,"blockExternalImages":null,"addTargetToLinks":null,"isReadOnly":true,"maximumBodySize":null},"result":2,"errorCode":161,"errorMessage":"Id is malformed."}}

SampleId: "AAMkADEyMmY0MGIxLTE1MTYtNDQ0Mi1iN2VhLTAzZjc2MjI3NjUzOQBGAAAAAABukiHDbJ1fS41J5wDk2nKMBwCq662iVas0SqFPIFH4KBw3AAAAAAENAACq662iVas0SqFPIFH4KBw3AAC/6u+JAAA="

I have observed whenever the unique meeting id does have plus (+) symbol, It give the error mentioned above.

Regards
Jafar Sadiq.

**Comment by gautamsi** [comment]
there may be some factor not discovered yet, can you check if you are able to bind to this item like `Appointment.Bind(service, new ItemId("AAMkA="));` replace the item id.

**Comment by jafarsadiqali** [comment]
I am already using in the same way. Please find the below code.

app.get('/cancelMeeting', function(req, res) {
    var meetingId = req.query.meetingId;

    var id = new ews.ItemId(meetingId);

    ews.Appointment.Bind(exch, id).done(function(rawAppointment) {
        rawAppointment.CancelMeeting("Meeting cancelled by service").done(function(result) {
            console.log("success");
            res.send("success");
        }, function(err) {
            console.log(err);
            res.send("errors");
        });
    }, function(err) {
        res.send(err);
    });


What I have observed is when the unique meeting id has "+" symbol, then I am getting this error.
For remaining meetingid, i am able to delete it.



Regards
Jafar Sadiq.

**Comment by gautamsi** [comment]
are you able to replicate this in c# version of lib? just bind, do not delete
