### ISSUE TITLE
Cannot find FetchOptions, FetchStream, fetchUrl

### ISSUE THREAD

**Issue by SuperTroye** [gautamsi/ews-javascript-api#261]
Trying to include ews-javascript-api in my Angular 6 project and run build and getting the following errors

ERROR in node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts(60,40): error TS2304: Cannot find name 'FetchOptions'.
node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts(1443,32): error TS2304: Cannot find name 'FetchStream'.
node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts(1444,29): error TS2304: Cannot find name 'fetchUrl'.
node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts(1445,28): error TS2304: Cannot find name 'FetchOptions'.
node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts(1446,19): error TS2304: Cannot find name 'FetchOptions'.
node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts(1450,32): error TS2304: Cannot find name 'FetchOptions'.

Is there a Typings file missing, or where is the Fetch api referenced?

**Comment by gautamsi** [comment]
you may want to use `skipLibCheck` in typescript compiler options, will fix in later release
