### ISSUE TITLE
resperr.getAllResponseHeaders is not a function at ExchangeWebService.js:38963

### ISSUE THREAD

**Issue by elrapha** [gautamsi/ews-javascript-api#262]
I am trying to use [https://github.com/gautamsi/ews-js-api-browser](https://github.com/gautamsi/ews-js-api-browser) with the following example from (https://gist.github.com/gautamsi/ba0561da1b4a2b29478943ba5f002328)

`EwsJS.EwsLogging.DebugLogEnabled = false;

            var service = new EwsJS.ExchangeService(EwsJS.ExchangeVersion.Exchange2016);
            service.Credentials = new EwsJS.WebCredentials(
                "username","password"
            );
            service.Url = new EwsJS.Uri("https://outlook.office365.com/Ews/Exchange.asmx");

            var view = new EwsJS.CalendarView(EwsJS.DateTime.Now.Add(-5, "week"), EwsJS.DateTime.Now); // appointments in last one week.
            service.FindAppointments(EwsJS.WellKnownFolderName.Calendar, view).then((response) => {
                let appointments = response.Items;
                let appointment = appointments[0];
                console.log("Subject: " + appointment.Subject);
                console.log("Start Time: " + appointment.Start);
                console.log("End Time: " + appointment.End);
                console.log("Recipients: ");
                appointment.RequiredAttendees.Items.forEach((a) => {
                    console.log(a.Address);
                });
                console.log("unique id: " + appointment.Id.UniqueId, true, true);

            }, function (error) {
                console.log(error)
            })`

but i get the following error:
resperr.getAllResponseHeaders is not a function at ExchangeWebService.js:38963

**Comment by gautamsi** [comment]
where are you using it? it is supposed to be used inside browser where CORS is disabled.

**Comment by elrapha** [comment]
@gautamsi  hmmm....I am using it in my outlook add-in script.. What am i doing wrong.  I actually want to get meeting rooms but  I  just trying out the code above first. My example above is quite similar to the example given here https://github.com/gautamsi/ews-js-api-browser. This is the full example

`(function () {
    'use strict';
    Office.initialize = function (reason) {
        EwsJS.ConfigureForOutlook(); // only needed in outlook add-ins, not needed for other browser based process

        $(document).ready(function () {

            EwsJS.EwsLogging.DebugLogEnabled = false;

            var service = new EwsJS.ExchangeService(EwsJS.ExchangeVersion.Exchange2010);
            service.Credentials = new EwsJS.WebCredentials(
                "user","pass"
            );
            service.Url = new EwsJS.Uri("https://outlook.office365.com/Ews/Exchange.asmx");

            var view = new EwsJS.CalendarView(EwsJS.DateTime.Now.Add(-5, "week"), EwsJS.DateTime.Now); // appointments in last one week.
            service.FindAppointments(EwsJS.WellKnownFolderName.Calendar, view)
                .then((response) => {
                let appointments = response.Items;
                let appointment = appointments[0];
                console.log("Subject: " + appointment.Subject);
                console.log("Start Time: " + appointment.Start);
                console.log("End Time: " + appointment.End);
                console.log("Recipients: ");
                appointment.RequiredAttendees.Items.forEach((a) => {
                    console.log(a.Address);
                });
                console.log("unique id: " + appointment.Id.UniqueId, true, true);

            }, function (error) {
                console.log("Error",error)
            });
        });
    };
})();`

**Comment by gautamsi** [comment]
glad that it worked.
