### ISSUE TITLE
Loading Custom Property of Items via SyncFolderItems

### ISSUE THREAD

**Issue by moa101** [gautamsi/ews-javascript-api#267]
How do I add a custom property to the PropertySet? This custom property is set when the Meeting Invite is created via an Outlook AddOn. This field is used to tag a meeting invite before it is sent.

I am working on a tool to sync all calendar invites for a user and parse this custom field that is set during the meeting invite creation.

I am using the following approach to call the sync function. As you can see below, I am currently loading all the `BasePropertySet.FirstClassProperties`. I am not sure how to go about defining a custom field and adding that field to the array of properties that will be loaded when changeItems Items are returned.

```js
const folderId = new FolderId(WellKnownFolderName.Calendar)
const propertySet = new PropertySet(BasePropertySet.FirstClassProperties)
const ignoredItemIds = []
const maxChangesReturned = 512
const numberOfDays = 0
const syncScope = SyncFolderItemsScope.NormalAndAssociatedItems
const syncState = null

await service.SyncFolderItems(syncFolderId, propertySet, ignoredItemIds, maxChangesReturned, numberOfDays, syncScope, syncState)
```

Fix:
```js
const PS_PUBLIC_STRINGS = new Guid('00020329-0000-0000-C000-000000000046')
const ExtendedPropertyProjectID = new ExtendedPropertyDefinition(PS_PUBLIC_STRINGS, '<YourPropertyName>', MapiPropertyType.Integer);
const folderId = new FolderId(WellKnownFolderName.Calendar)
const propertySet = new PropertySet(BasePropertySet.FirstClassProperties, [ExtendedPropertyProjectID])
const ignoredItemIds = []
const maxChangesReturned = 512
const numberOfDays = 0
const syncScope = SyncFolderItemsScope.NormalAndAssociatedItems
const syncState = null

await service.SyncFolderItems(syncFolderId, propertySet, ignoredItemIds, maxChangesReturned, numberOfDays, syncScope, syncState)
```

**Comment by gautamsi** [comment]
have you checked #182 and/or #25 ? they have example on how to use ExtendedProperty.

more info on custom or extendedproperty https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/properties-and-extended-properties-in-ews-in-exchange

**Comment by moa101** [comment]
I am trying to use the examples to fetch the custom property I want - will post here how it goes.

In the meantime, just for context here is how we set the custom property:

`meeting.ItemProperties.Add("TagID", Microsoft.Office.Interop.Outlook.OlUserPropertyType.olInteger, false, false);`

See docs: https://msdn.microsoft.com/en-us/vba/outlook-vba/articles/itemproperties-add-method-outlook.

**Comment by moa101** [comment]
I am getting this error

```js
const ProjectIDProperty = new ExtendedPropertyDefinition("TagID", MapiPropertyType.Integer);
          console.log(ProjectIDProperty)
          const newAppointment = await appointment.Load(new PropertySet(BasePropertySet.FirstClassProperties, ProjectIDProperty))
          console.log(newAppointment)
```

```js
SoapFaultDetails {
  message: 'The request is invalid.',
  InnerException: null,
  faultCode: 'a:ErrorInvalidRequest',
  faultString: { 'xml:lang': 'en-US', faultstring: 'The request is invalid.' },
  faultActor: null,
  responseCode: 214,
  errorCode: 0,
  exceptionType: null,
  lineNumber: 0,
  positionWithinLine: 0,
  errorDetails: DictionaryWithStringKey { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] },
  HttpStatusCode: 500 }
Exception: The request is invalid.
    at Function.SoapFaultDetails.Parse (/Users/moa/Projects/journal/node_modules/ews-javascript-api/js/Misc/SoapFaultDetails.js:230:32)
    at GetItemRequestForLoad.ServiceRequestBase.ReadSoapFault (/Users/moa/Projects/journal/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:340:72)
    at GetItemRequestForLoad.ServiceRequestBase.ProcessWebException (/Users/moa/Projects/journal/node_modules/ews-javascript-api/js/Core/Requests/ServiceRequestBase.js:263:41)
    at /Users/moa/Projects/journal/node_modules/ews-javascript-api/js/Core/Requests/SimpleServiceRequestBase.js:70:41
    at tryCatcher (/Users/moa/Projects/journal/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/moa/Projects/journal/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/moa/Projects/journal/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/moa/Projects/journal/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/moa/Projects/journal/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/moa/Projects/journal/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/moa/Projects/journal/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/moa/Projects/journal/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

**Comment by gautamsi** [comment]
you may not be using correct constructor, check [this](http://ews-javascript-api.github.io/api/classes/propertydefinitions_extendedpropertydefinition.extendedpropertydefinition.html#constructor) 

only overload with two parameter is with number and type, yours is string and type.

**Comment by gautamsi** [comment]
more example - https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/dd633697(v%3dexchg.80)

**Comment by moa101** [comment]
I was using https://github.com/gautamsi/ews-javascript-api/blob/672e89373776379bc804307b7ffb4932ed80bc16/src/js/PropertyDefinitions/ExtendedPropertyDefinition.ts#L102

**Comment by moa101** [comment]
Is there a way to fetch all ExtendedProperties so that I can check what the DefaultExtendedPropertySet or the Guid is for the custom property I am trying to find. My problem is that I dont know how to find the Guid of the custom property.

**Comment by gautamsi** [comment]
use https://github.com/stephenegriffin/mfcmapi tool to get details from within mailbox.

**Comment by gautamsi** [comment]
haven't thought about donations right now, but you can help differently. ping me on gitter or send message in LinkedIn (link on profile page)

**Comment by moa101** [comment]
My GUID as you can see from the image is "00020329-0000-0000-C000-000000000046"

It doesnt match the regex in the Guid class here https://github.com/gautamsi/ews-javascript-api/blob/310081cc3921fdc72a0f22e19d64555348a6eb7a/src/js/Guid.ts#L13

![image 4](https://user-images.githubusercontent.com/19394489/43483617-051b5266-94c1-11e8-92f3-8a9e6f193f50.png)

**Comment by gautamsi** [comment]
you can still try search with lowercase of this guid, it should be case agnostic on Exchange side.

**Comment by moa101** [comment]
I get this error when i do this - i dont think this is because of case sensitivity

```const guid = new Guid('00020329-0000-0000-C000-000000000046')```

```TypeError: Guid.ctor - invalid input
    at new Guid (/app/node_modules/ews-javascript-api/js/Guid.js:20:23)
    at /app/server/exchange/ExchangeAPI.js:111:26
    at Generator.next (<anonymous>)
    at step (/app/server/exchange/ExchangeAPI.js:19:191)
    at /app/server/exchange/ExchangeAPI.js:19:361
    at <anonymous>
TypeError: Guid.ctor - invalid input
    at new Guid (/app/node_modules/ews-javascript-api/js/Guid.js:20:23)
    at /app/server/exchange/ExchangeAPI.js:111:26
    at Generator.next (<anonymous>)
    at step (/app/server/exchange/ExchangeAPI.js:19:191)
    at /app/server/exchange/ExchangeAPI.js:19:361
    at <anonymous>```

**Comment by gautamsi** [comment]
can you change the regex for Guid class with `/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i` and try again?

**Comment by gautamsi** [comment]
what is 882? is it numeriic tag for this property? you may be able to use it like `new ExtendedPropertyDefinition(882, MapiPropertyType.Integer);`

**Comment by moa101** [comment]
It worked!

**Comment by gautamsi** [comment]
Guid or 882?

**Comment by moa101** [comment]
Do you mean like ``` '00020329-0000-0000-C000-000000000046ProjectID'

**Comment by moa101** [comment]
@gautamsi Thank you so much! It worked! I will post a clean version of the code Iam using here
