### ISSUE TITLE
Respect of proxy settings out-of-the-box

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#270]
It would be nice is ews-javascript-api could pick the proxy configuration from `HTTP_PROXY / HTTPS_PROXY` env variables, similarly to google-api-nodejs-client: https://github.com/google/google-api-nodejs-client#using-a-proxy.
Other HTTP libraries like https://www.npmjs.com/package/request respect the proxy settings out-of-the-box, but it looks like `fetch` does not, unfortunately.

**Comment by gautamsi** [comment]
have you looked at ewsjs/xhr? I will consider adding proxy support using environment variable in next release of ewsjs/xhr

**Comment by marcoancona** [comment]
Oh, `ewsjs/xhr` uses the `request` library so, in theory, env variables should be supported out-of-the box. Is also ews-javascript-api based on `request`?

**Comment by gautamsi** [comment]
not yet, I am thinking moving to request in next major release.

**Comment by gautamsi** [comment]
XHR in ew-javascript-api is pluggable, so you can in theory bring your own xhr

**Comment by gautamsi** [comment]
suggestion is to use `@ewsjs/xhr` if you want to use proxy, either using explicit setting or via env variable.
