### ISSUE TITLE
Keep track of attachment downloading progress

### ISSUE THREAD

**Issue by y25zhao** [gautamsi/ews-javascript-api#273]
Hi

I am wondering if there is an easy way for us to keep track of attachment downloading progress by hooking up with standard XHR.onProgress callback:

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget/onprogress

Thanks

**Comment by gautamsi** [comment]
there is no `onProgress` event as of yet, you may copy the current xhr implementation (inbuilt or from ewsjs/xhr repo) and add your own hook easily.

**Comment by gautamsi** [comment]
no plan to add this.
