### ISSUE TITLE
Getting messages from folder UniqueID

### ISSUE THREAD

**Issue by gianlucainnocente** [gautamsi/ews-javascript-api#276]
Hi,
i have the folders list with theirs UniqueId and i need to use SyncFolderItems for each folder. How can i use it passing UniqueId instead of WellKnownFolderName?

I tried in this way but it doesn't work:
`exch.SyncFolderItems(new ews.FolderId(HERE_THE_UNIQUE_ID), ews.PropertySet.FirstClassProperties, null, 5 ews.SyncFolderItemsScope.NormalItems, syncState).then(function (response) {

});`

Thank you

**Comment by gautamsi** [comment]
are you able to use `Folder.Bind` using this unique Id?

**Comment by gautamsi** [comment]
do you still need help with this?

**Comment by craigmarvelley** [comment]
Hello,

I'm having the same issue and would be grateful if someone could point me in the right direction. I tried using `Folder.Bind` as you suggested @gautamsi but that doesn't appear valid either:

```
const folder = ews.Folder.Bind ews, "UNIQUE_ID");

Error: unknow parameter type. this should not be  reached
    at Function.Folder.Bind (/ews-javascript-api/js/Core/ServiceObjects/Folders/Folder.js:192:15)
```

[Microsoft's docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.exchange.webservices.data.folderid.-ctor?view=exchange-ews-api#Microsoft_Exchange_WebServices_Data_FolderId__ctor_System_String_) seem to suggest that the FolderId constructor should accept a string ID, but in this library the constructor that accepts a uniqueId has been commented out:

```
var FolderId = (function (_super) {
    __extends(FolderId, _super);
    //    constructor(uniqueId?: string, folderName?: WellKnownFolderName, mailbox?: Mailbox) {
    //        super(uniqueId);
    //
    //        this.mailbox = mailbox;
    //        this.folderName = folderName;
    //    }
```

and it's not an exact match with the one in Microsoft's docs anyway.

My use case is: I need to store the IDs of a set of folders (they won't all be well-known) and then sync the items inside each one. I could first find all the folders in Exchange and then filter them to get the FolderId objects, but that seems a bit expensive – I'd prefer to be more declarative if that's possible?

Would appreciate any advice! Thanks.

**Comment by gautamsi** [comment]
let me work on that code. 

can you test this instead while it may take time to publish?

instead of FolderId try passing `new ServiceId(<uniqueid>);`

**Comment by craigmarvelley** [comment]
Awesome, thanks. I tried using a `ServiceId`, and got this error:

```
Unhandled rejection Error: abstract method must implement.
    at ServiceId.GetXmlElementName (/ews-javascript-api/js/ComplexProperties/ServiceId.js:56:65)
```

**Comment by gautamsi** [comment]
ok, I will try to wrap this soon.

This should work, give it a try. 

```js
folderId = new FolderId();
folderId.UniqueId = <unique id>
```

**Comment by craigmarvelley** [comment]
Yep, that works perfectly. Thanks!
