### ISSUE TITLE
Example Retrieve inbox emails 

### ISSUE THREAD

**Issue by rezaffm** [gautamsi/ews-javascript-api#278]
I am sorry for the maybe quite stupid question but cd somebody please provide an example how to retrieve mails from the inbox folder (Exchange 2013 S1). Thank you!

**Comment by RezaFFM** [comment]
Some example code would be appreciated

**Comment by rousselle** [comment]
Please email muchbetterwaysoftware at gmail dot com. I may be able to help you.

**Comment by iXMTS** [comment]
i would also need that...

**Comment by gautamsi** [comment]
see this - https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-work-with-exchange-mailbox-items-by-using-ews-in-exchange
