### ISSUE TITLE
Problem accessing Office 365 shared calendars

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#279]
I am facing an interesting issue and I would like to know if you have an idea of what is causing it.
One of our users uses Office 365 for Business and would like to see other employees' calendars (which are all visible within the company as global setting).
The calendar can be accessed from Office 365 web portal, but if I try to access it using

```js
let propSet = new ews.PropertySet(
		ews.BasePropertySet.FirstClassProperties,
		ews.FolderSchema.Permissions
	);
// Try to access default calendar folder
const calendarFolderId = new ews.FolderId(
	ews.WellKnownFolderName.Calendar,
	new ews.Mailbox("delegate@company.com")
);
ews.Folder.Bind(exchange, calendarFolderId, propSet).then(
	folder => {...}
```
I get `Access is denied. Check credentials and try again., Can't look up the requested Entry ID.`
Interestingly, Apple Calendar on macOS, which is based on EWS, also fails to connect to these calendars:
<img width="536" alt="screen shot 2018-09-24 at 16 39 17" src="https://user-images.githubusercontent.com/2278117/45981323-da79c780-c054-11e8-8fc4-65b4044a6e05.png">

On the other hand, BusyCal seems to be able to connect. I am not sure this is a problem with the way one is supposed to access shared calendar, or a bug. Do you have any idea?

**Comment by gautamsi** [comment]
what is the default permission/accesslevel setting you used for all users?

**Comment by marcoancona** [comment]
I am close to see the pattern. It turns our that employee in the company have different sharing permissions (maybe they changed the default):
- for those that only share Free/Busy availability, I cannot Bind the folder (but this is expected, I think)
- some users seem to have "Subject/Location" sharing only, and these calendars can be viewed on the web portal but they cannot be accessed from Outlook for Mac (Microsoft mistery, I will ignore this case for now)
- for some users, it turns out that I can bind the calendar Folder (and afterward get the Items), but only if the initial binding uses
```js
let propSet = new ews.PropertySet(
	ews.BasePropertySet.IdOnly,
);
```
instead of
```js
let propSet = new ews.PropertySet(
	ews.BasePropertySet.FirstClassProperties,
	ews.FolderSchema.Permissions
);
```
Notice that keeping `ews.BasePropertySet.FirstClassProperties` only won't work either. 
If I make do with the Id only, I can then get the calendar items as expected!

I am not sure what kind of permissions leads to this behavior. Interestingly, in this case, Outlook for Mac cannot access the folder permission of the delegate user either (but correctly shows the events):

<img width="497" alt="screen shot 2018-09-25 at 10 53 56" src="https://user-images.githubusercontent.com/2278117/46003644-51dd4480-c0b1-11e8-9054-b809267bd1d9.png">

Now I wonder if I should handle this scenario, and what is the best way to do that. Should I catch the exception when trying to get permission and display name info from the folder, and try again with id only?

**Comment by gautamsi** [comment]
If this is permission issue you are left with retrying with ID Only, this way you can check more scenario and adapt to permission level of the mailbox. or you can just throw error similar to outlook.

**Comment by marcoancona** [comment]
I will do that then. Still, I don’t understand what permission setting give this access as using the Outlook interface one can only make a binary choice about folder visibility.

Il giorno 25 set 2018, alle ore 12:51, Gautam Singh <notifications@github.com<mailto:notifications@github.com>> ha scritto:


If this is permission issue you are left with retrying with ID Only, this way you can check more scenario and adapt to permission level of the mailbox. or you can just throw error similar to outlook.

**Comment by gautamsi** [comment]
re-open if still facing issues.

**Comment by Roendi61** [comment]
We have the same Problem. I found the problem. Not the solution.
The User has added to his Account an external Email Addresses. 
The Permission start with ExchangePublished....
When you delete this Permission for the Calendar, everything works fine again

**Comment by gautamsi** [comment]
that would be limitation of EWS in general and not this lib

**Comment by Roendi61** [comment]
I have no idea. We use ews for reading the calendar from all User. Only one User has this problem and we see the error message exactly like on your post.

Check the Mailbox Permission for this User with: 

get-MailboxFolderPermission -Identity s.test@test.com:\Calendar

When you see an Access Right for a ExchangePublished.. Account you find the Problem for the unsucsesfful EWS registration
