### ISSUE TITLE
Appointment does not appear on organizer's calendar

### ISSUE THREAD

**Issue by CailinPitt** [gautamsi/ews-javascript-api#280]
I'm having a weird issue with appointments, and I would appreciate some guidance. When I create and send an appointment, like so:
```JavaScript
let appointment = new ews.Appointment("<email>");
appointment.subject = "Untitled Meeting";
appointment.Start = ews.DateTime.Parse("<start>");
appointment.End = ews.DateTime.Parse("<end>");
appointment.Location = "<location>";
appointment.Body = new ews.MessageBody("<body>");
appointment.RequiredAttendees.Add(new ews.Attendee("<email>"));

appointment.Save(ews.SendInvitationsMode.SendToAllAndSaveCopy)
```

The appointment is sent to the required attendees, and the current user is set as the meeting organizer. However, the appointment does not show up on the organizer's calendar. The appointment invite shows up in the organizer's trash, but it cannot be accepted or altered and does not appear on the calendar. Any help or insight on this issue would be appreciated!

**Comment by gautamsi** [comment]
still facing this issue?

**Comment by CailinPitt** [comment]
@gautamsi Yes. I wasn't able to get past this issue and moved on to other projects, so I haven't looked at this since

**Comment by gautamsi** [comment]
I am not able to reproduce with version `0.9.4`. the invitation is sent fine, I can cancel the appointment as an organizer. the email goes into sent item and not in the trash. tested with office 365. 

I did have to fix few things in your example 

```js
let appointment = new ews.Appointment(service); // service instance of ExchangeService
appointment.subject = "Untitled Meeting";
appointment.Start = ews.DateTime.Parse("<start>"); // moment string
appointment.End = ews.DateTime.Parse("<end>"); // moment string
appointment.Location = "<location>";
appointment.Body = new ews.MessageBody("body"); // you can not use any special character or escape the content 
appointment.RequiredAttendees.Add(new ews.Attendee("<email>"));

await appointment.Save(ews.SendInvitationsMode.SendToAllAndSaveCopy); // can await
```

**Comment by gautamsi** [comment]
@jserra91 any error message or it simply does not send the invitation? 
exchange version?

**Comment by jserra91** [comment]
Ok, I´m solvented but it´s not easy haha
```
        // appoinment
        let appoinment = new ews.Appointment(exch);
        appoinment.Subject = "Alexa - Meeting in " + correctRoom.title;
        appoinment.Start = starttime;
        appoinment.End = finishtime;
        appoinment.Location = localitation;
        appoinment.Body = new ews.MessageBody("Meeting booked by Alexa Service");
        appoinment.RequiredAttendees.Add(new ews.Attendee("jserrago@xxxx.com"));
        appoinment.RequiredAttendees.Add(new ews.Attendee(emailRoom));
        await appoinment.Save(ews.SendInvitationsMode.SendToAllAndSaveCopy);
```

It's necessary include the Room Email to booking.

**Comment by jserra91** [comment]
Thank you @gautamsi
