### ISSUE TITLE
Failed to load resource: net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by prashantphatate3643** [gautamsi/ews-javascript-api#288]
We are using internal local exchange server ( Not the public O365 exchange. Using O365 accounts the error is not seen)

Error in calling service, error code:0
<img width="1382" alt="screen shot 2018-11-06 at 11 18 41 am" src="https://user-images.githubusercontent.com/40854749/48045506-98e14e00-e1b6-11e8-9d3b-95e9a13db79b.png">

**Comment by prashantphatate3643** [comment]
Hi gautam.
Thanks for the quick reponse. Yes we are using self signed certificate. Will try and post the output.

**Comment by prashantphatate3643** [comment]
Hi Gautam,
We are using ews-js-api-browser library. Does this library supports ConfigurationApi.SetXHROptions({rejectUnauthorized : false}); call??

**Comment by gautamsi** [comment]
oh, no, not for the Browser, you are relying on chrome's inbuilt handler then.

try to trust the certificate and the certificate chain, are you using self signed cert or a trusted cert? sometime the exchange may not have full chain visible at server side and it throws certificate error on chrome/browser.

**Comment by gautamsi** [comment]
any luck with certificate trusting?

**Comment by prashantphatate3643** [comment]
Hi Gautam,
Using self signed cert. Will try to install and trust the certificate. and then try it.

**Comment by gautamsi** [comment]
let us know if you solved it.

**Comment by prashantphatate** [comment]
Hi Gautam,
ews-js-api-browser library can be used to integrate with iOS application ???? And also use Self signed Exchange User to interact in backend???? Can I verify email present from the iOS application on my exchange server ???

**Comment by prashantphatate** [comment]
No not using cordova/ionic. creating web interface and calling js functions. Will it work for self signed exchange server accounts ???

**Comment by gautamsi** [comment]
you can not call it form web interface, it has to be native application where CORS is not an issue. 

for web application using ews-javascript-library CORS is major problem not the certificate
