### ISSUE TITLE
this.propertySetId.ToString is not a function

### ISSUE THREAD

**Issue by dpk07** [gautamsi/ews-javascript-api#289]
I am setting extended properties on my EmailMessage object. When I do EmailMessage.SendAndSaveCopy
this error( this.propertySetId.ToString is not a function ) pops up, and the mail is not sent.
This is the stack trace if it helps.
[StackTrace.txt](https://github.com/gautamsi/ews-javascript-api/files/2585371/StackTrace.txt)
Thanks a lot in advance.

**Comment by gautamsi** [comment]
how are you setting the ExtendedProperty?

**Comment by dpk07** [comment]
This is the way in which I am setting ExtendedProperties,
emailObject.SetExtendedProperty(new ewsclass.ExtendedPropertyDefinition(propertySetId, 'Name', ewsclass.MapiPropertyType.String), 'Value')

**Comment by gautamsi** [comment]
this should not be the problem anymore, reopen if still facing this. I believe this one may be due to invalid value for `propertySetId` in parameter.
