### ISSUE TITLE
Typescript compilation errors

### ISSUE THREAD

**Issue by Faruktulumcu** [gautamsi/ews-javascript-api#293]
I'm having compilation errors when this library is used into a Node.js application written in TypeScript. 

I fixed by importing the missing modules into ExchangeWebService.d.ts 
replaced
import { FetchStream, fetchUrl, FetchOptions } from 'fetch';
with
import { FetchStream, fetchUrl, FetchOptions, XMLHttpRequest, Node } from 'fetch';

Log of errors:

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:247:27 - error TS2304: Cannot find name 'Node'.

247     parseXMLNode(xmlNode: Node, soapMode?: boolean, xmlnsRoot?: any): any;
                              ~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:293:42 - error TS2304: Cannot find name 'XMLHttpRequest'.

293     customRequestInitializer?: (request: XMLHttpRequest) => void;
                                             ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:306:100 - error TS2304: Cannot find name 'XMLHttpRequest'.

306     xhr(xhroptions: IXHROptions, progressDelegate?: (progressData: IXHRProgress) => void): Promise<XMLHttpRequest>;
                                                                                                       ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:307:105 - error TS2304: Cannot find name 'XMLHttpRequest'.

307     xhrStream(xhroptions: IXHROptions, progressDelegate: (progressData: IXHRProgress) => void): Promise<XMLHttpRequest>;
                                                                                                            ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:1453:131 - error TS2304: Cannot find name 'XMLHttpRequest'.

1453     fetchOptions: FetchOptions;    xhr(xhroptions: IXHROptions, progressDelegate?: (progressData: IXHRProgress) => void): Promise<XMLHttpRequest>;
                                                                                                                                       ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:1454:105 - error TS2304: Cannot find name 'XMLHttpRequest'.

1454     xhrStream(xhroptions: IXHROptions, progressDelegate: (progressData: IXHRProgress) => void): Promise<XMLHttpRequest>;
                                                                                                             ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:1508:100 - error TS2304: Cannot find name 'XMLHttpRequest'.

1508     xhr(xhroptions: IXHROptions, progressDelegate?: (progressData: IXHRProgress) => void): Promise<XMLHttpRequest>;
                                                                                                        ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:1509:105 - error TS2304: Cannot find name 'XMLHttpRequest'.

1509     xhrStream(xhroptions: IXHROptions, progressDelegate: (progressData: IXHRProgress) => void): Promise<XMLHttpRequest>;
                                                                                                             ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:1583:47 - error TS2304: Cannot find name 'XMLHttpRequest'.

1583     ProcessHttpErrorResponse(httpWebResponse: XMLHttpRequest, webException: any): any;
                                                   ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:1584:29 - error TS2304: Cannot find name 'XMLHttpRequest'.

1584     TraceResponse(response: XMLHttpRequest, memoryStream: any): any;
                                 ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:1586:41 - error TS2304: Cannot find name 'XMLHttpRequest'.

1586     TryGetRedirectionResponse(response: XMLHttpRequest, redirectUrl: IOutParam<Uri>): boolean;
                                             ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:6290:47 - error TS2304: Cannot find name 'XMLHttpRequest'.

6290     ProcessHttpErrorResponse(httpWebResponse: XMLHttpRequest, webException: any): any;
                                                   ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:16911:51 - error TS2304: Cannot find name 'XMLHttpRequest'.

16911     static IsRedirectionResponse(httpWebResponse: XMLHttpRequest): boolean;
                                                        ~~~~~~~~~~~~~~

node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts:16913:39 - error TS2304: Cannot find name 'XMLHttpRequest'.

16913     ProcessWebException(webException: XMLHttpRequest): void;
                                            ~~~~~~~~~~~~~~

[10:21:32 AM] Found 33 errors. Watching for file changes.

**Comment by gautamsi** [comment]
`XMLHttpRequest` may be due to newest TypeScript has removed browser specific api in lib.d.ts

**Comment by gautamsi** [comment]
use typescript compiler option `lib`

```
"lib": [
            "es2015",
            "dom"
        ],
```
