### ISSUE TITLE
Sending Body AS html not worling

### ISSUE THREAD

**Issue by BaardOvrebo** [gautamsi/ews-javascript-api#303]
I might be doing something wrong.
But what happens is that I can send text without any html tags.
If I add any hymn tags all the text enclosed in the tags are removed.

I pass along the BodyType.HTML when creating the new body text. 
Is this a bug or me doing it wrong?

**Comment by gautamsi** [comment]
see #295

**Comment by BaardOvrebo** [comment]
Thank you. I will give it a try when I’m back at my computer. I thought I did try escaping the html first. But it might have not been implemented correctly. I will give an update tomorrow
