### ISSUE TITLE
Get Users E-Mail by token

### ISSUE THREAD

**Issue by garrit-schroeder** [gautamsi/ews-javascript-api#305]
Hello,

is it possible to get the users emailaddress by an oauth token provided by office.js?
Which operation should i use?

**Comment by gautamsi** [comment]
I don't think you can do that with auth token.  There may be some hacky way to do this. 

you are better with `Office.context.mailbox.userProfile` api on add-in side to get the details. If you are passing on the token to back end service to use there you can use the single sign on with add-in docs for this https://docs.microsoft.com/en-us/office/dev/add-ins/develop/sso-in-office-add-ins
