### ISSUE TITLE
Deleting An Appointment Using A Global ID?

### ISSUE THREAD

**Issue by WilsonCWong** [gautamsi/ews-javascript-api#307]
Hi,

Currently, I'm retrieving appointments from a room list using ```service.FindAppointments()```, which works great. The problem is that the ```appointment.Id.UniqueId``` property that I get from this appointment corresponds to the room list's calendar, not from the appointment organizer's calendar. I've confirmed this by returning the ```UniqueId``` when I book the appointment, which was different from the appointment retrieved from the room lists. Due to this, when I bind to this appointment using its ID and try to delete it with ```CancelMeeting()```, I get the ```User must be an organizer for CancelCalendarItem action.``` error.

Is there a way to get a global ID of some sort to delete the appointment?

**Comment by gautamsi** [comment]
You can get the organizer name from the meeting then try to bind that appointment using explicit permission or impersonation.

You can use folder id with mailbox parameter
