### ISSUE TITLE
Unable to install "ews-javascript-api-auth" without git installed!!!

### ISSUE THREAD

**Issue by brt-chetan-mk** [gautamsi/ews-javascript-api#309]
Environment: Raspberry Pi
Platform: Raspbian
Server: node (v8.16) npm(6.4.1) - Installed
Git: Not Installed

Hi Gautam,

Please help me on this:
We need to install all dependent packages on our application using npm in raspberry pi.
Since we use ews-javascript-api-auth it gives me error "fetchPackageMetaData error for ntlm-client@git+https://git@github.com/gautamsi/node-ntlm-client.git Error while executing:"

So, we downloaded the archive version to .tgz and then tried to install the package.
Now no error while installation. But application cannot run. It says "cannot find module ews-javascript-api-auth"

Thanks,

**Comment by brt-chetan-mk** [comment]
![image](https://user-images.githubusercontent.com/39684236/59520693-157e9c80-8efd-11e9-85c7-e15b27e3c454.png)

**Comment by gautamsi** [comment]
the issue is with the `ntlm-client` which still hasn't accepted my PR. let me see if I can make some improvements over next week and use a renamed package

**Comment by brt-chetan-mk** [comment]
ok... thank you
