### ISSUE TITLE
what is the ews function that uses for giving reply to an email???

### ISSUE THREAD

**Issue by siva201010sivakumar** [gautamsi/ews-javascript-api#312]
what is the ews function that uses for giving reply to an email???

**Comment by gautamsi** [comment]
you have to `EmailMessage.Bind` with item id or list emails, then use one of them as instance of `EmailMessage`, then use `<EmailMessage>.Reply` method

**Comment by siva201010sivakumar** [comment]
can we add an attachment while giving reply if yes how to keep in replytoitem or replyalltoitem in ews soap request???

**Comment by gautamsi** [comment]
see this - https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-respond-to-email-messages-by-using-ews-in-exchange

you can use `<EmailMessage>.CreateReply` and attach items. Attachments are not preserved with reply all so you have to fetch attachment and attach them when replying/all.

**Comment by siva201010sivakumar** [comment]
Thank You, working now.
