### ISSUE TITLE
Schema Validation error for older exchange versions

### ISSUE THREAD

**Issue by Tyranicangel** [gautamsi/ews-javascript-api#313]
When trying to update an email belonging to 2010_2 exchange version I get the following error 

const email:EmailMessage = {{some email message}}

email.IsRead = true
email.Update(ConflictResolutionMode.AutoResolve);

The request failed schema validation: The SuppressReadReceipts attribute is not declared.

This is specific to 0.9.5. I switched to using 0.9.4 for now.
From my understanding the attribute was added in 2013_1 exchange version.

**Comment by gautamsi** [comment]
I have tried it, it works perfectly. I am using latest. Please provide full code example to reproduce. 

I have tried this, it finds 10 items which are unread and mark them read one by one.

```js
(async () => {
    const view = new ItemView(10);
    view.PropertySet = PropertySet.FirstClassProperties;
    const response = await service.FindItems(WellKnownFolderName.Inbox, "isRead:false", view);
    const email = response.Items[0] as EmailMessage
    EwsLogging.Log(email.Id.ChangeKey, true, true)
    EwsLogging.Log(email.From, true, true)
    EwsLogging.Log(email.Subject, true, true)
    EwsLogging.Log(email.IsRead, true, true)
    EwsLogging.Log(response.TotalCount, true, true)
    email.IsRead = true;
    for (const em of response.Items) {
        const mail = em as EmailMessage;
        EwsLogging.Log(`${email.From} - ${mail.Subject} - ${mail.IsRead}`, true, true)
        mail.IsRead = true;
        await mail.Update(ConflictResolutionMode.AutoResolve);
    }
    console.log(email.IsRead);
})()
```

**Comment by Tyranicangel** [comment]
I have exact same snippet of code. EWS version is ExchangeVersion.Exchange2010_SP2.

**Comment by gautamsi** [comment]
this doesn't help in test result.

**Comment by gautamsi** [comment]
seems #316 may be the problem. Can you try again with latest 0.9.6 version.
