### ISSUE TITLE
Update not working on Exchange Items

### ISSUE THREAD

**Issue by jwfortney** [gautamsi/ews-javascript-api#316]
I'm using the ews-javascript-api to update an appointment (meeting) in exchange. I am getting an error that says:

The request failed schema validation: The \'SuppressReadReceipts\' attribute is not declared.

I was able to change this compiled js file 
node_modules/ews-javascript-api/js/core/requests/UpdateItemRequest.js

from this: 
if (hasValue(this.SuppressReadReceipts))

to this:
if (this.SuppressReadReceipts) {

This is an optional value that would only be valid when updating items and is false by default.  If you have a look at the original source https://github.com/OfficeDev/ews-managed-api/blob/master/Core/Requests/UpdateItemRequest.cs . What you should be doing is after checking there is a value only set the attribute if that value is true (which is what the original does) rather then then setting if there is any value to true.

See stackoverflow for the details of the problem happening.  Here's the link:
https://stackoverflow.com/questions/57485520/error-updating-an-exchange-meeting-using-the-ews-javascript-api/57502950#57502950

Thank you much, love the api!

**Comment by gautamsi** [comment]
thanks for catching this. I will update this soon.

**Comment by jwfortney** [comment]
Thank you!

On Aug 17, 2019, at 2:40 PM, Gautam Singh <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #316<https://github.com/gautamsi/ews-javascript-api/issues/316> via 841ca30<https://github.com/gautamsi/ews-javascript-api/commit/841ca30750ef67fb881ab1129a1a3f86dc036bea>.

**Comment by gautamsi** [comment]
you can try 0.9.6 which includes this fix

**Comment by jwfortney** [comment]
It’s working for me now, thank you for the fix!
