### ISSUE TITLE
Updating appointment with attachment does not update attachment

### ISSUE THREAD

**Issue by dennis2k** [gautamsi/ews-javascript-api#317]
Hi i have an issue when maintaining outlook appointments.

I can create an appointment with attachments just fine - but when updating an existing it like it's always one version behind - but I can workaround it by running the Update function twice then the changes takes effect. I've found the workaround from an old stackoverflow post on the C# version of the api so it might be an issue with EWS it self.

[https://stackoverflow.com/questions/11418163/ews-attachment-not-sent-with-invitation](https://stackoverflow.com/questions/11418163/ews-attachment-not-sent-with-invitation)

Im using version 0.9.6

```
updateMeeting(date: string, meetingId: string, meeting: Meeting, sendToAll: boolean = true) {
	const appointment: ews.Appointment = await this.getAppointment(date, meetingId);
	appointment.Attachments.Clear();
	meeting.attachments.forEach((attachment) => {
		appointment.Attachments.AddFileAttachment(attachment.name, attachment.content);
	});
	return appointment.Update(ews.ConflictResolutionMode.AlwaysOverwrite, sendToAll ? ews.SendInvitationsOrCancellationsMode.SendOnlyToAll : ews.SendInvitationsOrCancellationsMode.SendToNone);
}
```

**Comment by gautamsi** [comment]
if this is in the ews service itself, no one can help with client side implementation.
