### ISSUE TITLE
Unable to retrieve more than 1 item using FindItems

### ISSUE THREAD

**Issue by lheneks** [gautamsi/ews-javascript-api#318]
Hello, 
I am attempting to use this package to read the email from an inbox and look for attachments.  The problem I am having is that it will only ever return 1 item from the inbox, no matter what I do to the ItemView PageSize and Offset. 

For example, the following will only return 1 result even though I know there are significantly more messages in the inbox (it's my inbox).

`const results = await exch.FindItems(ews.WellKnownFolderName.Inbox, new ews.ItemView(100))`

Stepping through the Request execution in SimpleServiceRequestBase.js, I see the request has the necessary values (IndexedPageViewItemView.MaxEntriesReturned is 100 in the xml).  I'm not sure what the issue could be.

Can someone out there verify that they can retrieve more than one item from an inbox?

**Comment by gautamsi** [comment]
If you see the XML has correct value, you can try using same xml in curl/postman to see what server returns, if server does not return right value, then in a client library nothing can be done

**Comment by lheneks** [comment]
I realized the problem, it looks like it isn't generating the impersonation header.  
I believe this line 

`exch.Credentials.ImpersonatedUserId = new ews.ImpersonatedUserId(ews.ConnectingIdType.SmtpAddress, email)`

should be generating a soap header like

`	<t:ExchangeImpersonation>
		    <t:ConnectingSID>
		    	<t:PrimarySmtpAddress>email</t:PrimarySmtpAddress>
		    </t:ConnectingSID>
		</t:ExchangeImpersonation>`

**Comment by gautamsi** [comment]
it should be `exch.ImpersonatedUserId ` not on `Credential`

**Comment by lheneks** [comment]
Doh!  Thanks.  I was basing my work on some existing code we have in C# where the service has a Credentials property.  If you are looking to make the library close to 1-1 compatible (as it seems you are), it might be a good thing to add>  

Good work and thanks again.

**Comment by gautamsi** [comment]
All my work has been on a fork when I started, so basically it may be missing newer stuff. that does not include ImpersonatedUserId on `ExchangeCredentials` base class. once I upgrade the code to latest, then probably it may include.
