### ISSUE TITLE
Error deleting task

### ISSUE THREAD

**Issue by Herotko** [gautamsi/ews-javascript-api#322]
Error deleting task:
Code Example:
async deleteTask(taskId: string) {
        try {
            const task = await this.findTaskById(taskId) as Task; // This function found the Task
            if (task) {
                await task.Delete(DeleteMode.SoftDelete, true); 
                return {id: taskId};
            } else
            // noinspection ExceptionCaughtLocallyJS
                throw new InternalServerError(`Task with id === ${taskId}is not found`);
        } catch (e) {
            throw new InternalServerError(e);
        }
    }

Exception:
{
  "message": "AffectedTaskOccurrences attribute is required for Task items.",
  "InnerException": null,
  "response": {
    "errorDetails": {
      "keys": [],
      "keysToObjs": {},
      "objects": {}
    },
    "errorProperties": [],
    "result": 2,
    "errorCode": 9,
    "errorMessage": "AffectedTaskOccurrences attribute is required for Task items."
  }
}

**Comment by gautamsi** [comment]
have to fix the code for this

**Comment by Herotko** [comment]
Can I help you?


С уважением,
Павел Бормотов


ср, 25 сент. 2019 г. в 17:53, Gautam Singh <notifications@github.com>:

**Comment by gautamsi** [comment]
not needed, I know where is this failing, will fix it soon.
