### ISSUE TITLE
Error service calling 

### ISSUE THREAD

**Issue by Khahory** [gautamsi/ews-javascript-api#325]
I have this error when I use a company proxy. I heard that the firewall might be blocking some requests from the api.

I try to receive a list of rooms and rooms of the company that I have in outlook but it lasts a long time waiting.

**** removed image****

**Comment by gautamsi** [comment]
have you tried using [`@ewsjs/xhr`](https://github.com/ewsjs/xhr) for proxy support?

**Comment by Khahory** [comment]
No, if I am connected to the internal network of the workgroup, with our proxy, then I have to tell the app to connect to an external proxy of our network? using @ ewsjs / xhr, the proxy we use pere has no password but we have to connect to the network

**Comment by gautamsi** [comment]
still having the issue when you use proxy support? you dont have to provide password for proxy, but if you proxy expects integrated authentication somehow, then it may not work.

**Comment by Khahory** [comment]
![image](https://user-images.githubusercontent.com/46386012/66227584-75b36d00-e6ab-11e9-8dbe-08600816b253.png)

Mmm, I can make the company that has the firewall of us accept a link so that the firewall does not block the execution of the App, the problem is that the request of the room and roomList lasts a long time. Sometimes it works or others do not (when I am connected to the network of the company that provides the proxy).

I tried to implement what you told me but it gave me a token error when I try to use the import

Mmm, I can make the company that has the firewall of us accept a link so that the firewall does not block the execution of the App, the problem is that the request of the room and roomList lasts a long time. Sometimes it works or others do not (when I am connected to the network of the company that provides the proxy).

I tried to implement what you told me but it gave me a token error when I try to use the import

Do you have any idea of the link that may be blocked when I use the firewall? And I know that it is ews-javascript-api because when I put in the address bar: root / api / room.js then it loads a lot

**Comment by gautamsi** [comment]
if you are trying this in browser, it will not work without some changes on your network or exchange server

**Comment by Khahory** [comment]
Yes, I understand, one last thing, do you know which link could be the one that is blocked by the firewall? from ews-javascript-api

**Comment by gautamsi** [comment]
unfortunately not, you can have someone check live monitoring for your ip on firewall

**Comment by Khahory** [comment]
Ok, thank you very much, good luck in everything
