### ISSUE TITLE
Email with voting options

### ISSUE THREAD

**Issue by privatmamtora** [gautamsi/ews-javascript-api#331]
I am trying to send an email with voting options.
I have looked around and I see that we have an interface to `get` the voting information & data.

But how do I set it? Do I use the `SetExtendedProperty` method?

Any chance someone has a small sample?

**Comment by gautamsi** [comment]
not sure exactly how to do that in ews managed api, I see someone asked but that was not answered here - https://github.com/OfficeDev/ews-managed-api/issues/206

you can try get help from here - https://gsexdev.blogspot.com/2015/01/sending-message-with-voting-buttons.html
