### ISSUE TITLE
Issue with upgrading to @ewsjs/xhr from ews-javascript-api-auth

### ISSUE THREAD

**Issue by bladerunner2020** [gautamsi/ews-javascript-api#334]
Hello!
I am trying to upgrade to new helper library @ewsjs/xhr from ews-javascript-api-auth.

Original code that works:
```js
ConfigurationApi.SetXHROptions({rejectUnauthorized : credentials.secure}); // global property
const exch = new ExchangeService(credentials.exchangeVersion);
exch.Credentials = new ExchangeCredentials(credentials.username, credentials.password);
exch.Url = new Uri(credentials.url);

const xhr = new ntlmAuthXhrApi(credentials.username, credentials.password, true);
exch.XHRApi  = xhr;

```
I replaced last 2 lines with:
```
const xhr = new XhrApi(true).useNtlmAuthentication(credentials.username, credentials.password);
exch.XHRApi  = xhr;
```

and got lot of warnings and error like this in dom-parse.js:
```
[xmldom error]	element parse error: Error: invalid tagName::]^�e��Sj�l 
[xmldom warning]	unclosed xml attribute 
[xmldom error]	element parse error: Error: invalid tagName:[^�{;�;����^����_ 
[xmldom warning]	attribute "ws}�nC�" missed value!! "ws}�nC�" instead2!! 
```
PS
Tried to use ConfigurationApi.ConfigureXHR(xhr) - with the same result.

Any ideas?

**Comment by Lumpenstein** [comment]
Facing the same error, the `responsetext` of the `xhrResponse` in `SimpleServiceRequestBase.InternalExecute` are invalid chars.

**Comment by gautamsi** [comment]
I dont have access to ntlm server right now, but let me try restoring last one to check. 

what version you are using for ews api and xhr?

**Comment by Lumpenstein** [comment]
Hi gautamsi, I found the solution you described [here](https://github.com/ewsjs/xhr/issues/9).

Setting `exch.AcceptGzipEncoding = false` was fixing the problem for me. @bladerunner2020 give it a try

**Comment by bladerunner2020** [comment]
@Lumpenstein many thanks for link. I read the thread and found the solution. 
I added **gzip: true** too XhrApi constructor:
```js
const xhr = new XhrApi({ rejectUnauthorized: false, gzip: true }).useNtlmAuthentication(credentials.username, credentials.password);
```
PS
@gautamsi: I have 0.10.0 version for ewe-api and 1.4.2 for ewsjs/xhr

**Comment by gautamsi** [comment]
have you tried this:
> Setting exch.AcceptGzipEncoding = false was fixing the problem for me. @bladerunner2020 give it a try

**Comment by bladerunner2020** [comment]
Yeap. This also works. 
I believe gzip:true is better )

> have you tried this:
> 
> > Setting exch.AcceptGzipEncoding = false was fixing the problem for me. @bladerunner2020 give it a try

**Comment by Lumpenstein** [comment]
> I believe gzip:true is better 

True that :) haven't seen the gzip option there, because intellisense not working correclty for the request/request package

**Comment by gautamsi** [comment]
not all options of requestjs is added to typings that is why.

**Comment by Lumpenstein** [comment]
Ah ok, I guess we can close this issue now, maybe add the `gzip:true` option to the readme for future users :)

**Comment by bladerunner2020** [comment]
I don't mind. Still curious when this option is needed and when is not...

**Comment by gautamsi** [comment]
added text in readme for this
