### ISSUE TITLE
Crash when talking to Exchange service using 0.10

### ISSUE THREAD

**Issue by PhilHannent** [gautamsi/ews-javascript-api#340]
Our beta testing of 0.10 has thrown out the following error when connecting to an Exchange server (O365 seems to work well).

`Cannot get appointments from Exchange: ServiceRequestException {  message:   'The request failed. Cannot read property \'Header\' of null',  InnerException:   TypeError: Cannot read property 'Header' of null       at FindItemRequest.ServiceRequestBase.ReadResponseXmlJsObject (/home/site/src/js/Core/Requests/ServiceRequestBase.ts:378:21)       at FindItemRequest.SimpleServiceRequestBase.ReadResponsePrivate (/home/site/src/js/Core/Requests/SimpleServiceRequestBase.ts:110:44)       at /home/site/src/js/Core/Requests/SimpleServiceRequestBase.ts:53:52       at tryCatcher (/home/site/wwwroot/node_modules/bluebird/js/release/util.js:16:23)       at Promise._settlePromiseFromHandler (/home/site/wwwroot/node_modules/bluebird/js/release/promise.js:512:31)       at Promise._settlePromise (/home/site/wwwroot/node_modules/bluebird/js/release/promise.js:569:18)       at Promise._settlePromise0 (/home/site/wwwroot/node_modules/bluebird/js/release/promise.js:614:10)       at Promise._settlePromises (/home/site/wwwroot/node_modules/bluebird/js/release/promise.js:694:18)       at _drainQueueStep (/home/site/wwwroot/node_modules/bluebird/js/release/async.js:138:12)       at _drainQueue (/home/site/wwwroot/node_modules/bluebird/js/release/async.js:131:9)       at Async._drainQueues (/home/site/wwwroot/node_modules/bluebird/js/release/async.js:147:5)       at Immediate.Async.drainQueues (/home/site/wwwroot/node_modules/bluebird/js/release/async.js:17:14)       at runCallback (timers.js:694:18)       at tryOnImmediate (timers.js:665:5)       at processImmediate (timers.js:647:5) }`

**Comment by gautamsi** [comment]
have you looked at what is returned soap from server, if there is any issues there

**Comment by PhilHannent** [comment]
Sorry for the delay.

The soap message is coming out mangled, has the request library changed, since 0.9.4 as that version worked for us? 

We bumped up to 0.10 for access to the headers.

`responseText: '\u001f�\b\u0000\u0000\u0000\u0000\u0000\u0004\u0000��\u0007`\u001cI�%&/m�{J�J��t�\b�`\u0013$ؐ@\u0010������\u001diG#)�*��eVe]f\u0016@�흼��{���{���;�N\'���?\\fd\u0001l��J�ɞ!���\u001f?~|\u001f?"\u001e�\u001e�\u0016ez��MQ-?�hw��Q�/�լX^|�Ѻ=�>��8z�<:]^�e��Sj�l\u001e5�}4o�գ�w��<_d͘>o�l5�ꋻ��n�o��\b�;�fy}�x��u^S?)]�-ϫ��+�\u0001�p���b��4y�.�ً�b����ާ��0���ÏR��O���>��w�����\u0014�y\u000f�E1���:o��jq77�gˋ�nCx\u0016Ӽ��������z�7\n' +
    "��!<z��,������=&\u001c5ܽ�{��5\u0003v���\u001bo\u0017˦͖����G��:�7��T��\u0007齐=z�x��X���|�*oVղ1ܲ�z\u0014[�M�]8��_\u000f�\u0010\u001e�\u0019��P�1�����}Rf\r�����\u0000�`N�Y~��:��~|��9�UU��*i\u001a�7U���9[�d�_\u0011�~��-��z�7ϳ��wg�W@����z�SO�#~\u0003��d��e5>0_���3����/�\u001e�\u0013�?��o�~����o~r��\u000f��\u0017O�����]���wϿ�\u0013{?������?��?���/��|~����������w�7g_��������'�>�:^<�}�W����8���|:�_�~����\u0003y��\u0005�3�����O�M^���}���l�^��g\u001f=�����>Ǜ^���`���ˬΗJ�\u000f\u001a��z�(���Q���\u0017��g�%怹����\u0017��ժ*��\u0010|���Z�^O~:��Gǳ�y5M\u0017yޒ~E3�\r\u001a�˦h�ˢ�&��\u0017Y�\r�O��Ӭ��\u0014��U>͋�|v�����������f�����v�~\n" +
    '��\u001a���\u0007�����\u000f\u00190��(\u0016��fq�z�>D���\\\u0014mK`γ�ɹ��!�yZg���|��=���\u0017���~�ߒ�\u0010s���\'��W�\u0005���"����#\u000bQ���$��{��3���L;z�U� ���O�������;�b��{�h��G�r��|�5#�n��I~^���6�ۣ���\u001b�\u0006\u0018WѬ���dz���M�};k��6�����#h�sh�uٮ��(_n�\u001aM�\u0007����91-�ի�b�͙8�MSM�,`��7��I�lC4:�ۖ�.�:����nS�\u0005���y�[����\u0017`�k���ɔ�f�<�\u001f�%2<��/��^d���\u000b��t�"�&���N�M\u0002SM�\u0002D�}\u0007\u0006�i��z\r��Ξ\u001e����s@f�~>�?���������\u001e�}�c��\u0007{ǻ\u000f��=y�����]��>惃Ӄ\u007\u000f�?==��t�����\u000f��{��{z�����΃�]��~}\u0001k���FI�V�8̓C�a9�t\u0019H��Σ{;�v�ѩ�\u0003�e�4�>���z���\u0018D�/����:ϟ��k�]7G��\t\u001b�\u0012/UӬ%��7��\u000b�@����|�ߟ@a�e��܇܆��;P܇`V\u0001�*�E�i��5��l���\n' +
    '[�\u000f�.w�\u001d�\u000e��y\u0015o�K:zM�K\u0011��W���@�O��/�%Y���\n' +
    "����k~5+�I�\u000e��F|�Ȝ.��٬&����|��W�/�����N�o\u001f���4=~��ً��o^\u001d�9�����W_~�2�z��<={�巟��{����7w������˳�\u0017o^㯓�}���\u000f�>}�����g\u0007�O�?{�����g�϶�8=}s����՗_~�n33��@Tk\f��|�{�\u0012�>a�����P��\u0016�z�f�ۻ�_��a-k?�&\u0010�������WoN>فI��'e�\u001c��\u0014�M���|�>/�IE\u001f=���j\t(�M��9&�1�Ď\u0012+\u001d����םwIZ��+�)sߗK�+��H�E���|���_�ݾ���������W�$��hyڿ9��ޛ�\u0007��v�nlvl?�w�\u0001��߱\u001d ɍ������~��m\u001c���G���_�؂��u��y�5=�ϟ���������\n" +
    '\'�=��\u001b�x���;~���\'�>=����<|������ӽ�O\u001f�?;8x�p�����O\u000f�����o�x�Do��\r\u0004g���������\u001f��kY�G������{;_���������b�]R��y��y�\f��\u0019��eu�"�\u0002~/�jU5Yi94�%s�m�h⚼}=����˻�?p��M��A��o���\u0016[���y�6o�����sN�v:O�Z�Q�f\\���{���������վ���=\u0006��sW{�$�]���n�jz{Wێ��k��x�>��U�y5/x�?���Q��g���\u0019�S�\u001f�y��\u001e<{r�x����&���\u001dJ,Ss�O�\u001f<��d�����O鿇\u000fw��{��l�-��\u001e�p[�ۗ�A������y�4��oq��_�y>���\u0015[��t�C�\u0005\u0000?\u0014����g\'\u000fO(��������γ��O\u001f��<���鳃��O�|E�}���:}�mfş%ϛE�g��~����\u0001�#�0�8\u0004�����+�w�Y��;\f�\u001f�\u0017�Ļ\u000b��J=T��\u0019\u0019`|ix�\u000b���"���gM��w�GO�\u0019\u0019\u0018��ty���*?�\u0000�,U\u0004�%\u0000\u0000',`

**Comment by PhilHannent** [comment]
OK, some bright spark figured out this was gzip and then that meant it was #334 

Adding the gzip option solved the issue:

`xhr = new XhrApi({ gzip: true })`
