### ISSUE TITLE
Office 365 Single Sign On support

### ISSUE THREAD

**Issue by PhilHannent** [gautamsi/ews-javascript-api#342]
We have someone that is using Office 365 with their own Active Directory. When the user logs into Office.com, they type in their email and it redirects to their own authentication portal before being redirected to their office 365 account.

Does ews-javascript-api support this type of authentication?

**Comment by gautamsi** [comment]
yes, you have to use a oAuth method (create app in azure, have some ui and redirection) and capture the correct access token, then you can pass on the token to the lib using oAuthCredential type.
