### ISSUE TITLE
 Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by lemontea1990** [gautamsi/ews-javascript-api#343]
hi,

i am try to use NTLM to connect with my EWS server, but i always get the error like the title, its really strange because this was lead to the ews-javascript-api error. 
i am using the 0.9.0 version ews-javascript-api and ntlmXHRApi 

the error message is:
`"TypeError: Cannot read property 'then' of undefined\n    at node_modules\ews-javascript-api\js\Core\Requests\SimpleServiceRequestBase.js:50:50\n    at Promise._execute (node_modules\bluebird\js\release\debuggability.js:384:9)\n    at Promise._resolveFromExecutor (\node_modules\bluebird\js\release\promise.js:518:18)\n    at new Promise (\node_modules\bluebird\js\release\promise.js:103:10)\n    at GetRoomListsRequest.SimpleServiceRequestBase.InternalExecute (\node_modules\ews-javascript-api\js\Core\Requests\SimpleServiceRequestBase.js:47:16)\n    at GetRoomListsRequest.Execute (\node_modules\ews-javascript-api\js\Core\Requests\GetRoomListsRequest.js:38:21)\n    at `

**Comment by gautamsi** [comment]
there must be some parameter mismatch which does not create proper request. 

can you post sample code which throws the error?

**Comment by lemontea1990** [comment]
Hi,

thanks for your reply
i detected that the error was occurred at this function:

`var getListOfRooms = function () {
    var promise = new Promise(function (resolve, reject) {
      exch.GetRoomLists().then((lists) => {
        var roomLists = lists.items;
        resolve(roomLists);
      }, (err) => {
        callback(err, null);
        console.log("there is the callback error in Rooms.js" + err);
      });
    })
    return promise;
  };`


this is the first step after i passed the ews verification.
the verification was based on your XHR suggestion, as my exchange server requires NTLM(that means i have to use ews-javascript-api version 0.9.0):

`var ews = require("ews-javascript-api");
  var auth = require("../../config/auth.js");
  var blacklist = require("../../config/room-blacklist.js");  
  var ntlmXHR = require("../../config/ntlmXHRApi");
  // ews -----------------------------------------------------------------------
  
  ews.EwsLogging.DebugLogEnabled = true;
  var ntlmXHRApi = new ntlmXHR.ntlmXHRApi("UserName","PWD");


  var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2016);
  exch.XHRApi = ntlmXHRApi;
  exch.Credentials = new ews.ExchangeCredentials("UserName","PWD");
  exch.Url = new ews.Uri(auth.exchange.uri);`

i checked the ews log, it showed the connection was fine without error.


![image](https://user-images.githubusercontent.com/16532622/76579837-a58f5800-6508-11ea-8455-e5a2f48f6a5c.png)

Btw, i am using the template from [https://github.com/danxfisher/MeetEasier](url):)

**Comment by bladerunner2020** [comment]
@lemontea1990 
You could try this code. In our case it works with ntlm. 

"@ewsjs/xhr": "^1.4.2"
"ews-javascript-api": "^0.10.0"

```js
/* eslint-disable no-console */
const debug = require('debug')('ExchangeCalendarSystem');
const { ExchangeService, ExchangeCredentials, Uri } = require('ews-javascript-api');
const { XhrApi } = require('@ewsjs/xhr');

const { credentials } = require('credentials.json');

const exch = new ExchangeService(credentials.exchangeVersion);
exch.Credentials = new ExchangeCredentials(credentials.username, credentials.password);
exch.Url = new Uri(credentials.url);

const xhr = new XhrApi({ rejectUnauthorized: false, gzip: true })
    .useNtlmAuthentication(credentials.username, credentials.password);
exch.XHRApi = xhr;

async function requestCalendarList() {
  const list = [];
  const { Items: items } = await exch.GetRoomLists();
  for (const index in items) {
    const { address, name } = items[index];
    debug(`List: ${name} - ${address}`);
    const rooms = await exch.GetRooms(items[index]);
    debug(`  room count: ${rooms.length}`);
    for (let i = 0; i < rooms.length; i++) {
      const { name, address: id } = rooms[i];
      debug(`  ${i}. ${name}: ${id}`);
      list.push({ name, id });
    }
  }
  return list;
}

requestCalendarList()
  .then((list) => list.forEach((item) => console.log(item)))
  .catch((err) => console.log(err));
``

**Comment by lemontea1990** [comment]
> @lemontea1990
> You could try this code. In our case it works with ntlm.
> 
> "@ewsjs/xhr": "^1.4.2"
> "ews-javascript-api": "^0.10.0"
> 
> ```js
> /* eslint-disable no-console */
> const { ExchangeService, ExchangeCredentials, Uri } = require('ews-javascript-api');
> const { XhrApi } = require('@ewsjs/xhr');
> 
> const { credentials } = require('credentials.json');
> 
> const exch = new ExchangeService(credentials.exchangeVersion);
> exch.Credentials = new ExchangeCredentials(credentials.username, credentials.password);
> exch.Url = new Uri(credentials.url);
> 
> const xhr = new XhrApi({ rejectUnauthorized: false, gzip: true })
>     .useNtlmAuthentication(credentials.username, credentials.password);
> exch.XHRApi = xhr;
> 
> async function requestCalendarList() {
>   const list = [];
>   const { Items: items } = await exch.GetRoomLists();
>   for (const index in items) {
>     const { address, name } = items[index];
>     const rooms = await exch.GetRooms(items[index]);
>     for (let i = 0; i < rooms.length; i++) {
>       const { name, address: id } = rooms[i];
>       list.push({ name, id });
>     }
>   }
>   return list;
> }
> 
> requestCalendarList()
>   .then((list) => list.forEach((item) => console.log(item)))
>   .catch((err) => console.log(err));
> ```

hi, thanks for your solution, it looked like also worked at my side.
Because i got the response from Server: error code 401.
i think there should be some problem about the NTLM v1.2 authentication process.
anyway, thanks again.


btw, i solved this problem by C# easily, now i am using windows service to query data from ews server and then push into SqlServer.
