### ISSUE TITLE
Autodiscovery using Email address is not working

### ISSUE THREAD

**Issue by srinathgnath** [gautamsi/ews-javascript-api#348]
Hello,

Autodiscovery using Email address is not working. Any help would be appreciated.

var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010_SP2);
exch.Credentials = new ews.ExchangeCredentials("id@domain.com", "password");
exch.AutodiscoverUrl("id@domain.com",);

ERROR: ---------------
TypeError: Cannot read property 'AbsoluteUri' of null
    at Function.ExchangeCredentials.GetUriWithoutSuffix (C:\TestProject\node_modules\ews-javascript-api\js\Credentials\ExchangeCredentials.js:28:31)

**Comment by gautamsi** [comment]
version? 0.10?
another correction, use `ews.WebCredentials` instead.

**Comment by kstankov** [comment]
Hi,

I am using another approach, have a try:

(copied my code, you'll figure it out...)

this._exch.HttpHeaders.Add("X-AnchorMailbox", account.email);
this._exch.Url = null;
var autod = new ews.AutodiscoverService(global.config.exchangeVersion);
autod.RedirectionUrlValidationCallback = RedirectionUrlValidationCallback;
autod.Credentials = new ews.WebCredentials(email, password);
            var settings = [
                ews.UserSettingName.InternalEwsUrl,
                ews.UserSettingName.ExternalEwsUrl,
                ews.UserSettingName.UserDisplayName,
                ews.UserSettingName.UserDN,
                ews.UserSettingName.EwsPartnerUrl,
                //ews.UserSettingName.DocumentSharingLocations,
                ews.UserSettingName.MailboxDN,
                ews.UserSettingName.ActiveDirectoryServer,
                ews.UserSettingName.CasVersion,
                ews.UserSettingName.ExternalWebClientUrls,
                ews.UserSettingName.ExternalImap4Connections,
                ews.UserSettingName.AlternateMailboxes
            ];
            await autod.GetUserSettings(email, settings)
                .then(function (response) {
                    var ewsUriKey =
response.Settings.Keys.indexOf(ews.UserSettingName.ExternalEwsUrl);
                    var ewsUriKeyInt =
response.Settings.Keys.indexOf(ews.UserSettingName.InternalEwsUrl);
                    console.log("Setting autodiscovery URL to:",
response.Settings.Items[ewsUriKey].value);
                    self._exch.Url = new
ews.Uri(response.Settings.Items[ewsUriKey].value);
//Set credentials with WebCredentials

and then check with:

 await this._exch.ResolveName(account.email).then(response => {...})


Have a try


------------------------------------------------------------------------
*With best regards,*
Kiril Stankov

**Comment by srinathgnath** [comment]
iIstead of auto discovery, I replaced with uri. But now I'm getting "401 unauthorised". I have similar code in C# and it works fine with same credentials/URL.

var ews = require("ews-javascript-api");
ews.ConfigurationApi.SetXHROptions({rejectUnauthorized : false});
ews.EwsLogging.DebugLogEnabled = false;

var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010_SP2);
exch.Credentials = new ews.ExchangeCredentials("id@domain.com", "password");

exch.Url = new ews.Uri("https://domain/EWS/exchange.asmx");

exch.SubscribeToStreamingNotifications([new ews.FolderId(ews.WellKnownFolderName.Inbox)], ews.EventType.NewMail, ews.EventType.Created, ews.EventType.Deleted, ews.EventType.Modified, ews.EventType.Moved, ews.EventType.Copied, ews.EventType.FreeBusyChanged)
    .then(function (streamingSubscription) {
        var connection = new ews.StreamingSubscriptionConnection(exch, 1);
        console.log("subscribing....: ");
        connection.AddSubscription(streamingSubscription);
        connection.OnNotificationEvent.push(function (obj, notificationArgs) {
            console.log("notification received: ");
            ews.EwsLogging.Log(obj, true, true);
            // EwsLogging.Log(notificationArgs, true, true);
        });
        connection.OnDisconnect.push(function (connection, subscriptionErrorEventArgsInstance) {
            console.log("disconnecting...");
            ews.EwsLogging.Log(subscriptionErrorEventArgsInstance, true, true);
            //access subscriptionErrorEventArgsInstance
            //connection.Open();
        });
        connection.Open();
    }, function (err) {
        console.log("ERROR: ---------------  ");
        console.log(err);
    });

**Comment by gautamsi** [comment]
is your server supporting basic auth? if server supports NTLM only then you have to use `@ewsjs/xhr` to get this working.

**Comment by srinathgnath** [comment]
Yes It does support. I tried both and getting same 401 error.

**Comment by gautamsi** [comment]
so the other operations, like FindItems, Item.Bind etc. works but streaming notification does not, correct?

**Comment by srinathgnath** [comment]
I didn't try any other operations.

**Comment by srinathgnath** [comment]
Finally  I was able to get notifications.  Any idea how can i fetch the email body which triggered the notification?

**Final version of EWS streaming notifications code:**

> var ews = require("ews-javascript-api");
> var ewsAuth = require("@ewsjs/xhr");
> ews.EwsLogging.DebugLogEnabled = false;
> const exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010_SP2);
> const xhr = new ewsAuth.ntlmAuthXhrApi("ID", "PASSWORD", true);
> exch.XHRApi  = xhr;
> exch.Credentials = new ews.WebCredentials("ID", "PASSWORD");
> exch.Url = new ews.Uri("https://DOMAIN.COM/EWS/exchange.asmx");

> exch.SubscribeToStreamingNotifications([new ews.FolderId(ews.WellKnownFolderName.Inbox)], ews.EventType.NewMail)
>     .then(function (streamingSubscription) {
>         var connection = new ews.StreamingSubscriptionConnection(exch, 10);
>         console.log("subscribing....: ");
>         connection.AddSubscription(streamingSubscription);
>         connection.OnNotificationEvent.push(function (obj, notificationArgs) {
>             console.log("notification received: ");
>             ews.EwsLogging.Log(obj, true, true);
>             // EwsLogging.Log(notificationArgs, true, true);
>         });
>         connection.OnDisconnect.push(function (connection, subscriptionErrorEventArgsInstance) {
>             console.log("disconnecting...");
>             ews.EwsLogging.Log(subscriptionErrorEventArgsInstance, true, true);
>             //access subscriptionErrorEventArgsInstance
>             //connection.Open();
>         });
>         connection.Open();
>     }, function (err) {
>         console.log("ERROR: ---------------  ");
>         console.log(err);
>     });

**Comment by kstankov** [comment]
You should have the item ID in the notification.

Use it and do Appointment.Bind(...)
