### ISSUE TITLE
SubscribeToStreamingNotifications - on specific email

### ISSUE THREAD

**Issue by JojiePalahang** [gautamsi/ews-javascript-api#350]
Hi All,

I want to consume any new emails on specific shared emails may how can I do it?

see the code 
```js
const { EwsLogging, FolderId, ExchangeService,
    StreamingSubscriptionConnection, WellKnownFolderName,
    StreamingSubscription, ExchangeVersion, Uri,
    ExchangeCredentials, WebCredentials, EventType } = require("ews-javascript-api");


async function main() {
    const service = new ExchangeService(ExchangeVersion.Exchange2013_SP1);
    service.Credentials = new ExchangeCredentials("domain\\user", "passowrd")
    service.Url = new Uri("https://xxxxx");


    const streamingSubscription = await service.SubscribeToStreamingNotifications([new FolderId(WellKnownFolderName.Inbox)], [EventType.NewMail]);

    // Create a streaming connection to the service object, over which events are returned to the client.
    // Keep the streaming connection open for 30 minutes.
    let connection = new StreamingSubscriptionConnection(service, 30);
    connection.AddSubscription(streamingSubscription);
    connection.OnNotificationEvent.push((o, a) => {
        console.log(a)
        console.log("notification received") //this gives you each notification.
        EwsLogging.Log(a, true, true);
    });

    connection.Open();
}

main().then(() => console.log("Running ..."))`

**Comment by gautamsi** [comment]
```js
connection.OnNotificationEvent.push((o, a) => {
        console.log(a)
        console.log("notification received") //this gives you each notification.
        EwsLogging.Log(a, true, true);
    });
```

`a` is `NotificationEventArgs` which gives you notification type an you can access the item id, then you can use that item id to get more details from server.

**Comment by JojiePalahang** [comment]
@gautamsi  but it's not coming on that event, I'm not sure if I need to implement ` service.AutodiscoverUrl("share@domain.com")` but when implementing this line I received this error
![image](https://user-images.githubusercontent.com/19182512/82564243-07280e80-9bab-11ea-8f35-36b577ca7b6f.png)

**Comment by gautamsi** [comment]
You may be using old version, update to latest.

You dont need autodiscover to get streaming subscription working.

**Comment by JojiePalahang** [comment]
@gautamsi - okay does it mean, the account that I entered in the credentials will be the default email address that is consumed? - this code was from your typescript I'm not sure if this is a code problem because my code is a js

**Comment by gautamsi** [comment]
yes, you have right version. 

what is the value you get in `EwsLogging.Log(a, true, true);` ? or you dont even get there.

**Comment by JojiePalahang** [comment]
if it's logging in console no output just my custom logs

**Comment by gautamsi** [comment]
have you tried this with provided url rather than autodicover it? I am not sure where does your code break? in autodisocver or streaming subscription?

**Comment by JojiePalahang** [comment]
Given this code when I execute this `
async function main() {
    const service = new ExchangeService(ExchangeVersion.Exchange2013_SP1);
    service.Credentials = new ExchangeCredentials("xxxx\\xxx", "xxxxxpass");
    service.Url = new Uri("https://xxxx.com/Ews/Exchange.asmx");
    // service.AutodiscoverUrl("xxxx" , (url)=>{
    //     console.log(url);
    //     return true;
    // })

    const streamingSubscription = await service.SubscribeToStreamingNotifications([new FolderId(WellKnownFolderName.Inbox)], EventType.NewMail, EventType.NewMail, EventType.Created,
    EventType.Deleted, EventType.Modified, EventType.Moved,
    EventType.Copied, EventType.FreeBusyChanged);
    console.log("JOjie");
    // Create a streaming connection to the service object, over which events are returned to the client.
    // Keep the streaming connection open for 30 minutes.
    let connection = new StreamingSubscriptionConnection(service, 30);
    connection.AddSubscription(streamingSubscription);
    connection.OnNotificationEvent.push((o, a) => {
        console.log(a)
        console.log("notification received") //this gives you each notification.
        EwsLogging.Log(a, true, true);
    });
     

    connection.Open();
}

main().then(() => console.log("Running ..."))`


This is the logs I received
![image](https://user-images.githubusercontent.com/19182512/82569237-89680100-9bb2-11ea-9be4-9de63183ec7f.png)

**Comment by JojiePalahang** [comment]
@gautamsi  - thanks for the support, your comments are really much appreciated. As you mentioned we don't need to do both I URL and Autodiscover, I used the URL provided and it works.

I just have small doubt here, what if the app suddenly stops working, Can I get that missed notification on the next event? If Yes - it is safe but If No is there a way I can get the missed notifications?

**Comment by gautamsi** [comment]
You may miss all the things when your app is down. You also need to hook into `OnDisconnect` events as the max lifetime of this connection is 30min on exchange server.

```js
connection.OnDisconnect.push(() => {
    // yoiur logic for connecting again.
});
```

**Comment by gautamsi** [comment]
if you do not need live notification, you can use `service. SyncFolderItems` to [sync changes ](https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/ee693003(v%3Dexchg.80))even if the app was offline.

**Comment by JojiePalahang** [comment]
SyncFolderItems  - will download all new emails ? is that what you mean just in case the notification app will go down

**Comment by gautamsi** [comment]
it has `sync state` which keeps track of what has change since then. 

when you call it first time it will give you sync state and then you can use it in next call which will give you another sync state. 

this method can be called very 5 min to get all the latest changes without listening to the streaming events. this is different than streaming event.

**Comment by JojiePalahang** [comment]
okay means I can listen and read the new emails every 5 mins and the next reading the previous read mail will no part of it right? do you have a gist for this SyncFolderItems?

**Comment by gautamsi** [comment]
https://docs.microsoft.com/en-us/previous-versions/office/developer/exchange-server-2010/ee693003(v%3Dexchg.80)

**Comment by JojiePalahang** [comment]
Thanks a lot @gautamsi, closing this issue now.
