### ISSUE TITLE
Server stuck and no action happens 

### ISSUE THREAD

**Issue by yaron14** [gautamsi/ews-javascript-api#352]
I'm trying to send an email from my local Exchange server.

I turned the debugger on and the XML looks fine but for some reason the server is stuck.
No success nor failed response.
Node js process in the CPU is 0% so nothing really happens.

Any idea what should be done?

**Comment by gautamsi** [comment]
try sending same xml using Postman app, if that succeeds try again and compare headers as well.

**Comment by yaron14** [comment]
Same result using postman - stuck on sending request.

**Comment by gautamsi** [comment]
then try to get your server fixed, 
also check if you can use c# version and if that helps.

**Comment by yaron14** [comment]
It's very strange as I could send an email using node-ews.
Maybe I'm missing something in my configuration?

var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);
exch.Credentials = new ews.ExchangeCredentials("MY_EXCHANGE_EMAIL", "PASSWORD");
exch.Url = new ews.Uri("SERVER_URI");

**Comment by gautamsi** [comment]
problem is that you are not able to use xml using postman. does node-ews generate same xml as ews-javascript-api

**Comment by yaron14** [comment]
Very similar.
I don't think that the issue is within the XML but maybe authentication method or missing/wrong header.

**Comment by yaron14** [comment]
I managed to get it work:
The difference between this library and node-ews is that in the uri I had to add /EWS/Exchange.asmx to the server uri.
