### ISSUE TITLE
Accessing raw request

### ISSUE THREAD

**Issue by Alino** [gautamsi/ews-javascript-api#383]
I would like to be able to access the raw request for debugging purposes, is this somehow possible?

It would be really cool if it would be possible to do both - access raw request and response.
Related issue -> https://github.com/gautamsi/ews-javascript-api/issues/184

**Comment by Alino** [comment]
I solved my issue with

```ews.EwsLogging.DebugLogEnabled = true;```

this now outputs raw request and response which is cool.
But perhaps still someone might want to access this programmatically.

**Comment by gautamsi** [comment]
you can modify the XHR Api and plug your own to access them raw.
