### ISSUE TITLE
Accessing email as a delegate

### ISSUE THREAD

**Issue by Alino** [gautamsi/ews-javascript-api#384]
I haven't seen this in the documentation, or any methods related to this -> https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-access-email-as-a-delegate-by-using-ews-in-exchange#search-for-an-email-as-a-delegate-by-using-ews

Is this currently not available in this lib? Thank you

**Comment by gautamsi** [comment]
most of the example there would work, look for corresponding EWS Managed api code examples.

in all cases you have to use a variant which uses `FolderId` object with mailbox of primary user. see example on that page 

`new FolderId(WellKnownFolderName.SentItems, new Mailbox("primary@contoso.com")` at https://docs.microsoft.com/en-us/exchange/client-developer/exchange-web-services/how-to-access-email-as-a-delegate-by-using-ews-in-exchange#create-and-send-an-email-as-a-delegate-by-using-the-ews-managed-api

**Comment by Alino** [comment]
thank you, that works.

here is an example for future visitors:

```typescript
function getFolders() {
  exch.FindFolders(new ews.FolderId(ews.WellKnownFolderName.MsgFolderRoot, new ews.Mailbox(DELEGATED_ADDRESS)), new ews.FolderView(100)).then(res => {
    console.log(res);
    res.Folders.forEach(f => {
      console.log(f.DisplayName, f.Id)
    })
  }).catch(err => console.log(err))
}
```
