### ISSUE TITLE
readMe information is wrong

### ISSUE THREAD

**Issue by jpiepkow** [gautamsi/ews-javascript-api#4]
readMe does not show the correct npm install title.

Shows:
npm install ews-managed-api

Should show:
npm install ews-javascript-api

**Comment by gautamsi** [comment]
Thanks for the catch. updated readme. 

are you using this for anything?

**Comment by jpiepkow** [comment]
No not currently was looking through options for a program I am making currently and came across it.

**Comment by gautamsi** [comment]
let me know if you find any roadblocks and need some info. I can help in getting started

**Comment by jpiepkow** [comment]
For sure, Thanks!
