### ISSUE TITLE
Sending raw SOAP requests via XHRApi

### ISSUE THREAD

**Issue by marcoancona** [gautamsi/ews-javascript-api#407]
I was wondering, @gautamsi , is it possible to send raw requests through the library, taking advantage of the fact that `ews-managed-api` already takes care of all the authentication parts?

I would like to try using the `FindPeople` API, which [is not implemented](https://github.com/gautamsi/ews-javascript-api/issues/253), and it would be convenient to pass [the raw request body](https://docs.microsoft.com/en-us/exchange/client-developer/web-service-reference/findpeople-operation) to an authenticated XHRApi as a workaround. I would be ok with parsing the raw response then.

**Comment by gautamsi** [comment]
I guess then you can just use `request`, `got` or any http client library and parse yourself.

**Comment by marcoancona** [comment]
The tricky think is the authentication (Basic, OAuth, NLTM). What’s the easiest to use the already configured XHRApi module?

**Comment by gautamsi** [comment]
basic and oauth are plain
only ntlm may be issue
