### ISSUE TITLE
Invalid message signature: Basic realm="..."

### ISSUE THREAD

**Issue by bladerunner2020** [gautamsi/ews-javascript-api#409]
Our customer has Exchange Server installed on-prem, ntlm auth.

When we do requests to EWS we get an error: Invalid message signature: Basic realm="mail.domain.com". Any ideas what could be a reason for that?

Kind regards,
Alex

**Comment by gautamsi** [comment]
sorry not much idea about this error. seems like the negotiation is expecting specific realm name.

**Comment by bladerunner2020** [comment]
I managed to repeat this error using Office365 Development Account. When I am trying to connect office365 Exchange with ntlm auth I am getting the same error.

**Comment by gautamsi** [comment]
you can not connect to O365 with ntlm, this is oauth only going forward
