### ISSUE TITLE
Authorisation problem - 401

### ISSUE THREAD

**Issue by Lakshmiganthangithub** [gautamsi/ews-javascript-api#412]
Hello @gautamsi , I tried reaching you through [Gitter](https://gitter.im/gautamsi/ews-javascript-api?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge#) for the below clarification.

Hallo @gautamsi
hier is my code:
var ews = require('ews-javascript-api');
//create ExchangeService object
//var ewsAuth = require("ews-javascript-api-auth");
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2019);
exch.Credentials = new ews.WebCredentials("Username", "Password");
console.log(exch.Credentials);
console.log(exch.Credentials.getPassword());
//set ews endpoint url to use
exch.Url = new ews.Uri("https://xxx.com/EWS/Exchange.asmx"); // you can also use exch.AutodiscoverUrl+
console.log(exch.Url);
console.log(exch.requestedServerVersion);
var attendee =[new ews.AttendeeInfo("[Username@domain.com](mailto:Username@domain.com)")];
console.log(attendee);
//create timewindow object o request avaiability suggestions for next 48 hours, DateTime and TimeSpan object is created to mimic portion of .net datetime/timespan object using momentjs
var timeWindow = new ews.TimeWindow(ews.DateTime.Now, ews.DateTime.Now.AddDays(2));
console.log(timeWindow);
//console.log(GetUserAvailabilityResults);
exch.GetUserAvailability(attendee, timeWindow, ews.AvailabilityData.FreeBusyAndSuggestions)
.then(function (availabilityResponse) {
//do what you want with user availability
console.log('This example is different!');
console.log(availabilityResponse);
}, function(error) {
// Common error handling
console.log(error.responseCode);
console.log(error);
});
I am using an exchange version 2019.Will your code support for this version?
I am getting Soap fault details with error message 401 Unauthorized. Also when I try to print the exchange version (console.log(exch.requestedServerVersion);), I am getting 5 as result. Through further analysis in your code, I could find that enum value 5 corresponds to Exchange2013_SP1.
![68747470733a2f2f66696c65732e6769747465722e696d2f3536316666633833313662366337303839636237323130332f6a7874702f7468756d622f67726166696b2e706e67](https://user-images.githubusercontent.com/113343956/189620079-f81944fa-94b5-4901-80b3-b002bb9ff058.png)

**Comment by kstankov** [comment]
My two cents:
First, add this before setting the URL:
exch.HttpHeaders.Add('X-AnchorMailbox', "Username");
Next, do a resolve on the user, before getting availability.
something like:
await exch.ResolveName(user).then((response) => {...}))

If you are using autodiscovery, you also need to pass the credentials to the auto-discovery service as well

const autod = new ews.AutodiscoverService(config.exchangeVersion || ews.ExchangeVersion.Exchange2019);
autod.Credentials = new ews.WebCredentials(user, password);

**Comment by Lakshmiganthangithub** [comment]
> My two cents: First, add this before setting the URL: exch.HttpHeaders.Add('X-AnchorMailbox', "Username"); Next, do a resolve on the user, before getting availability. something like: await exch.ResolveName(user).then((response) => {...}))
> 
> If you are using autodiscovery, you also need to pass the credentials to the auto-discovery service as well
> 
> const autod = new ews.AutodiscoverService(config.exchangeVersion || ews.ExchangeVersion.Exchange2019); autod.Credentials = new ews.WebCredentials(user, password);

@kstankov Thanks a million for your help. With the first hint I have no problem. But with the second one, we can use await only inside an aync function. I am new to Javascript. Can you please help me with the await keyword?

So, I have changed the code as below,
var ews = require('ews-javascript-api');
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2019);
exch.Credentials = new ews.WebCredentials("Username", "Password");
console.log(exch.Credentials);
console.log(exch.Credentials.getPassword());
**_exch.HttpHeaders.Add('X-AnchorMailbox', "user");_**
//set ews endpoint url to use
exch.Url = new ews.Uri("https://xxx.com/EWS/Exchange.asmx"); // you can also use exch.AutodiscoverUrl+
console.log(exch.Url);
console.log(exch.requestedServerVersion);
var attendee =[new ews.AttendeeInfo("[Username@domain.com](mailto:Username@domain.com)")];
console.log(attendee);
**_async() =>{
await exch.ResolveName("user").then((response) => {});
}_**
//create timewindow object o request avaiability suggestions for next 48 hours, DateTime and TimeSpan object is created to mimic portion of .net datetime/timespan object using momentjs
var timeWindow = new ews.TimeWindow(ews.DateTime.Now, ews.DateTime.Now.AddDays(2));
console.log(timeWindow);
//console.log(GetUserAvailabilityResults);
exch.GetUserAvailability(attendee, timeWindow, ews.AvailabilityData.FreeBusyAndSuggestions)
.then(function (availabilityResponse) {
//do what you want with user availability
console.log('This example is different!');
console.log(availabilityResponse);
}, function(error) {
// Common error handling
console.log(error.responseCode);
console.log(error);
});

**Comment by gautamsi** [comment]
most of the methods in this library return promise. you can use await with this lib. You can use your own async function or async IIFE to use await

**Comment by Lakshmiganthangithub** [comment]
> most of the methods in this library return promise. you can use await with this lib. You can use your own async function or async IIFE to use await

Thanks @gautamsi for your reply. I used async IIFE, but still getting the same error.

var ews = require('ews-javascript-api');
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2019);
exch.Credentials = new ews.WebCredentials("Username", "Password");
console.log(exch.Credentials);
console.log(exch.Credentials.getPassword());
exch.HttpHeaders.Add('X-AnchorMailbox', "user");
//set ews endpoint url to use
exch.Url = new ews.Uri("https://xxx.com/EWS/Exchange.asmx"); 
console.log(exch.Url);
console.log(exch.requestedServerVersion);
**_async() =>{
await exch.ResolveName("GuestUsername").then((response) => {});
}_**
var attendee =[new ews.AttendeeInfo("[GuestUsername@domain.com](mailto:GuestUsername@domain.com)")];
console.log(attendee);
//create timewindow object o request avaiability suggestions for next 48 hours, DateTime and TimeSpan object is created to mimic portion of .net datetime/timespan object using momentjs
var timeWindow = new ews.TimeWindow(ews.DateTime.Now, ews.DateTime.Now.AddDays(2));
console.log(timeWindow);
//console.log(GetUserAvailabilityResults);
exch.GetUserAvailability(attendee, timeWindow, ews.AvailabilityData.FreeBusyAndSuggestions)
.then(function (availabilityResponse) {
//do what you want with user availability
console.log('This example is different!');
console.log(availabilityResponse);
}, function(error) {
// Common error handling
console.log(error.responseCode);
console.log(error);
});

So, my Soap fault details are printed twice. Once with async and ither time with console.log(error). Can we do anything to avoid this soap fault message of 401 unauthorized?

**Comment by gautamsi** [comment]
is your server only using NTLM? that could be one reason why it comes back as 401. 

I do not see the IIFE properly here. when you use await you do not have to use `.then` or `.catch` you use `try...catch`

**Comment by Lakshmiganthangithub** [comment]
True! NTLM. Will raise another issue next week on User availability.
