### ISSUE TITLE
Specify certificate authority while sending request

### ISSUE THREAD

**Issue by DarkSector** [gautamsi/ews-javascript-api#421]
I would like to mimic this process. How can we specify CA certs when sending requests?

```
const https = require('https');
const { cacerts } = require('./local-ca-certs');

https.get(
  {
    hostname: 'example.internal',
    ca: cacerts,
  },
  (res) => {
    // do something with res
  }
);
```

`npm set config ca ./local-ca-certs` doesn't work. In the absence of local certs I encounter `unable to get local issuer certificate`

**Comment by gautamsi** [comment]
have you seen or tried this?
https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs

**Comment by DarkSector** [comment]
Yes! That worked. Thank you. I am going to eventually have to figure out how to bundle certs with the script when I am building for electron.
