### ISSUE TITLE
Appointment.Bind sometimes return null Organizer

### ISSUE THREAD

**Issue by brt-tiep-duong** [gautamsi/ews-javascript-api#423]
`const appt = await Appointment.Bind(service, new ItemId(uniqueId));`

The `appt` in above code sometimes contains null for the Organizer property. Is it observed by anyone? I found similar issue: https://stackoverflow.com/questions/47288978/ews-appointment-organizer-sometimes-empty

**Comment by gautamsi** [comment]
did the resolution work for you as in stackoverflow issue in mentioned?

**Comment by brt-tiep-duong** [comment]
yes, i added the `AppointmentSchema.Organizer` to property set. Issue is not observed so far.
