### ISSUE TITLE
Missing typescript declaration for CreateItem

### ISSUE THREAD

**Issue by bladerunner2020** [gautamsi/ews-javascript-api#427]
Got this error in typescript:
```
Property 'CreateItem' does not exist on type 'ExchangeService'. Did you mean 'CreateItems'?ts(2551)
ExchangeWebService.d.ts(4302, 5): 'CreateItems' is declared here.
```

In JS there are both CreateItem and CreateItems
<img width="1377" alt="image" src="https://github.com/gautamsi/ews-javascript-api/assets/13632647/90bb524f-e626-4901-8153-e14fff5b4ede">

while in typescript declaration there is only CreateItems 
<img width="1331" alt="image" src="https://github.com/gautamsi/ews-javascript-api/assets/13632647/3bfb2603-f6b0-4be1-8a12-4781bd28e51d">

**Comment by bladerunner2020** [comment]
And I believe CreateItems should return `Promise<ServiceResponseCollection< CreateItemResponse>>` rather than `Promise<ServiceResponseCollection<ServiceResponse>>`

**Comment by gautamsi** [comment]
`CreateItem` is marked internal in c# hence it is excluded from the typings. This return type is also based on the c# return type, Although it does not matter as the declaration is missing anyways.
