### ISSUE TITLE
Question: Can we create a new mailbox for an existing AD user using this library? 

### ISSUE THREAD

**Issue by DreamIT1** [gautamsi/ews-javascript-api#432]

**Comment by DreamIT1** [comment]
I don't see this operation in EWS soap documentation also. Any help is appreciated.

**Comment by bladerunner2020** [comment]
EWS doesn't have such feature.

https://stackoverflow.com/questions/25378911/how-to-create-new-mail-account-microsoft-exchange-2013-ews
