### ISSUE TITLE
Convert recurrence to RRule

### ISSUE THREAD

**Issue by julianallchin** [gautamsi/ews-javascript-api#442]
For my application, I need to convert ews.Recurrence to RRule. In order to build the frequency part of the RRule, I need to discriminate between the different recurrence types—i.e. DailyRecurrence, MonthlyRecurrence, etc. In C# there is a .GetType() such as 
```c#
if(app.Recurrence.GetType() == typeof(Recurrence.DailyPattern))
{
    // do something 
}
else if(app.Recurrence.GetType() == typeof(Recurrence.WeeklyPattern))
{
    // do something
}
```
The `.GetType()` does not exist on the javascript ews.Recurrence. There is also a `.ToString()` such as 

```c#
Appointment app = Appointment.Bind(service,id);
string[] split = app.Recurrence.ToString().Split('+');
if (split.Length != 2)
  return;

string pattern = split[1];

switch (pattern)
{
  case "DailyPattern":
    break;

  case "WeeklyPattern":
    break;

  case "MonthlyPattern":
    break;

  case "YearlyPattern":
    break;
}
```

I've been trying to find away around the lack of these functions, including searching for a way to get the recurrence object as an XML string. 

Any advice?

**Comment by gautamsi** [comment]
have you tried `instanceof` operator?

`if(app.Recurrence instanceof Recurrence.DailyPattern)`

**Comment by julianallchin** [comment]
Yes. 
```
TypeError: Right-hand side of 'instanceof' is not an object

      24 |   }
      25 |
    > 26 |   if (recurrence instanceof DailyPattern) {
 ```

**Comment by julianallchin** [comment]
Wait, trying it with `if (recurrence instanceof Recurrence.DailyPattern)` worked. Why is `DailyPattern` not an object but `Recurrence.DailyPattern` is?

**Comment by gautamsi** [comment]
`DailyPattern` is not exported directly, `Recurrence.DailyPattern` is.
