### ISSUE TITLE
Implement: eDiscovery/Compliance operations

### ISSUE THREAD

**Issue by gautamsi** [gautamsi/ews-javascript-api#48]
ExchangeService methods:
- [x] GetDiscoverySearchConfiguration
- [x] GetSearchableMailboxes
- [x] SearchMailboxes
- [x] SetHoldOnMailboxes
- [x] GetHoldOnMailboxes
- [x] GetNonIndexableItemDetails
- [x] GetNonIndexableItemStatistics

**Comment by r1bb3t** [comment]
Would love this implemented in order to find users in litigation hold.

**Comment by r1bb3t** [comment]
Awesome to see this implemented--thank you.  Is there any sample code for using GetSearchableMailboxes by chance?

**Comment by gautamsi** [comment]
still working on last one, then I will provide code sample.

**Comment by gautamsi** [comment]
this is complete now with 0.8 pushed to npm.
 @r1bb3t  try `GetSearchableMailboxes` in Typescript

```ts
service.GetSearchableMailboxes("search term, passing 'null' will return all", false /* set true to expand groups */).then((response) => {
    EwsLogging.Log(response, true, true);
}, (err) => {
    debugger;
    console.log("Error - geting config");
    EwsLogging.Log(err, true, true);
});
```
