### ISSUE TITLE
Cookies Authentication behind TMG - Error when calling GetUserAvailability method

### ISSUE THREAD

**Issue by iguissouma** [gautamsi/ews-javascript-api#5]
Hello, First thank you for this module, 
I'm trying to call GetUserAvailability from meteorjs application (the code is same like in readme file).

I'm getting the following error:

I20151014-18:57:28.056(2)? [ServiceObjectPropertyDefinition.ctor] uri is null or empty
I20151014-18:57:29.245(2)? [ServiceObjectPropertyDefinition.ctor] uri is null or empty
I20151014-18:57:29.246(2)? [ServiceObjectPropertyDefinition.ctor] uri is null or empty
I20151014-18:57:29.247(2)? [ServiceObjectPropertyDefinition.ctor] uri is null or empty
I20151014-18:57:29.247(2)? sending ews request
I20151014-18:57:29.247(2)? { url: 'https://mail.xxxx.com/EWS/Exchange.asmx',
I20151014-18:57:29.247(2)?   headers:
I20151014-18:57:29.247(2)?    { 'Content-Type': 'text/xml; charset=utf-8',
I20151014-18:57:29.248(2)?      Accept: 'text/xml',
I20151014-18:57:29.248(2)?      Authorization: 'Basic aWd1aXNzb3VtYTpA==' },
I20151014-18:57:29.248(2)?   type: 'POST',
I20151014-18:57:29.248(2)?   data: '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="h
ttp://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Vers
ion="Exchange2010"></t:RequestServerVersion><t:TimeZoneContext><t:TimeZoneDefinition Name="UTC" Id="UTC"></t:TimeZoneDefinition></t:TimeZoneContext></soap:Header><soap:Bo
dy><m:GetUserAvailabilityRequest><m:MailboxDataArray><t:MailboxData><t:Email><t:Address>Salle-Pixel@xxxx.com</t:Address></t:Email><t:AttendeeType>Required</t:AttendeeTy
pe><t:ExcludeConflicts>false</t:ExcludeConflicts></t:MailboxData></m:MailboxDataArray><t:FreeBusyViewOptions><t:TimeWindow><t:StartTime>2015-10-14T00:00:00</t:StartTime><
t:EndTime>2015-10-16T00:00:00</t:EndTime></t:TimeWindow><t:MergedFreeBusyIntervalInMinutes>30</t:MergedFreeBusyIntervalInMinutes><t:RequestedView>Detailed</t:RequestedVie
w></t:FreeBusyViewOptions></m:GetUserAvailabilityRequest></soap:Body></soap:Envelope>' }
I20151014-18:57:29.287(2)? Error in calling service, error code:0
I20151014-18:57:29.287(2)? -----------error
I20151014-18:57:29.288(2)? null

When I tied the SoapRequest with another tool I get the followin error:

<?xml version="1.0" encoding="utf-8"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"><s:Body><s:Fault><faultcode xmlns:a="http://schemas.microsoft.com/exchange/services/2006/types">a:ErrorMissingArgument</faultcode><faultstring xml:lang="fr-FR">You must specify TimeZone.</faultstring><detail><m:ErrorCode xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages">5028</m:ErrorCode></detail></s:Fault></s:Body></s:Envelope>

To fix the request soap I have to add like this:

            <t:TimeZone>
                <t:Bias>0</t:Bias>
                <t:StandardTime>
                    <t:Bias>0</t:Bias>
                    <t:Time>02:00:00</t:Time>
                    <t:DayOrder>1</t:DayOrder>
                    <t:Month>3</t:Month>
                    <t:DayOfWeek>Sunday</t:DayOfWeek>
                </t:StandardTime>
                <t:DaylightTime>
                    <t:Bias>0</t:Bias>
                    <t:Time>02:00:00</t:Time>
                    <t:DayOrder>1</t:DayOrder>
                    <t:Month>10</t:Month>
                    <t:DayOfWeek>Sunday</t:DayOfWeek>
                </t:DaylightTime>
            </t:TimeZone>

Do you have any idea how to fix this issue.
thx in advance.

**Comment by gautamsi** [comment]
are you using in Node or requirejs version? 
I tries fresh application with this code. 
1. create new directory 
2. npm install ews-javascript-api
3. create app.js and paste readme code. 
4. change credential and exchange version. 

What exchange version you are using in code? 
What is the version of Exchange you are querying?

**Comment by Martin-Pitt** [comment]
Hi gautamsi, I'm also trying to use this and getting an error: (censored sensitive details where appropriate with 'xxx')

```
$ node .koa.js
[ServiceObjectPropertyDefinition.ctor] uri is null or empty
[ServiceObjectPropertyDefinition.ctor] uri is null or empty
[ServiceObjectPropertyDefinition.ctor] uri is null or empty
[ServiceObjectPropertyDefinition.ctor] uri is null or empty
Launching webserver at localhost:8042
GET /test/
sending ews request
{ url: 'https://outlook.xxx.net/EWS/Exchange.asmx',
  headers: 
   { 'Content-Type': 'text/xml; charset=utf-8',
     Accept: 'text/xml',
     Authorization: 'Basic xxx' },
  type: 'POST',
  data: '<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2013"></t:RequestServerVersion><t:TimeZoneContext><t:TimeZoneDefinition Name="UTC" Id="UTC"></t:TimeZoneDefinition></t:TimeZoneContext></soap:Header><soap:Body><m:GetUserAvailabilityRequest><m:MailboxDataArray><t:MailboxData><t:Email><t:Address>xxx@xxx.net</t:Address></t:Email><t:AttendeeType>Required</t:AttendeeType><t:ExcludeConflicts>false</t:ExcludeConflicts></t:MailboxData><t:MailboxData><t:Email><t:Address>xxx@xxx.net</t:Address></t:Email><t:AttendeeType>Required</t:AttendeeType><t:ExcludeConflicts>false</t:ExcludeConflicts></t:MailboxData></m:MailboxDataArray><t:FreeBusyViewOptions><t:TimeWindow><t:StartTime>2015-10-15T00:00:00</t:StartTime><t:EndTime>2015-10-17T00:00:00</t:EndTime></t:TimeWindow><t:MergedFreeBusyIntervalInMinutes>30</t:MergedFreeBusyIntervalInMinutes><t:RequestedView>Detailed</t:RequestedView></t:FreeBusyViewOptions><t:SuggestionsViewOptions><t:GoodThreshold>25</t:GoodThreshold><t:MaximumResultsByDay>10</t:MaximumResultsByDay><t:MaximumNonWorkHourResultsByDay>0</t:MaximumNonWorkHourResultsByDay><t:MeetingDurationInMinutes>60</t:MeetingDurationInMinutes><t:MinimumSuggestionQuality>Fair</t:MinimumSuggestionQuality><t:DetailedSuggestionsWindow><t:StartTime>2015-10-15T00:00:00</t:StartTime><t:EndTime>2015-10-17T00:00:00</t:EndTime></t:DetailedSuggestionsWindow></t:SuggestionsViewOptions></m:GetUserAvailabilityRequest></soap:Body></soap:Envelope>' }
Error in calling service, error code:401
```

I'm connecting as follows and yes, IT guy says we use Exchange 2013.

```
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);
exch.Credentials = new ews.ExchangeCredentials('xxx@xxx.net', 'xxx!');
exch.Url = new ews.Uri('https://outlook.xxx.net/EWS/Exchange.asmx');
```

**Comment by gautamsi** [comment]
@Martin-Pitt your issue is little different, 401 means there is credential issue, your on-prem server may not be supporting basic authentication. It may be the case that your exchange service is behind ISA/TMG server with form based authentication. 

I have had implementation issue with TimeZone. In my testing, there is requirement to have TimeZoneContext in header or TimeZone in body. It could take me longer to implement TimeZone object due to complexity in calculating current time zone in JavaScript, I decided to pack TimeZoneContext in header hardcoded to UTC until I figure out TimeZone stuff or make it mandatory to initialize timezone manually by client code.

I will have to find on-prem Exchange server to test this again. I have O365 tenant it work perfectly all the time with any server version I specify.

**Comment by iguissouma** [comment]
Hello, 
I installed latest node version.
I followed your instructions:
1. create new directory
2. npm install ews-javascript-api
3. create app.js and paste readme code.
4. change credential and exchange version. 
5. run node app.js

I have the same Error, see the screnn shot.
We are using Exchange 2010.
![2015-10-16_09h44_45](https://cloud.githubusercontent.com/assets/9085108/10536391/edff0784-73ea-11e5-9e25-53e420532b23.png)

**Comment by gautamsi** [comment]
I have to find a server to install Exchange 2010 and test.

can you copy and paste soap xml in Fiddler2 and let me know what error it give? you have to check left panel for errors. 
![fiddler - ews javascript api](https://cloud.githubusercontent.com/assets/5769869/10537589/6c60fdb0-7410-11e5-8cf8-fba39be437ed.JPG)

http://www.telerik.com/fiddler
disable capturing from file menu to prevent fiddler from overwhelming this window with other connections.

**Comment by Martin-Pitt** [comment]
@gautamsi I logged into the web based email (/OWA/) and then fired off successful POST requests with the same soap payload for user availability to the API (/EWS/). So yes, form-based authentication seems to do the trick. How can I use form based authentication with your API?

**Comment by gautamsi** [comment]
I will have to look into it. it looks like some more development time will be needed. will try to work over this weekend.

**Comment by iguissouma** [comment]
I've tested with fiddler, I'm getting 401 error.
![2015-10-16_14h14_11](https://cloud.githubusercontent.com/assets/9085108/10541344/95351190-7410-11e5-817b-52d32e6d9fdf.png)

I'm doing some test with SOAPe v1.0.5.0
I'm getting this error:
![2015-10-16_14h17_50](https://cloud.githubusercontent.com/assets/9085108/10541579/892ba862-7412-11e5-9d1a-19edd93c5ec5.png)

Wehn I check Force Basic authentication, Im getting 401 Error.

![2015-10-16_14h32_54](https://cloud.githubusercontent.com/assets/9085108/10541625/ea4585b4-7412-11e5-91b9-f7a99fca3916.png)

Hope this can help.

**Comment by gautamsi** [comment]
my problem is that it works every time for me:) may be because it is Office 365.
@Martin-Pitt  you may also have issues with authentication.  it could also be the case that EWS is behaving differently with basic auth and with form auth. let me do some testing and try to implement  timezone element instead of timezonecontext to see if it helps.  can you try running again with TimeZone element added? does it work?

**Comment by iguissouma** [comment]
I confirm, it works with office365.

**Comment by iguissouma** [comment]
Hello, Do you have an example how to iterate through availabilityResponse 

.then(function (availabilityResponse) {
                //do what you want with user availability
                console.log('-----------success');
                EwsLogging.Log(availabilityResponse,true,true);
                for (var freeBusyResponse in availabilityResponse.FreeBusyResponseArray) {
                    console.log('test');
                    EwsLogging.Log(freeBusyResponse,true,true);
                }

            }

Im getting only success trace with the above code.
thanks in advance

**Comment by gautamsi** [comment]
GetUserAvailability returns IPromise<GetUserAvailabilityResults>, this is ES6/Typescript class
```` javascript
 class GetUserAvailabilityResults {
    SuggestionsResponse: SuggestionsResponse;
    AttendeesAvailability: ServiceResponseCollection<AttendeeAvailability>;
    Suggestions: Suggestion[];
}


````
checkout my repo ews-javascript-api-demoapps, this has scenarios for getuseravailability
you will need to do some setup. 
* clone
* npm install
* create credential.json file in nodejs directory (where app.js is), this stores user name and password for connection to EWS.
```` json
{
	"userName":"username",
	"password":"password"
}
````
* change email address in two lines in file scenarios/availability1.js (do not build, or change .ts file)
```` js
var attendee1 = new ews_javascript_api_1.AttendeeInfo("gstest@singhs.pro");
var attendee2 = new ews_javascript_api_1.AttendeeInfo("gs@singhspro.onmicrosoft.com");
````
* run following code from nodejs directory
```` js
node app.js --run availability1
````

**Comment by iguissouma** [comment]
thanks.

**Comment by gautamsi** [comment]
I had the opportunity to setup local Exchange server for some other work, Was able to get something for anyone waiting for TMG backed Cookies Authentication. 

I have created a [GIST](https://gist.github.com/gautamsi/4aec3307942de9087e89) to show example. You can use the file "cookiesAuthXHRApi.js" as node module as is or modify to make sure other best practices are followed. This is using library [httpreq](https://github.com/SamDecrock/node-httpreq).

Please make sure to handle any 401 after TMG cookies expires. 

I have also created a [Gist for NTLM authentication](https://gist.github.com/gautamsi/28211eda711e3e7dc04c) see #8  for more detail.

I did test this app.js and made sure it is working before giving example. GetPasswordExpirationDate is the only function I tested, other should work too, let me know if there is any issue. Will work on improving this when I get more time.

**Comment by gautamsi** [comment]
@Martin-Pitt  check previous comment for form based authentication. it should work now for you. There is no FBA for EWS, it is only Basic/NTLM but TMG/ISA does the FBA<--->ntlm/basic/negotiate bridge.
