### ISSUE TITLE
Problem Import eml into Exchange 2013

### ISSUE THREAD

**Issue by Sennar81** [gautamsi/ews-javascript-api#57]
When I try to import an .eml file I get the following error:
[xmldom error]	element parse error: Error: invalid tagName:myaddress@domain.com 
@#[line:6,col:14]
[xmldom error]	element parse error: Error: invalid tagName:myaddress@domain.com 
@#[line:13,col:6]
[xmldom error]	element parse error: Error: invalid tagName:myaddress@domain.com 
@#[line:19,col:33]
[xmldom error]	element parse error: Error: invalid tagName:rpctaddress@domain.com
@#[line:25,col:6]
[xmldom error]	element parse error: Error: invalid tagName:rpctaddress@domain.com
@#[line:27,col:13]
[xmldom error]	element parse error: Error: invalid tagName:CAJGmDoE-Uc8LfFrVg8ryuOu95kzH4TVSMPSkr+hvpL_9sObJ7w@mail.domain.com 
@#[line:54,col:13]
[xmldom error]	element parse error: Error: invalid tagName:myaddress@domain.com  
@#[line:56,col:22]
[xmldom error]	element parse error: Error: invalid tagName:rpctaddress@domain.com
@#[line:57,col:32]
[xmldom warning]	unclosed xml attribute 
@#[line:64,col:23]

My js code is:
fs.open("/tmp/test.eml",'r', function(err, fd) {
  fs.stat("/tmp/test.eml", function(err, stats)
  {

    var bufferSize=stats.size,
      chunkSize=512,
      buffer=new Buffer(bufferSize),
      bytesRead = 0;

    while (bytesRead < bufferSize)
    {
      if ((bytesRead + chunkSize) > bufferSize)
      {
        chunkSize = (bufferSize - bytesRead);
      }
      fs.read(fd, buffer, bytesRead, chunkSize, bytesRead);
      bytesRead += chunkSize;
    }

    var email = new ews.EmailMessage(exch);
    email.MimeContent = new ews.MimeContent("UTF-8", buffer);
    var PR_MESSAGE_FLAGS_msgflag_read = new ews.ExtendedPropertyDefinition(3591, ews.MapiPropertyType.Integer);
    email.SetExtendedProperty(PR_MESSAGE_FLAGS_msgflag_read, 1);
    email.Save(ews.WellKnownFolderName.Inbox);
    console.log(buffer.toString('utf8', 0, bufferSize));
    fs.close(fd);
  });
});

Can someone help me?
Best Regards
Giovanni

**Comment by gautamsi** [comment]
these errors happen when server returned something can not be processed by underlying DOMParser. 

try this and report any further issue.

1  do not pass Buffer, convert to base64 string then pass it. use `utf-8` not `UTF-8` if there is server error about encoding. 
Note:nodejs base64 conversion with encoding uses `utf8` not `utf-8`

2  `email.save` is a promise, use `.then` before processing further.
````typescript
email.save(....).then(()=>{
   //saved
}, (err)=>{
  //error in saving
}); 
````

**Comment by gautamsi** [comment]
above snippet is in typescript

**Comment by gautamsi** [comment]
I just tested this, it works, I see the message getting saved in inbox. slight change from your example 

change `email.MimeContent = new ews.MimeContent("UTF-8", buffer);` to `email.MimeContent = new ews.MimeContent("UTF-8", buffer.toString('base64'));`

make sure you treet save call as promise.
```typescript
email.save(....).then(function(){
   //saved - cleanup code
}, function(err){
  //error in saving - cleanup code
console.log(err);
}); 
```

**Comment by Sennar81** [comment]
It's work, it's fantastic

**Comment by gautamsi** [comment]
great, good to know. Please spread the word if possible.
