### ISSUE TITLE
Availability is using GMT and not leveraging user's current timezone

### ISSUE THREAD

**Issue by jontowles** [gautamsi/ews-javascript-api#58]
It appears that the module is using the server's timezone and not working off the current timezone of the user.

Is this a configuration issue or something more?

**Comment by gautamsi** [comment]
I have not yet figured out to detect current timezone correctly. so defaulted to UTC/GMT. you can assume until further update to TimeZone functionality it will always be UTC.

once I publish beta (complete most functionality, except compliance/discovery) I will focus on improving TimeZone processing. suggestions are welcome based on any node.js module (MIT License preferably).

beta timeframe is not decided right now as I am working on spare time, sometime get more time and sometime not much. It could be end of next month or later (even much sooner).

**Comment by ChMrWang** [comment]
I have a problem here too , I construct a TimeWindow by 
```
var timeWindow = new ews.TimeWindow(
        new ews.DateTime(ews.DateTime.Now.TotalMilliSeconds),
        new ews.DateTime(ews.DateTime.Now.TotalMilliSeconds + ews.TimeSpan.FromHours(24).asMilliseconds())
    );
return exch.GetUserAvailability(attendee, timeWindow, ews.AvailabilityData.FreeBusyAndSuggestions)
        .then(function (availabilityResponse) {
```

and current time is  9/13/2016, 2:05:01 PM , but I found in the log 
```
FreeBusyViewOptions: 
         { __prefix: 't',
           __type: 'FreeBusyViewOptions',
           TimeWindow: 
            { __prefix: 't',
              __type: 'TimeWindow',
              StartTime: '2016-09-13T00:00:00',
              EndTime: '2016-09-14T00:00:00' },
           MergedFreeBusyIntervalInMinutes: '30',
           RequestedView: 'Detailed' },
```

So how could set the time to now bug not '2016-09-14T00:00:00' ?

**Comment by gautamsi** [comment]
I will look into this again before 1.0 release.

**Comment by gautamsi** [comment]
check this: https://stackoverflow.com/questions/8750937/difference-between-a-datetime-object-i-create-and-datetime-now

may not be problem based on official document. 
you want to do it this way now:
```ts
new ews.TimeWindow(ews.DateTime.Now.AddDays(1), ews.DateTime.Now.AddDays(2))
```
