### ISSUE TITLE
Item.ts - SetSubject : Not implemented.

### ISSUE THREAD

**Issue by ervinfetic** [gautamsi/ews-javascript-api#6]
Hi,

First of all I want to say thanks for the great module. I have a little issue, I am getting the following error, Error: Item.ts - SetSubject : Not implemented, when trying to create a new appointment on the calendar. I looked a bit through the code and I saw that this feature is not yet implemented. Any ETA on when we can expect it? 
I am trying to understand what I can do to implement this, in case you don't have time, but it seems fairly complex, any help or notes you might have?

The code in question:

      var appointment = new ews.Appointment(exch);
      appointment.Subject = "Dentist Appointment";
      appointment.Body = "The appointment is with Dr. Smith.";
      appointment.Start = new DateTime(2016, 3, 1, 9, 0, 0);
      appointment.End = appointment.Start.AddHours(2);
      appointment.Save(SendInvitationsMode.SendToNone);

**Comment by gautamsi** [comment]
I will try to fix this soon. by next week if I get some quality time over weekend. 
I have been porting code from ews-managed-api so it is fairly complex. there are some workaround I did which will be difficult to explain. let me see if I can create any notes soon.

**Comment by ervinfetic** [comment]
Great, thanks, if you could look into that, I will also try my best to get more familiar with the code.

**Comment by gautamsi** [comment]
I am working on code updates. Still have too many source files to update. it is like chain, Appointment class calls another class, that calls another class and so on. Will have to update each one of those to be able to test and publish to npm. 

at this time at least 5-6 other files needs to be update, they may require additional files to be update. 

It looks like it will take few more days, probably next Monday.

**Comment by gautamsi** [comment]
Still working
After 4 commits having 49 changed files  with 2,248 additions and 378 deletions; don't think I am even half the way to complete porting Appointment part of code. 
Appointment depends on EmailMessage, EmailMessage reference 5 other classes and so on. 

I have to divert some attention to my other projects. Will try to balance time for sure, not leaving this n side yet:).

**Comment by hazam** [comment]
I pile up con the congrats for the module, really cool.
I'm also trying to create meeting via this lib, and met same limitation.
Can I help with something, testing?

**Comment by gautamsi** [comment]
I have pushed a change which will enable this code to run. There is a slight change in way you will call this in TypeScript. File in test/ManualLiveTesting/app.ts provide more insights. 

```` TypeScript
var exch = new ExchangeService(ExchangeVersion.Exchange2013);
exch.Credentials = new ExchangeCredentials(credentials.userName, credentials.password);
exch.Url = new Uri("https://outlook.office365.com/Ews/Exchange.asmx");
EwsLogging.DebugLogEnabled = true;

var appointment = new Appointment(exch);
appointment.Subject = "Dentist Appointment";
appointment.Body = new MessageBody("The appointment is with Dr. Smith.");
appointment.Start = new DateTime(new Date(2016, 3, 1, 9, 0, 0));
appointment.End = appointment.Start.Add(2, "hour");//based on moment.js pattern
appointment.Save(SendInvitationsMode.SendToNone).then(() => {
    console.log("------------");
}, (ei) => {
    EwsLogging.Log(ei, true, true);
    console.log(ei.stack, ei.stack.split("\n"));
    console.log("------------");
});
````
or in js
````javascript
var ExchangeWebService_1 = require("../../src/js/ExchangeWebService");
var credentials = require("./credentials"); // credential is a json file { username: "username", password: "password" }
var exch = new ExchangeWebService_1.ExchangeService(ExchangeWebService_1.ExchangeVersion.Exchange2013);
exch.Credentials = new ExchangeWebService_1.ExchangeCredentials(credentials.userName, credentials.password);
exch.Url = new ExchangeWebService_1.Uri("https://outlook.office365.com/Ews/Exchange.asmx");
ExchangeWebService_1.EwsLogging.DebugLogEnabled = true;
var appointment = new ExchangeWebService_1.Appointment(exch);
appointment.Subject = "Dentist Appointment";
appointment.Body = new ExchangeWebService_1.MessageBody("The appointment is with Dr. Smith.");
appointment.Start = new ExchangeWebService_1.DateTime(new Date(2016, 3, 1, 9, 0, 0));
appointment.End = appointment.Start.Add(2, "hour");//based on moment.js pattern
appointment.Save(ExchangeWebService_1.SendInvitationsMode.SendToNone).then(function () {
    console.log("------------");
}, function (ei) {
    ExchangeWebService_1.EwsLogging.Log(ei, true, true);
    console.log(ei.stack, ei.stack.split("\n"));
    console.log("------------");
});
````

I did not have time to fix attachment collection, if you try to add any attachment, it will fail or simply does not save attachment, you will see message in debug log about those function not being implemented.

**Comment by gautamsi** [comment]
Attachment collection fixed, you can now also send attachment with EmailMessage - File attachment as well as ItemAttachment works. 
See this issue #11 for details on how to do it, did not have much time to write wiki.
