### ISSUE TITLE
FindFolders not continue when ews return error

### ISSUE THREAD

**Issue by Sennar81** [gautamsi/ews-javascript-api#60]
I'm trying to verify the existence of a mailbox using the function FindFolders.
My code is:

var folderid = new ews.FolderId(ews.WellKnownFolderName.Inbox, new ews.Mailbox("fakemailbox@domain.local"));
service.FindFolders(folderid, new ews.FolderView(10)).then(function(response) {
    console.log("OK");
}, function(error) {
    console.log("ERROR");
});
console.log("CONTINUE");

When the mailbox exists it works great but when the mailbox is not found, no console.log command is executed and the script doesn't continue.

EWS answers correctly this error:

Body: 
   { __prefix: 's',
     FindFolderResponse: 
      { __prefix: 'm',
        __type: 'FindFolderResponse',
        ResponseMessages: 
         { __prefix: 'm',
           __type: 'ResponseMessages',
           FindFolderResponseMessage: 
            { __prefix: 'm',
              __type: 'FindFolderResponseMessage',
              ResponseClass: 'Error',
              MessageText: 'The SMTP address has no mailbox associated with it.',
              ResponseCode: 'ErrorNonExistentMailbox',
              DescriptiveLinkKey: '0',
              MessageXml: 
               { __prefix: 'm',
                 __type: 'MessageXml',
                 Value: 
                  { __prefix: 't',
                    __type: 'Value',
                    Name: 'SmtpAddress',
                    Value: 'fakemailbox@domain.local' } } } } } } }

can you help me? Excuse me for the countless requests and excuse me for my bad English

Best Regards

**Comment by gautamsi** [comment]
from error it seems you are really using a fake mailbox email address as Exchange can not find a mailbox with such email address.  `MessageText: 'The SMTP address has no mailbox associated with it.',`

if you are searching in the mailbox you are currently logging on with, you may just use `service.FindFolders(WellKnownFolderName.Inbox, new FolderView(10))`

try this while I update mailbox.ts with constructor overload. once this bug is closed you no longer have to use extra parameter in `Mailbox`. 2nd parameter is optional which is "SMTP" by default. 

```js
var folderid = new ews.FolderId(ews.WellKnownFolderName.Inbox, new ews.Mailbox("fakemailbox@domain.local","SMTP"));
 service.FindFolders(folderid, new ews.FolderView(10)).then(function(response) {
 console.log("OK");
 }, function(error) {
 console.log("ERROR");
 });
 console.log("CONTINUE");
```

**Comment by Sennar81** [comment]
The same problem I have also by taking the example statements .
It does not run the command console.log ("OK")
------------------------------------------------------------------------------------------------------------------
var ews = require('ews-javascript-api');

var autod = new ews.AutodiscoverService(new ews.Uri("https://exchange.domain.local/autodiscover/autodiscover.svc"), ews.ExchangeVersion.Exchange2013_SP1);
autod.Credentials = new ews.ExchangeCredentials("DOMAIN\\Administrator", "password");

var settings = [
ews.UserSettingName.InternalEwsUrl,
ews.UserSettingName.ExternalEwsUrl,
ews.UserSettingName.UserDisplayName,
ews.UserSettingName.UserDN,
ews.UserSettingName.EwsPartnerUrl,
ews.UserSettingName.DocumentSharingLocations,
ews.UserSettingName.MailboxDN,
ews.UserSettingName.ActiveDirectoryServer,
ews.UserSettingName.CasVersion,
ews.UserSettingName.ExternalWebClientUrls,
ews.UserSettingName.ExternalImap4Connections,
ews.UserSettingName.AlternateMailboxes
];

autod.GetUserSettings(["administrator@domain.local", "fakemailbox@domain.local"], settings).then(function (response) {
    console.log("OK");
}, function (e) {
    console.log("ERROR");
});
console.log("END");
------------------------------------------------------------------------------------------------------------------
DEBUG OUTPUT:
                   { UserSetting: 
                       [ { type: 'StringSetting',
                           Name: 'UserDisplayName',
                           Value: 'Administrator' },
                         { type: 'StringSetting',
                           Name: 'UserDN',
                           Value: '/o=DOMAIN/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=6c4cb52fea7442c8a82c432be7f1b3d5-Administrator' },
                         { type: 'StringSetting',
                           Name: 'CasVersion',
                           Value: '15.00.0847.030' },
                         { type: 'StringSetting',
                           Name: 'ActiveDirectoryServer',
                           Value: 'DC02.domain.local' },
                         { type: 'StringSetting',
                           Name: 'MailboxDN',
                           Value: '/o=DOMAIN/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=68ef66cf-62e7-4fed-acd6-65c8c5e3cdf9@domain.local/cn=Microsoft Private MDB' },
                         { type: 'StringSetting',
                           Name: 'InternalEwsUrl',
                           Value: 'https://exchange.domain.local/EWS/Exchange.asmx' } ] } },
                 { ErrorCode: 'InvalidUser',
                   ErrorMessage: 'Invalid user \'fakemailbox@domain.local\' specified.',
                   RedirectTarget: null,
                   UserSettingErrors: null,
                   UserSettings: null } ] } } } } }
-----------------------------------------------------------------------------------------------------------------------
how can I disable the debug log ?

Best Regards

**Comment by gautamsi** [comment]
you can  put following just after importing the module
```js

```

**Comment by Sennar81** [comment]
I have tried using two users who has mailbox but the result does not change, the console.log("OK") command is not executed.

_DEBUG OUTPUT:_
UserResponses: 
            { UserResponse: 
               [ { ErrorCode: 'NoError',
                   ErrorMessage: 'No error.',
                   RedirectTarget: null,
                   UserSettingErrors: null,
                   UserSettings: 
                    { UserSetting: 
                       [ { type: 'StringSetting',
                           Name: 'UserDisplayName',
                           Value: 'Administrator' },
                         { type: 'StringSetting',
                           Name: 'UserDN',
                           Value: '/o=DOMAIN/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=6c4cb52fea7442c8a82c432be7f1b3d5-Administrator' },
                         { type: 'StringSetting',
                           Name: 'CasVersion',
                           Value: '15.00.0847.030' },
                         { type: 'StringSetting',
                           Name: 'ActiveDirectoryServer',
                           Value: 'DC01.domain.local' },
                         { type: 'StringSetting',
                           Name: 'MailboxDN',
                           Value: '/o=DOMAIN/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=68ef66cf-62e7-4fed-acd6-65c8c5e3cdf9@domain.local/cn=Microsoft Private MDB' },
                         { type: 'StringSetting',
                           Name: 'InternalEwsUrl',
                           Value: 'https://exchange.domain.local/EWS/Exchange.asmx' } ] } },
                 { ErrorCode: 'NoError',
                   ErrorMessage: 'No error.',
                   RedirectTarget: null,
                   UserSettingErrors: null,
                   UserSettings: 
                    { UserSetting: 
                       [ { type: 'StringSetting',
                           Name: 'UserDisplayName',
                           Value: 'Giovanni' },
                         { type: 'StringSetting',
                           Name: 'UserDN',
                           Value: '/o=DOMAIN/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Recipients/cn=9bd802062aab4d259ffa4a003e421ab2-Giovanni' },
                         { type: 'StringSetting',
                           Name: 'CasVersion',
                           Value: '15.00.0847.030' },
                         { type: 'StringSetting',
                           Name: 'ActiveDirectoryServer',
                           Value: 'DC01.domain.local' },
                         { type: 'StringSetting',
                           Name: 'MailboxDN',
                           Value: '/o=DOMAIN/ou=Exchange Administrative Group (FYDIBOHF23SPDLT)/cn=Configuration/cn=Servers/cn=08e24fdc-32c1-49ce-864e-427ca10d269f@domain.local/cn=Microsoft Private MDB' },
                         { type: 'StringSetting',
                           Name: 'InternalEwsUrl',
                           Value: 'https://exchange.domain.local/EWS/Exchange.asmx' } ] } } ] } } } } }

_SCRIPTS OUTPUT:_
bash-4.3$ node test.js 
END
bash-4.3$

**Comment by gautamsi** [comment]
I see there is a problem with autodiscover process when any of the result is null for invalid users, it throws error which cause it to fail silently, fixing in next release.  Will track it in #61. please use workaround for AutoDiscover related error.

I do not find any issue with `FindFolders` call. can you try again this for user which worked in AutoDiscover?

**Comment by Sennar81** [comment]
FindFolders works in tests that you suggested!
I just have to find a way to verify the existence of a mailbox in EWS.

You are very great and very helpful , thank you thank you thank you
Best Regards

**Comment by gautamsi** [comment]
you can use `ResolveName` method to find if there is a ews resource. it returns a Mailbox property if the mailbox exist. 

```js
service.ResolveName("gs@mysupport.in").then(function (response) {
    console.log("OK");
        if(response.Items[0].Mailbox && response.Items[0].Mailbox.MailboxType === ews.MailboxType.Mailbox)
    {
            
        // "response.Items[0].Mailbox.Address"" is is a mailbox
    }
    EwsLogging.Log(response, true, true);
}, function (error) {
    console.log("ERROR");
});
console.log("CONTINUE");
```

msdn docs at https://msdn.microsoft.com/en-us/library/office/dd635548(v=exchg.80).aspx
