### ISSUE TITLE
Typings for NPM Packages

### ISSUE THREAD

**Issue by thomas-hilaire** [gautamsi/ews-javascript-api#64]
Hello,

Looking at the Typescript documentation, it seems that your project lacks of an `index.d.ts` file or of a `typings` property in your `package.json`. See http://www.typescriptlang.org/docs/handbook/typings-for-npm-packages.html

When I try to set the typings with `"typings": "./typings/ExchangeWebService.d.ts"`, I get this error 

> node_modules/ews-javascript-api/typings/ExchangeWebService.d.ts(11133,34): error TS2304: Cannot find name 'UpdateInboxRulesResponse'

Is it an issue or I'm doing that wrong ?

Thanks!

**Comment by gautamsi** [comment]
It could be I missed internal modifier (`/** @internal */`) in one of the file 😞 
just comment the line and you should be fine, I will fix it in next release.
