### ISSUE TITLE
Push notifications

### ISSUE THREAD

**Issue by istersin** [gautamsi/ews-javascript-api#66]
Hi, I see that push subscriptions are not implemented. Any plans on this one? I do know that streaming notifications are a better alternative, but it might be easier to get push notifications working on both basic and NTLM auth, as I see that streaming notifications currently do not work with NTLM.

**Comment by gautamsi** [comment]
For Push notification to work you have to implement public facing receiver (web service end point). 

you can test using Microsoft provided sample of push notification along with web service code. ews-javascript-api should be able to call EWS to set push notification parameters. I have not implemented any generic example of how you can create the compatible service for receiving push notification.

**Comment by istersin** [comment]
Oh I must have missed it. That is all what is needed for the push notification then. As long as you can inform EWS to start a subscription and to report to a certain endpoint that is sufficient. It is up to the user to set up the web service to intercept the notifications from EWS. Thanks for the quick response.

**Comment by gautamsi** [comment]
np. spred the word and blog about if you find it useful.
