### ISSUE TITLE
Work in progress, help/suggestion wanted

### ISSUE THREAD

**Issue by gautamsi** [gautamsi/ews-javascript-api#7]
I have made progress on many items but did not have time to document them. most updates are in dev branch with version pushed out to npm. I am also working on another app ([gautamsi/MailboxApp.js](http://github.com/gautamsi/MailboxApp.js) - based on electron by @atom) which would showcase what is possible with ews-javascript-api. very slow progress though.

Please feel free to guide me for better documentation strategy (API docs generation etc.).

I have started adding jsdoc comment to new files by copying them from original ews-managed-api source file. Most function signature is same hence it is easier in using them directly. Original c# code has xml comment, I have used xmltojsdoc by  @patik. I did modify his demo page at http://patik.github.io/xmltojsdoc/ to http://gautamsi.github.io/xmltojsdoc/indexAuto.html, benefit? added macro to perform paste, convert and then copy to clipboard so that workflow is like 
1. copy xml doc in visual studio (or any editor)
2. switch to my indexAuto.html
3. paste in ts file

now I am looking to build API pages any suggestion to generate .md page based on jsdoc comments? I can then modify samples in the page for everyone to use. 

any takers for MailboxApp.js frontend? meaning if you can help with creating a nice GUI (ref [github.com/nylas/N1](http://github.com/nylas/n1)), I can plugin ews-javascript-api to talk to Exchange/Office365. If anyone can help with an n1 plugin modal where data can be stored locally in sqlite, (no sync-server needed), this repo can be used to sync,update mailbox using EWS (only for Exchange/O365 mailboxes).

**Comment by kkontosis** [comment]
Hello Gautam,
I've been using your library to connect with EWS and I was able to successfully list folder items. Thanks for sharing! I have a question about the source:
I was comparing your source to OfficeDev/ews-managed-api. I notice that instead of using parseFromXML you are implementing a family of parseFromJson functions. I also see that the OfficeDev compatible .treeWalker and APIs in EwsXmlReader.ts is disabled. Why did you chose to do it this way?
Best,
Kimon

**Comment by gautamsi** [comment]
First of all I thanks for taking a look here. 

When I started working on this source, First item I chose was AutoDiscover. it was specific and fairly small SOAP response to parse. Used ParseFromXML (LoadFromXML, ReadAttributesFromXMl etc.). It was tedious and pain to convert recursively, XML is not native to JavaScript and had to do multiple round of testing and debugging to work through. Also needed to use external library to parse which did not have compatible methods to XMLReader in c#. 

Luckily I saw OfficeDev source having LoadFromJson methods all over, looked like they were adding json based payload in addition toXML/SOAP for next version (2016). it was fairly straight forward for me and less testing. 

Problem: I had to figure out how to get json form EWS, EWS in Office 365 did not expose this as library was still under development. Suddenly Exchange team announced that they will move to REST based API instead of EWS/SOAP (apart from JSON effort they put in source). They also removed all traces of LoadFromJson in OfficeDev/ews-managed-api, officedev/ews-managed-api@31951f456519786e41232fa9ff6a3ab20b56cac3 being last commit with LoadFromJson and other Json references. Next commit officedev/ews-managed-api@a0e0d52745487d1de35694ec04f43b53db603cbf removed all json support. But I knew what matters to me. 

I used small library (xmldom) to use DOMParser in node (in browser it is available natively) to convert returned XML to XMLDocument, then wrote small function to convert this to specific format of JavaScript object (similar to Json formatting) 

This helped me just copy and paste LoadFromJson (from specific commit) with little to no modification. Enabled rapid testing/validation. 

I am not using .xxxToJson methods as there is no support for Json in ews.

hope it explains tree-walker and EwsXMLReader api suppression

**Comment by gautamsi** [comment]
There are still many small items i miss every time in rapid convert, writing Enum value as string, which gets caught time to time in testing.

**Comment by philberg** [comment]
Hi @gautamsi
 
We've been looking into this library, as well as the C# and Java implementations by Microsoft, and we are trying to understand why the Microsoft libraries are around 50k lines of code.  I was under the impression that the ews-managed-api was just a thin wrapper around the soap/XML, but it seems crazy to me that would require so much code.  Am I missing something?

Thanks!

**Comment by gautamsi** [comment]
it is still a wrapper around SOAP, but the permutation and combination of each SOAP operation is so large, they have to have to wrap almost each element in its own class. If you see Web Service reference at https://msdn.microsoft.com/EN-US/library/office/aa580675(v=exchg.150).aspx, it has more than 1400 elements. most of them have their own class. each one has to write XML data in SOAP in specific order. 

I started with code organization based on [EWS Operations ](https://msdn.microsoft.com/EN-US/library/office/bb409286(v=exchg.150).aspx) Later I realized that there are so many combinations and having to hand code soap data will be error prone and difficult to port. I had to switch back to how c# code is organized, each class has to be implemented. Sometime there are 10-20 classes have to be completed to finish implementing one EWS call/operation like FindItems, or GetUserAvailability.

**Comment by philberg** [comment]
@gautamsi got it.  If you were to write a wrapper to use in node.js only, that you intended to use for your own project, but not necessarilry make available as an ews-managed-api equivalent library, would you do the same thing, and would the same logic apply?  Or would it make sense to just write a thing SOAP/XML wrapper?

**Comment by gautamsi** [comment]
If I need to get very specific set of data form EWS, lets say user availability, or resolve names using ews; I would just use specific SOAP data and some variable in there. no need to use full library. 

If I have to create email client, or have need to get attachments, meeting, appointments, create meetings, custom header values, delete items, move items, respond to meeting requests etc, will definitely need something like this library.

**Comment by gautamsi** [comment]
You can use of Microsoft provided  [EWS Operations](https://msdn.microsoft.com/EN-US/library/office/bb409286(v=exchg.150).aspx) they have example query as well as results. Keep in mind, when parsing results you may get different results based on Exchange version you specify in request.

**Comment by laeeq** [comment]
@gautamsi Is this api only supported by JS on Windows systems? I see you are using .net objects like DateTime etc. Is it possible to use this API by JS (node.js) on Linux systems?

**Comment by philberg** [comment]
@gautamsi can you think of any API or APIs in particular that will have different responses based on the exchange server version?

**Comment by gautamsi** [comment]
@laeeq  nothing is Windows specific, all works and tested on Mac. I have not tested on Linux (actually ran this on Raspbian for demoing an IOT scenario), it should work there too. node.js is only requirement. some third party libraries are also used to complement/simulate Browser objects like DOMParser, XHR, they are also MIT licensed as well as platform independent. 

DateTime is Class specific to this library to provide some of c# compatible function calls, created as wrapper on top of Moment js. I have to refine few members to match c# counterpart.

**Comment by gautamsi** [comment]
@philberg it may not have different response but error out if you are trying to access some operation not available in version like ArchiveItem operation with header requesting Exchange 2007/2010 as version.

**Comment by gautamsi** [comment]
closing this as I was able to invest time and work on bugs/features. please feel free to comment on this thread for help and how to topics.
