### ISSUE TITLE
Bug: Autodiscover GetUserSettings does not return descriptive errors

### ISSUE THREAD

**Issue by gautamsi** [gautamsi/ews-javascript-api#70]
based on @jackiehluo's comment on  #23, need to add descriptive errors when there is issue in completing the request.

**Comment by jackiehluo** [comment]
@gautamsi Yes, that would be super helpful overall! In general, I've found that a lot of my failed requests just fail silently or return `undefined`, which makes it hard to debug.

**Comment by gautamsi** [comment]
I have checked my code, Autodiscover errors are not corrctly thrown. I have already fixed ExchangeService code to properly return error in case of failures.

**Comment by gautamsi** [comment]
autodiscover is re-written, this should be non-issue now. reopen if needed
