### ISSUE TITLE
ews.Folder.Bind(exch, ews.WellKnownFolderName.Inbox) fails

### ISSUE THREAD

**Issue by rousselle** [gautamsi/ews-javascript-api#71]
I'm trying to get ews.Folder.Bind(exch, ews.WellKnownFolderName.Inbox) to work. 

The first thing I ran into was a failed assert at https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Core/Responses/ServiceResponse.ts#L236. That is supposed to detect when a subclass has not implemented the pure virtual method. The error message led me to https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Core/Responses/GetFolderResponse.ts#L38 where the super class method is explicitly called. I commented this line out.

Now I am getting as far as https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Core/EwsServiceJsonReader.ts#L45 which is

serviceObject = getObjectInstanceDelegate(service, typeName || key);

That is being called with service =

```js
ExchangeService {
  requestedServerVersion: 4,
  timeZone: TimeZoneInfo { offset: 0 },
  XHRApi: null,
  url: null,
  unifiedMessaging: null,
  renderingMode: 0,
  targetServerVersion: null,
  ImpersonatedUserId: null,
  PrivilegedUserId: null,
  ManagementRoles: null,
  PreferredCulture: null,
  DateTimePrecision: 0,
  FileAttachmentContentHandler: null,
  Exchange2007CompatibilityMode: false,
  TraceEnablePrettyPrinting: true,
  Credentials:
   ExchangeCredentials {
     UserName: 'test@exchange.company.com',
     setPassword: [Function],
     getPassword: [Function] },
  Url:
   Uri {
     m_scheme: 'https',
     url: 'https://us.exg7.exghost.com/Ews/Exchange.asmx' },
  httpResponseHeaders: {},
  ServerInfo:
   ExchangeServerInfo {
     MajorVersion: 15,
     MinorVersion: 1,
     MajorBuildNumber: 466,
     MinorBuildNumber: 33,
     VersionString: 'V2016_01_06' } }

```

and type = "Folder".

That takes me to https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Misc/DelegateTypes.ts#L15 which does not return. I don't know enough TypeScript to be sure what is going on there. It looks like it's trying to do a table lookup. I suspect that something is not initialized, which is why https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Core/Responses/GetFolderResponse.ts#L38 was set up to cause the assertion failure

If you could suggest a work-around I'd appreciate it greatly, I'm trying to do a findItems on the folder passing a filter to get all the emails between two dates. If you know of any way to accomplish this without the bind that would be helpful.

**Comment by gautamsi** [comment]
I see what is happening. 

https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Core/Responses/GetFolderResponse.ts#L38  is just a copy paste from original repo, I should have commented that anyways. 

I have to fix lexical scope of `this.GetObjectInstance` (https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Core/Responses/GetFolderResponse.ts#L45) with `this.GetObjectInstance.bind(this)`. similar instance will also have to be fixed.  this function is being called from Promised code, gets different `this`. will fix it soon.

**Comment by rousselle** [comment]
I changed GetFolderResponse.ts:45 as you suggested above. It resolved the problem. That is, my call to ews.Folder.bind is now returning a folder.

Once I get the folder I'm trying to do:

folder.FindItems(filter, view)

This is resulting in a call to the error callback that passes:

[TypeError: Cannot read property 'WriteAttributesToXml' of null]

Do you know what might be causing this? Looking at the code, I can't tell where it's coming from. My first thought is to find all instances of something.WriteAttributesToXml() and put logging around them. Is there any better way to debug this?

Here is how I'm building the filter:

```js

    var startDate = new ews.DateTime(2016,7,1); //Year, month, day
    var endDate = new ews.DateTime(2016,8,1);
    var greaterThanfilter = new ews.SearchFilter.IsGreaterThanOrEqualTo(
        ews.EmailMessageSchema.DateTimeReceived, startDate);

    var lessThanfilter = new ews.SearchFilter.IsLessThan(
        ews.EmailMessageSchema.DateTimeReceived, endDate);

    var filter = new ews.SearchFilter.SearchFilterCollection(ews.LogicalOperator.And, greaterThanfilter, lessThanfilter);

    var view = new ews.ItemView(100);

```

Does that look correct?

Thanks for your help.

**Comment by gautamsi** [comment]
if you are using visual studio code, you can debug it with All Exception option turned on. it will break on where is it trying to call. I am also looking into it.

**Comment by gautamsi** [comment]
can you try these changes

`new DateTime("2016-07-01");` notice date time format string. it is moment date format, ISO parts work best.
also change SearchFilterCollection constructor parameters, params is not used for some reason, it is easier in javascript to pass array than in c# so I stick to this signature. 

```js
new ews.SearchFilter.SearchFilterCollection(ews.LogicalOperator.And, [greaterThanfilter, lessThanfilter]);
```

full change from your example
```js
var startDate = new ews.DateTime("2016-07-01"); //Year, month, day
var endDate = new ews.DateTime("2016-08-01");
var greaterThanfilter = new ews.SearchFilter.IsGreaterThanOrEqualTo(
    ews.EmailMessageSchema.DateTimeReceived, startDate);

var lessThanfilter = new ews.SearchFilter.IsLessThan(
    ews.EmailMessageSchema.DateTimeReceived, endDate);

var filter = new ews.SearchFilter.SearchFilterCollection(ews.LogicalOperator.And, [greaterThanfilter, lessThanfilter]);

var view = new ews.ItemView(10);
```

let me know how it went.
