### ISSUE TITLE
Show changeType from SyncFolderHierarchy

### ISSUE THREAD

**Issue by jackiehluo** [gautamsi/ews-javascript-api#72]
Does this API support `changeType` for `FolderChange`? I saw that the EWS docs say to expect a string ("Create", "Update", "Delete"), but I'm just getting `0` for all of them—does that just mean "Create"?

**Comment by gautamsi** [comment]
It does provide correct ChangeType. Use following example to test. once it is running it will keep requesting changes every 30 seconds. in between you can try creating a test "Folder", move a test folder, delete a test folder. in case you are wondering about the items, you want to use `SyncFolderItems` instead.

```js
var ews = require("ews-javascript-api");
var service = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010_SP1);
service.Credentials = new ews.ExchangeCredentials("userName", "password"); //change username and password
service.Url = new ews.Uri("https://outlook.office365.com/Ews/Exchange.asmx");
ews.EwsLogging.DebugLogEnabled = false;
var count = 0;
var syncstate = null;
//first sync
service.SyncFolderHierarchy(ews.PropertySet.IdOnly, syncstate).then(function (folderChangeList) {
    syncstate = folderChangeList.SyncState;
    console.log("success - fist sync");
    ews.EwsLogging.Log(folderChangeList, true, true);
    setTimeout(syncFolderHierArchy, 30000);
}, function (err) {
    debugger;
    console.log("Error - first sync");
    ews.EwsLogging.Log(err, true, true);
});
function syncFolderHierArchy() {
    service.SyncFolderHierarchy(ews.PropertySet.IdOnly, syncstate).then(function (folderChangeList) {
        syncstate = folderChangeList.SyncState;
        console.log("success - " + (count++) + "sync");
        ews.EwsLogging.Log(folderChangeList, true, true);
        setTimeout(syncFolderHierArchy, 30000);
    }, function (err) {
        debugger;
        console.log("Error - " + (count++) + "sync");
        ews.EwsLogging.Log(err, true, true);
    });
}

```

**Comment by jackiehluo** [comment]
@gautamsi I am getting `ChangeType` in my responses—my question, I guess, is whether `ChangeType: 0` corresponds to "Create"!

**Comment by gautamsi** [comment]
yes it does, this is Enum value. 

https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Enumerations/ChangeType.ts

```ts
export enum ChangeType {
    Create = 0,
    Update = 1,
    Delete = 2,
    ReadFlagChange = 3
}
```

you can get corresponding string value by using `ews.ChangeType[changetype variable or 0]`

**Comment by gautamsi** [comment]
EWS SOAP operations return string representation of internal Enumeration value. it gets deserialized into ews object enum value which is 0 for `Create` and so on.

**Comment by jackiehluo** [comment]
Got it, that's super helpful! Thanks!
