### ISSUE TITLE
Autodiscover url giving error

### ISSUE THREAD

**Issue by alkasain** [gautamsi/ews-javascript-api#73]
Hi Gautam,

I have to autodiscover exchange url so using below code and getting nothing in response:

code used:
var autod = new ews.AutodiscoverService(ews.ExchangeVersion.Exchange2010); 

when I use hardcoded url then its working fine:

var autod = new ews.AutodiscoverService(new ews.Uri("https://autodiscover-s.outlook.com/autodiscover/autodiscover.svc"), ews.ExchangeVersion.Exchange2010);

Any help would be highly appreciated.

**Comment by gautamsi** [comment]
you have to set `<AutodiscoverService>.RedirectionUrlValidationCallback` for this. by default Autodiscover [prevents redirection](https://msdn.microsoft.com/en-us/library/office/jj220499(v=exchg.80).aspx), you can override by setting this delegate. 

```js
autod.RedirectionUrlValidationCallback = function (url){
//validate if redirection is valid and not malicious, you can also just check for https:// 
// url parameter is a string. 
if(valid(url)){
    return true;
}
    return false;
}
```

**Comment by gautamsi** [comment]
above fix was for error with message: `Autodiscover redirection is blocked for url: https://autodiscover-s.outlook.com/autodiscover/autodiscover.svc`

let me know if you faced any other issues

**Comment by alkasain** [comment]
I am already setting this like below:
autod.CallRedirectionUrlValidationCallback = function() {
                    return true;
                }

but response  is undefined.

**Comment by gautamsi** [comment]
Which domain you are trying? Can you send me full log (after stripping 'Authorization' header) to my contact email address.

Is autodiscover.domain.com for your domain published on dns? Please send me your domain name on my email as well.

**Comment by alkasain** [comment]
one quick query - does this module works for on-premise exchange??
As for one domain its working and for another domain(on-premise) its not working.

**Comment by gautamsi** [comment]
Yes it does, if you know exchange server url you simply use it. If you want autodiscover to work, you need autodiscover dns records. SRV records do npt work yet. Only autodiscover.domain.com cname would work. On premises exchange usually skips inter dns cname record and use SRV records.

**Comment by alkasain** [comment]
I am sending you an email on your gmail id for domain and logs.

**Comment by LohithBlaze** [comment]
Hi,

Is this fixed now?? we are also facing the same issue.

Thanks,
Lohith

**Comment by gautamsi** [comment]
not really had time to test this one. can you try ews-javascript-api@next package (dev build) and report any new error? have fixed few things but could not test this one.

**Comment by LohithBlaze** [comment]
can you let me know when the next build is releasing ?? 

Thanks,
Lohith

**Comment by gautamsi** [comment]
autodiscover is re-written in #324 , should not be facing this issue anymore,
