### ISSUE TITLE
Unable to fetch Calendar body

### ISSUE THREAD

**Issue by karan-jaryal** [gautamsi/ews-javascript-api#74]
var exch = getExchangeObject(),
    calenderFolderId =  new ews.FolderId(ews.WellKnownFolderName.Calendar,new ews.Mailbox("testcal@xyz.com"));  

//console.log(calenderFolderId);
    exch.FindAppointments(calenderFolderId,
        new ews.CalendarView(ews.DateTime.Now.Add(-5),
            new ews.DateTime(ews.DateTime.Now.TotalMilliSeconds + ews.TimeSpan.FromHours(192).asMilliseconds())))
        .then(function (params) {
              var propSet = new ews.PropertySet(ews.BasePropertySet.IdOnly);

```
          propSet.Add(ews.BasePropertySet.IdOnly);
                propSet.Add(ews.AppointmentSchema.Subject);
                propSet.Add(ews.AppointmentSchema.Body);
                propSet.Add(ews.AppointmentSchema.Start);
                propSet.Add(ews.AppointmentSchema.End);
                propSet.Add(ews.AppointmentSchema.Location);
                propSet.Add(ews.AppointmentSchema.RequiredAttendees);
                propSet.Add(ews.AppointmentSchema.OptionalAttendees);
        var parseData = JSON.parse(stringify(params));
        //console.log('Items Data', parseData);
        exch.LoadPropertiesForItems(params, propSet)
        .then(function(data){
            console.log("Getting data")
             console.log('Items Data', data);
        }).catch(function(err){
            console.log(err);
        });

        console.log(parseData.items[0].propertyBag.properties.objects);
```

I am unable to fetch body using LoadPropertiesForItems its giving me error:"The collection is empty."

**Comment by gautamsi** [comment]
I have fixed your example. 

- Collection is empty - due to no results in `FindAppointments` result. You also had to pass params.Items and not params in `LoadPropertiesForItems` that was other reason for collection is empty error. you should check `params.Items.length >0` before you call `LoadPropertiesForItems`.
- DateTime addition is Moment based, you can use milliseconds format or `.Add(amount,unit)` where is unit is second, hour, month etc.
- the promise library I am using is based on A+ formaty (WinJS or Q), it is not compatible with the `.catch()` call.
Properties and members are based on C# counter part EWS managed API, most properties are pascal cased not camel.  There are camel cased private properties (not really a private in javascript) which should not be used. 
- You can not use `propSet.Add(ews.BasePropertySet.IdOnly);` not compatible with function signature. Parameter validation in some of the methods are not done due to nature of c# library compile time error checking. TypeScript provide same when you use type definitions.
- you can use typescript definitions inside Visual Studio Code with .js file. it will provide intellisense, thus avoiding spelling and case errors.


```js
var exch = getExchangeObject(),
calenderFolderId = new ews.FolderId(ews.WellKnownFolderName.Calendar,new ews.Mailbox("testcal@xyz.com"));

//console.log(calenderFolderId);
exch.FindAppointments(calenderFolderId,
    new ews.CalendarView(ews.DateTime.Now.Add(-5, "month"),
        new ews.DateTime(ews.DateTime.Now.TotalMilliSeconds + ews.TimeSpan.FromHours(192).asMilliseconds())))
    .then(function (params) {
        var propSet = new ews.PropertySet(ews.BasePropertySet.IdOnly);

        //propSet.Add(ews.BasePropertySet.IdOnly);
        propSet.Add(ews.AppointmentSchema.Subject);
        propSet.Add(ews.AppointmentSchema.Body);
        propSet.Add(ews.AppointmentSchema.Start);
        propSet.Add(ews.AppointmentSchema.End);
        propSet.Add(ews.AppointmentSchema.Location);
        propSet.Add(ews.AppointmentSchema.RequiredAttendees);
        propSet.Add(ews.AppointmentSchema.OptionalAttendees);
        //var parseData = JSON.parse(stringify(params));
        ews.EwsLogging.DebugLog(params, true, true);
        exch.LoadPropertiesForItems(params.Items, propSet)
            .then(function (data) {
                console.log("Getting data")
                console.log('Items Data', data);
                console.log(params.Items[0].PropertyBag.Properties.Items);
            }, function (err) {
                console.log(err);
            });
    }, function (err) {
        console.log(err);
    });
```

**Comment by karan-jaryal** [comment]
Hi gautamsi,
calenderFolderId = new ews.FolderId(ews.WellKnownFolderName.Calendar,new ews.Mailbox("testcal@xyz.com")),
 in the above code I am entering wrong calendar url ,now i want to catch the error . Please let me know how can I track this.

**Comment by gautamsi** [comment]
In the promise `request.then(function(successresult){},function(err){/* catch here with err, it should be some ServiceException class with appropriate error */});`

**Comment by karan-jaryal** [comment]
Hi gautamsi,
var exch = getExchangeObject(),
calenderFolderId = new ews.FolderId(ews.WellKnownFolderName.Calendar,new ews.Mailbox(CalendarURL));

//console.log(calenderFolderId);
exch.FindAppointments(calenderFolderId,
    new ews.CalendarView(ews.DateTime.Now.Add(-5, "month"),
        new ews.DateTime(ews.DateTime.Now.TotalMilliSeconds + ews.TimeSpan.FromHours(192).asMilliseconds())))
    .then(function (params) {
        var propSet = new ews.PropertySet(ews.BasePropertySet.IdOnly);

        //propSet.Add(ews.BasePropertySet.IdOnly);
        propSet.Add(ews.AppointmentSchema.Subject);
        propSet.Add(ews.AppointmentSchema.Body);
        propSet.Add(ews.AppointmentSchema.Start);
        propSet.Add(ews.AppointmentSchema.End);
        propSet.Add(ews.AppointmentSchema.Location);
        propSet.Add(ews.AppointmentSchema.RequiredAttendees);
        propSet.Add(ews.AppointmentSchema.OptionalAttendees);
        //var parseData = JSON.parse(stringify(params));
        ews.EwsLogging.DebugLog(params, true, true);
        exch.LoadPropertiesForItems(params.Items, propSet)
            .then(function (data) {
                console.log("Getting data")
                console.log('Items Data', data);
                console.log(params.Items[0].PropertyBag.Properties.Items);
            }, function (err) {
                console.log(err);
            });
    }, function (err) {
        console.log(err);
    });

I have looped over the above code and passing CalenderURL one by one using for loop.
Sometime it finishes completely and sometime it stuck in any of CalenderURL(any random  CalendarURL not specific).
Note: This issue I am facing when I deployed my code on RackSpace server(linux server).On my local system it run fine.

**Comment by gautamsi** [comment]
`CalendarURL` - this is email address of the mailbox, right? Do you get any error?

**Comment by karan-jaryal** [comment]
Yes it's email address of mailbox.No it get stuck in servicerespone.ts present in js/core/responses.

**Comment by gautamsi** [comment]
it works fine for me. can you find a scenario in which this would get stuck or sure?

sometime Exchange services are degraded in O365 which may affect ews calls.

**Comment by karan-jaryal** [comment]
Is there any issue of linux server?

**Comment by gautamsi** [comment]
I have not tested on Linux. should not have any issue as it is nodejs only.

**Comment by karan-jaryal** [comment]
Hi gautamsi i have stuck in an issue  using LoadPropertiesForItems attaching screenshot i loads 5 items successfully but it get stucked in 6 th item due to an error and it doesn't response back .I need a response back so i can continue my proccess.Kindly help me as it has been deployed on production level.[
![calendar-items](https://cloud.githubusercontent.com/assets/20456398/26738934/a48bd0d6-47ed-11e7-8a4d-282f295063e7.PNG)
](url)

**Comment by gautamsi** [comment]
I need to understand the repro steps, ping me on gitter, I can help you over chat

**Comment by karan-jaryal** [comment]
Hi Gautam,
Can we have chat tomorrow according to your suitable IST time.

**Comment by gautamsi** [comment]
ping me on Gitter after 12pm IST.

**Comment by gautamsi** [comment]
reopen if still an issue
