### ISSUE TITLE
Mail Update: Error handling is only valid for singleton request

### ISSUE THREAD

**Issue by MarcelCremer** [gautamsi/ews-javascript-api#76]
Hello everyone,

when I try to update an email received by FindItems and LoadPropertiesForItems afterwards, I get the error

`[MultiResponseServiceRequest.Execute] ServiceErrorHandling.ThrowOnError error handling is only valid for singleton request`

My code is pretty straight forward:
```
[...]
item.IsRead = true;
item.Update(ews.ConflictResolutionMode.AlwaysOverwrite).then(function()
{
 console.log("Cleared!");
}, function(error){console.log(error)});
```

Shouldn't be then or error called in any case (how could someone make some proper error handling if not)? Do you see something strange about my code? The request is attached.
[error.txt](https://github.com/gautamsi/ews-javascript-api/files/370921/error.txt)

Best Regards
Marcel

**Comment by gautamsi** [comment]
commit 4a4c3e1dd1ac71e493a5c248e5da34044b6e2d20 fixes this, incorrect label as issue 77. 

try following example, this just toggles the read status (TypeScript)

```ts
service.FindItems(WellKnownFolderName.Inbox, view)
    .then((response) => {
        EwsLogging.Log(response.Items[0].Id, true, true);
        EwsLogging.Log(response.TotalCount, true, true);
        let item = response.Items[0];
        console.log("updating item with itemid: " + item.Id.UniqueId);
        (<EmailMessage>item).IsRead = !(<EmailMessage>item).IsRead;
        item.Update(ConflictResolutionMode.AutoResolve)
            .then(() => {
                console.log("updated");

            }, function (error) {
                if (error) {
                    console.log(error)
                }
            });        
    }, function (error) {
        if (error) {
            console.log(error)
        }
    });
```

**Comment by gautamsi** [comment]
update to 0.5.2 from npm.

**Comment by MarcelCremer** [comment]
Awesome, that works like a charm. Thank you very much for your help :)
