### ISSUE TITLE
AutodiscoverUrl not Implemented

### ISSUE THREAD

**Issue by alkasain** [gautamsi/ews-javascript-api#77]
Hi Gautam,

We need to use AutodiscoverUrl feature with srv lookup. Please let us know if you have any plans to implement this feature.

Thanks,
Alka Saini

**Comment by regimbal93** [comment]
When I use exch.AutodisoverUrl instead of exch.Url I get the following error for ExchangeServices:
[TypeError: Cannot read property 'AbsoluteUri' of undefined]

Am I not declaring AutodiscoverUrl properly?

**Comment by gautamsi** [comment]
autodiscover is re-written #324, try latest dev build using `@next` tag on npm.

this includes SRV lookup. Will be publishing the SCP lookup later
