### ISSUE TITLE
How can I disable request logging?

### ISSUE THREAD

**Issue by qcom** [gautamsi/ews-javascript-api#79]
I noticed `DebugLogEnabled` is hard coded to `true`:
https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/Core/EwsLogging.ts#L19

Can this be disabled without rebuilding?

**Comment by gautamsi** [comment]
Use `ews.EwsLogging.DebugLogEnabled = false` right after `var ews = require('ews-javascript-api');` statement.

**Comment by qcom** [comment]
I'm not very familiar with TypeScript but this should have been clear as day!

**Comment by qcom** [comment]
A separate issue perhaps, but is it possible to control what gets logged?

For example, enable request logging but disable full response body printing.
