### ISSUE TITLE
NTLM authentication

### ISSUE THREAD

**Issue by McGern** [gautamsi/ews-javascript-api#8]
Hi,

(Think this is a feature request).

Was trying to use this framework which looks really nice, but discovered that the exchange server I am using is configured for NTLM authentication.

I used a nodejs package https://github.com/tcr/node-ntlm where the demonstration worked when I tried it by adding simple EWS SOAP xml to the body of the second request (after the challenge).

I tried to have a look at the code for the EWS to see if I could implement it, but became quite lost as my node skills aren't up there yet, and got as far as seeing that Basic authentication is used.

Thanks,
Jarrod

**Comment by gautamsi** [comment]
I got something for you :)

I was not able to use node-ntlm lib you pointed, but I was able to use another library [httpntlm](https://github.com/SamDecrock/node-http-ntlm) it worked well for me. 

I have created a [Gist](https://gist.github.com/gautamsi/28211eda711e3e7dc04c) to show example. You can use the file "ntlmXHRApi.js" as node module as is or modify to make sure other best practices are followed. 

I have also added sample app.js file on how to use this XHR shim with ews-javascript-api

I did test this app and made sure it is working before giving example, GetPasswordExpirationDate is the only function I tested, other should work too, let me know if there is any issue. Will work on improving this when I get time.

**Comment by McGern** [comment]
Thanks very much for that, I really appreciate the time you took to get this working.

I got your demo code working and managed to call a couple of other services e.g. GetUserAvailability

Looking forward to the rest of the library getting completed and documented. If I can find some time to help out, I will do what I can.
