### ISSUE TITLE
Save Item into ImpersonatedUserId

### ISSUE THREAD

**Issue by Sennar81** [gautamsi/ews-javascript-api#82]
Hi,
I can't save an e-mail into another mailbox.
I receive the following error message:
**## MultiResponseServiceRequest.Execute] ServiceErrorHandling.ThrowOnError error handling is only valid for singleton request**

My code is:
**## var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013)
  exch.XHRApi = ntlmXHRApi
  exch.Credentials = new ews.ExchangeCredentials(config.username, config.password)
  // ews.EwsLogging.DebugLogEnabled = false // turn off logging
  exch.ImpersonatedUserId = new ews.ImpersonatedUserId(ews.ConnectingIdType.SmtpAddress, 'usersmail@mail.com')
var email = new ews.EmailMessage(exch);
......
email.save(ews.WellKnownFolderName.Inbox)).then(function(){
   //saved - cleanup code
}, function(err){
  //error in saving - cleanup code
console.log(err);
});** 

Can you help me?

**Comment by gautamsi** [comment]
are you using html body? check #81. pull latest from npm if not already.

**Comment by Sennar81** [comment]
No, I read e-mail from file
If I remove the following line:
exch.ImpersonatedUserId = new ews.ImpersonatedUserId(ews.ConnectingIdType.SmtpAddress, 'usersmail@mail.com')
It works perfectly.
The problem is ImpersonatedUserId.
I connect in ews with administrative user.
how can I save an email to another mailbox ?

I thank you in advance
Best Regard
Giovanni

**Comment by gautamsi** [comment]
have you tried this [Configuring Exchange Impersonation in Exchange 2010](https://msdn.microsoft.com/en-us/library/office/bb204095(v=exchg.140).aspx)?

same should work for higher exchange version as well. 

I do not see the specific message in my test when it fails for impersonation.  You may have to pull the latest npm release if not already.

**Comment by Sennar81** [comment]
It works.
Thanks VERY MUCH
I used the following documentation: http://www.codetwo.com/kb/how-to-set-impersonation-rights-manually/

Kind Regards
Giovanni
