### ISSUE TITLE
SyncFolderItems does not expose incorrect userID/password

### ISSUE THREAD

**Issue by rousselle** [gautamsi/ews-javascript-api#83]
As far as I can tell, if I call SyncFolderItems with an incorrect userID/password combination, I do not get enough information back to be able to determine why the call failed. What I get back is an object that looks like this:

```js
{ faultCode: null,
  faultString: null,
  faultActor: null,
  responseCode: 127,
  message: null,
  errorCode: 0,
  exceptionType: null,
  lineNumber: 0,
  positionWithinLine: 0,
  errorDetails: { keys: [], keysToObjs: {}, objects: {}, keyPicker: [Function] } }
```

The only real information here is responseCode: 127, which corresponds to ErrorInternalServerError (https://github.com/gautamsi/ews-javascript-api/blob/master/typings/ExchangeWebService.d.ts#L9098). 

The API logging includes "Error in calling service, error code:401." Which suggests that the API is getting back an HTTP 401 from the server. Is there any way I can determine, programmatically, that the responseCode 127 was caused by the HTTP 401?

Thanks,
Philip

**Comment by gautamsi** [comment]
What you see is default state of `SoapFaultDetail` class.  I will add a field of HTTPStatus so that caller would know if this is 401 or 500.

**Comment by gautamsi** [comment]
.then error part with `SoapFaultDetails.Exception` is updated to be type `ServiceRequestUnauthorizedException` (ews.ServiceRequestUnauthorizedException) when there is invalid credential and 401 status code by server.
