### ISSUE TITLE
Unable to fetch files from a folder with FindItems(folderid, view), schema fault

### ISSUE THREAD

**Issue by picazi** [gautamsi/ews-javascript-api#84]
Hi Gautam,
I want to fetch new emails from my inbox folder. I am using a hosted exchange server.
But if I am using the exch.FindItems(folderid, view); method I am receiving a soap error (scroll down for stacktrace):

`[SoapFaultDetails.ParseMessageXml] Element: Violation - Please report example of this operation to ews-javascript-api repo to improve SoapFault parsing`

Here is the code I am using to access my inbox folder:

`var ews = require('ews-javascript-api');
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2013);

exch.Credentials = new ews.ExchangeCredentials("xxx@xxx.de", "xxx");
exch.Url = new ews.Uri("https://xxx/ews/Exchange.asmx");

var view = new ews.FolderView(5); //OK
var inbox = ews.WellKnownFolderName.Inbox; //OK
var folderid = new ews.FolderId(inbox); //OK

//ERROR
var items = exch.FindItems(folderid, view);
console.log(items);`

Here is the output of my variable items: 
`Violation:` 'Das Element \'FindItem\' in Namespace \'http://schemas.microsoft.com/exchange/services/2006/messages\' hat ein ungültiges untergeordnetes Element \'FolderShape\' in Namespace \'http://schemas.microsoft.com/exchange/services/2006/messages\'. Erwartet wurde die Liste der möglichen Elemente: \'ItemShape\' in Namespace \'http://schemas.microsoft.com/exchange/services/2006/messages\'.' } } } } }`

Full stacktrace:
https://gist.github.com/picazi/62289abc8866e06b5bb41ee2297dc8d6#file-ews-api

**Comment by gautamsi** [comment]
use `new ews.ItemView()` for the view not `FolderView`. you are trying to fetch items not folders.

also the line `var items = exch.FindItems(folderid, view);` not going to work as this library is Promise oriented. use it this way
```js
exch.FindItems(folderid, view).then(function <success>(items){
//do something with items;
// name of function is optional, just function(items) is also fine
},function <error>(errorObj_ServiceException_usually){

// do something with error

});
```

**Comment by picazi** [comment]
Hi,
and thanks for your fix. Yes you are absolutly right, calling a FolderView on an Item is a stupid idea...
My code works right now. But the code your posted does not work. Is this ES6 Code?
Sorry for my ignorance but I'm new on Javascript...

Thanks!

**Comment by gautamsi** [comment]
part of that was a pseudo code. remove `<success>` and `<error>` and it should start working.
