### ISSUE TITLE
AdjustUrl : Not implemented

### ISSUE THREAD

**Issue by jdneo** [gautamsi/ews-javascript-api#89]
When I use **ews.WebCredentials**, an error throws and it says: Error: WebCredentials.ts - AdjustUrl : Not implemented.
below is my code:

`var ews = require('ews-javascript-api');

var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2010);
ews.EwsLogging.DebugLogEnabled = true;

exch.Credentials = new ews.WebCredentials("user", "password");
exch.Url = new ews.Uri("https://exchange__host_server/ews/exchange.asmx");

var emailMessage = new ews.EmailMessage(exch);
emailMessage.Subject = "test";
emailMessage.Body = new ews.MessageBody("test");
emailMessage.ToRecipients.Add("user@domain.com");
emailMessage.Send().then(() => {
    console.log("------------");
}, (ei) => {
    console.log(ei.stack, ei.stack.split("\n"));
    console.log("------------");
});`

**Comment by gautamsi** [comment]
use `ExchangeCredentials` instead of `WebCredentials`

**Comment by jdneo** [comment]
Actually I was using ExchangeCredentials at first. But it always return code 401, and my credentials was right. And then I find issue#15 mentioned the same problem. Next I used the [ntlmXHRApi.js](https://gist.github.com/gautamsi/28211eda711e3e7dc04c) you mentioned in issue#15 and now the problem is solved. That's amazing and thank you so much for your help!
