### ISSUE TITLE
Couldn't find NTLM in the message type2 comming from the server

### ISSUE THREAD

**Issue by jdneo** [gautamsi/ews-javascript-api#93]
Hi

Several days ago, the server of the email account I am using was migrate to outlook.office365.com. So I change the ews URL to https://outlook.office365.com/ews/exchange.asmx. But the code throw an Error: **Couldn't find NTLM in the message type2 comming from the server**.

Here is my code: 
`
var ews = require('ews-javascript-api');
ews.EwsLogging.DebugLogEnabled = true;
var ntlmXHR = require("./ntlmXHRApi");

var ntlmXHRApi = new ntlmXHR.ntlmXHRApi('Domain\\name', 'pwd');
var exch = new ews.ExchangeService(ews.ExchangeVersion.Exchange2016);
exch.XHRApi = ntlmXHRApi;
exch.Credentials = new ews.ExchangeCredentials('Domain\\name', 'pwd');
exch.Url = new ews.Uri('https://outlook.office365.com/ews/exchange.asmx');

exch.GetPasswordExpirationDate("name@xxx.com").then(function(value){
    console.log("successsssssssssssssssssssssssssss");
    console.log(value);
    console.log(value.toString());
},function(value){
    console.log("Errorrrrrrrrrrrrrrrrrrrrrrrrrr");
    console.log(value);
});`

I'm sure the ews URL is right because the server database is on Office 365 currently

**Comment by jdneo** [comment]
Finally, i find the solution. Seems that the authentication of o365 can be without ntlm. Just use ews.ExchangeCredentials is enough. And the username should be filled in with 'xxx@domain.com' pattern.

**Comment by gautamsi** [comment]
Office 365 does not support ntlm, basic and oauth only. Oauth works only when you register your application in same azure tenant, cross tenant functionality does not work yet. Not available in this library yet.

**Comment by jdneo** [comment]
@gautamsi Got it. Thanks for replying.
