### ISSUE TITLE
SearchFilter collection not working

### ISSUE THREAD

**Issue by alkasain** [gautamsi/ews-javascript-api#96]
Hi Gautam,

Searchfiltercollection not working. I can only set one filter criteria and that is greater or less than filter not even ContainsSubstring working. Code that I used: 
       
       var startDate = new ews.DateTime("2016-09-14"); //Year, month, day
        var endDate = new ews.DateTime("2016-09-14");
       
        var greaterThanfilter = new ews.SearchFilter.IsGreaterThanOrEqualTo(
        ews.EmailMessageSchema.DateTimeReceived, startDate);

        var lessThanfilter = new ews.SearchFilter.IsLessThan(
            ews.EmailMessageSchema.DateTimeReceived, endDate);

        var filter = new ews.SearchFilter.SearchFilterCollection(ews.LogicalOperator.And, greaterThanfilter, lessThanfilter);

        var view = new ews.ItemView(10);
        exch.FindItems(ews.WellKnownFolderName.Inbox, filter, view).then(function(response) {
            console.log(response, true, true);
            var propSet = new ews.PropertySet(ews.BasePropertySet.IdOnly);
            propSet.Add(ews.ItemSchema.Subject);
            propSet.Add(ews.ItemSchema.Body);
            propSet.RequestedBodyType = ews.BodyType.Text;
            
            exch.LoadPropertiesForItems(response.Items, propSet)
            .then(function (data) {
                console.log("Getting data")
                console.log('Items Data', data);
                console.log(response.Items[0].PropertyBag.Properties.Items);
            }, function (err) {
                console.log(err);
            });
            
        }, function(error) {
            console.log(error)
        })

Error details are:
JSON.stringify(error): "{"faultCode":"a:ErrorSchemaValidation","faultString":{"xml:lang":"en-US","faultstring":"The request failed schema validation: The element 'And' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types' has incomplete content. List of possible elements expected: 'SearchExpression, Exists, Excludes, IsEqualTo, IsNotEqualTo, IsGreaterThan, IsGreaterThanOrEqualTo, IsLessThan, IsLessThanOrEqualTo, Contains, Not, And, Or, Near' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'."},"faultActor":null,"responseCode":355,"message":"The request failed schema validation.","errorCode":0,"exceptionType":null,"lineNumber":1,"positionWithinLine":601,"errorDetails":{"keys":["Violation"],"keysToObjs":{"Violation":"Violation"},"objects":{"Violation":"The element 'And' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types' has incomplete content. List of possible elements expected: 'SearchExpression, Exists, Excludes, IsEqualTo, IsNotEqualTo, IsGreaterThan, IsGreaterThanOrEqualTo, IsLessThan, IsLessThanOrEqualTo, Contains, Not, And, Or, Near' in namespace 'http://schemas.microsoft.com/exchange/services/2006/types'."}}}"

Thanks,
Alka Saini

**Comment by gautamsi** [comment]
can you also add here what was the xml generated.

**Comment by alkasain** [comment]
"<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2013"></t:RequestServerVersion></soap:Header><soap:Body><m:FindItem Traversal="Shallow"><m:ItemShape><t:BaseShape>AllProperties</t:BaseShape></m:ItemShape><m:IndexedPageItemView MaxEntriesReturned="10" Offset="0" BasePoint="Beginning"></m:IndexedPageItemView><m:Restriction><t:And></t:And></m:Restriction><m:ParentFolderIds><t:DistinguishedFolderId Id="inbox"></t:DistinguishedFolderId></m:ParentFolderIds></m:FindItem></soap:Body></soap:Envelope>"

**Comment by alkasain** [comment]
`"<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"><soap:Header><t:RequestServerVersion Version="Exchange2013"></t:RequestServerVersion></soap:Header><soap:Body><m:FindItem Traversal="Shallow"><m:ItemShape><t:BaseShape>AllProperties</t:BaseShape></m:ItemShape><m:IndexedPageItemView MaxEntriesReturned="10" Offset="0" BasePoint="Beginning"></m:IndexedPageItemView><m:Restriction><t:And></t:And></m:Restriction><m:ParentFolderIds><t:DistinguishedFolderId Id="inbox"></t:DistinguishedFolderId></m:ParentFolderIds></m:FindItem></soap:Body></soap:Envelope>"`

**Comment by gautamsi** [comment]
what happens when you change the `SearchFilterCollection` constructor like this
```js
var filter = new ews.SearchFilter.SearchFilterCollection(ews.LogicalOperator.And, [greaterThanfilter, lessThanfilter]);
```

what happens in c# is that it can have `params` as well as `Array[]` type in an overload, TypeScript however has issues and I have to do workaround in code. it is easier syntax in TypeScript/JavaScript to pass inline array than c# so I decided to not use many of the `params` style overload. you can just wrap the overload with `[` and `]` and you can continue down the path. 

you can make use of TypeScript definition files `ExchangeWebService.d.ts` from `Typings` folder from npm module. 

[vscode](https://github.com/Microsoft/vscode) is best way to use this typing file even for js project, it gives intellisense.

**Comment by alkasain** [comment]
I tried to use array[] as below:
var filter = new ews.SearchFilter.SearchFilterCollection(ews.LogicalOperator.And, [greaterThanfilter, lessThanfilter]);

and now getting another error:

Uncaught {"InnerException":null,"message":"Can not use non Array argument for searchFilters, c# params not supported","ParamName":"Can not use non Array argument for searchFilters, c# params not supported"}

**Comment by gautamsi** [comment]
I see what it is
there is a bug in `SearchFilter.SearchFilterCollection.js` change the Array checking like this:

from:
```js
if (searchFilters instanceof Array) {
```
to 
```js
if (ExtensionMethods_1.ArrayHelper.isArray(searchFilters)) {
```

```js
var SearchFilterCollection = (function (_super) {
    __extends(SearchFilterCollection, _super);
    //constructor(logicalOperator: LogicalOperator, ...searchFilters: SearchFilter[]);
    function SearchFilterCollection(logicalOperator, searchFilters) {
        if (logicalOperator === void 0) { logicalOperator = LogicalOperator_1.LogicalOperator.And; }
        if (searchFilters === void 0) { searchFilters = []; }
        _super.call(this);
        this.searchFilters = [];
        this.logicalOperator = LogicalOperator_1.LogicalOperator.And;
        if (arguments.length >= 1) {
            this.logicalOperator = logicalOperator;
        }
        if (arguments.length === 2) {
            if (ExtensionMethods_1.ArrayHelper.isArray(searchFilters)) {
                this.AddRange(searchFilters);
            }
            else {
                throw new ArgumentException_1.ArgumentOutOfRangeException("searchFilters", "Can not use non Array argument for searchFilters, c# params not supported");
            }
        }
    }
```

**Comment by alkasain** [comment]
Thanks this works now but ContainsSubstring filter is still giving error:

"The 'ContainmentMode' attribute is invalid - The value '2' is invalid according to its datatype 'http://schemas.microsoft.com/exchange/services/2006/types:ContainmentModeType' - The Enumeration constraint failed."

**Comment by gautamsi** [comment]
thanks for spotting bugs. this is another instance of enumeration serialization.
Make changes to `SearchFilter.ContainsSubstring.js` so that `WriteAttributesToXml ` looks like this.

```js
ContainsSubstring.prototype.WriteAttributesToXml = function (writer) {
        _super.prototype.WriteAttributesToXml.call(this, 

> writer);

        writer.WriteAttributeValue(XmlAttributeNames_1.XmlAttributeNames.ContainmentMode, ContainmentMode_1.ContainmentMode[this.ContainmentMode]);
        writer.WriteAttributeValue(XmlAttributeNames_1.XmlAttributeNames.ContainmentComparison, ComparisonMode_1.ComparisonMode[this.ComparisonMode]);
    };
```

**Comment by gautamsi** [comment]
re-opening as closed inappropriately from branch merging.
this fix also added support for `params` parameters to `SearchFilterCollection` constructor.
