### ISSUE TITLE
Can't update appointment item - TypeError

### ISSUE THREAD

**Issue by inkirby** [gautamsi/ews-javascript-api#98]
I've faced a problem while I trying to update an appointment item, these are what I've done:
- I bind an appointment to rawAppointment var
- then I update the rawAppointment
- lastly, I call the ExchangeService.UpdateItem

But the service thrown me an error about timezone header:
`[TypeError: item.GetIsTimeZoneHeaderRequired is not a function]`

I've tried assigning the function via a newly created appointment
`newAppointment = new ews.Appointment(exchangeService);`
`rawAppointment.GetIsTimeZoneHeaderRequired = newAppointment.GetIsTimeZoneHeaderRequired;`

And it thrown me another error:
`[TypeError: item.WriteToXmlForUpdate is not a function]`

I was follow that error and with the same solution and it thrown me a new type of error:
`[TypeError: Cannot read property 'WriteToXmlForUpdate' of undefined]`

Do you have any suggestions on this?

Thanks in advance.

---

the code:

`var ews = require('ews-javascript-api');
//exchangeService is an initialized ExchangeServer

...

ews.Appointment.Bind(exchangeService, new ews.ItemId("item-unique-id")
.done(function (result) {
	var rawAppointment = result.propertyBag.properties.objects;
	rawAppointment.Subject = event.title;
	rawAppointment.Body = new ews.MessageBody(event.details);
	rawAppointment.Start = moment(event.startTime.unix);
	rawAppointment.End = moment(event.endTime.unix);
	rawAppointment.Location = event.roomId;

	var mailbox = new ews.Mailbox("some@email.com");
	var calendarFolder = new ews.FolderId(ews.WellKnownFolderName.Calendar, mailbox);
	xchangeService.UpdateItem(rawAppointment, calendarFolder, ews.ConflictResolutionMode.AlwaysOverwrite,
				ews.MessageDisposition.SendAndSaveCopy, ews.SendInvitationsOrCancellationsMode.SendToAllAndSaveCopy)
	.done(function (updateResult) {
		console.log(updateResult);
	}, function (updateErr) {
		console.log(updateErr);
	});
}, function (err) {
	console.log(err);
});`

**Comment by gautamsi** [comment]
you  have to use `result` object as `rawAppointment`not the `result.propertyBag.properties.objects`

let me know if that helps.

**Comment by inkirby** [comment]
Thanks for the response.

That solved the above error, but it appears to have another error instead.

As I used `result` instead of `result.propertyBag.properties.objects`, the error was changed to this:
`[TypeError: dateTime.Format is not a function]`
even though the `moment(event.startTime.unix).isValid()` is `true`

I've tried to add/subtract the `DateTime` objects of the `rawAppointment` like this:
`rawAppointment.End.Add(timeDiff, 'ms');`
It fixed the error but the appointment time on Exchange wasn't changed.

**Comment by gautamsi** [comment]
`DateTime` instance methods are not modifying the date value, it just return the updated value. 

you have to use ` rawAppointment.End = rawAppointment.End.Add(timeDiff, 'ms');`  when changing existing date. 

for setting date parameters, use this
```js
rawAppointment.Start = new ews.DateTime(moment(event.startTime.unix));
//OR just
rawAppointment.Start = new ews.DateTime(event.startTime.unix);
```
DateTime passes constructor 1st args to `moment(1stArg)`

`DateTime` object is a custom wrapper around `moment`, it is not exactly `moment`.  I had to do this so that I do not have to modify copied code (from ews-managed-api repo). 

see [`DateTime.ts`](https://github.com/gautamsi/ews-javascript-api/blob/master/src/js/DateTime.ts) for more detail

**Comment by inkirby** [comment]
Thank you very much for your help, the issue is now solved. :D
